/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// EmailAlertsAPIService EmailAlertsAPI service
type EmailAlertsAPIService service

type ApiCreateEmailAlertV1EmailAlertsPostRequest struct {
	ctx context.Context
	ApiService *EmailAlertsAPIService
	createEmailAlertRequest *CreateEmailAlertRequest
}

func (r ApiCreateEmailAlertV1EmailAlertsPostRequest) CreateEmailAlertRequest(createEmailAlertRequest CreateEmailAlertRequest) ApiCreateEmailAlertV1EmailAlertsPostRequest {
	r.createEmailAlertRequest = &createEmailAlertRequest
	return r
}

func (r ApiCreateEmailAlertV1EmailAlertsPostRequest) Execute() (*EmailAlertItem, *http.Response, error) {
	return r.ApiService.CreateEmailAlertV1EmailAlertsPostExecute(r)
}

/*
CreateEmailAlertV1EmailAlertsPost Create email alert

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateEmailAlertV1EmailAlertsPostRequest
*/
func (a *EmailAlertsAPIService) CreateEmailAlertV1EmailAlertsPost(ctx context.Context) ApiCreateEmailAlertV1EmailAlertsPostRequest {
	return ApiCreateEmailAlertV1EmailAlertsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EmailAlertItem
func (a *EmailAlertsAPIService) CreateEmailAlertV1EmailAlertsPostExecute(r ApiCreateEmailAlertV1EmailAlertsPostRequest) (*EmailAlertItem, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmailAlertItem
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EmailAlertsAPIService.CreateEmailAlertV1EmailAlertsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/email-alerts"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createEmailAlertRequest == nil {
		return localVarReturnValue, nil, reportError("createEmailAlertRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createEmailAlertRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest struct {
	ctx context.Context
	ApiService *EmailAlertsAPIService
	alertId string
}

func (r ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest) Execute() (*EmailAlertMessageResponse, *http.Response, error) {
	return r.ApiService.DeleteEmailAlertV1EmailAlertsAlertIdDeleteExecute(r)
}

/*
DeleteEmailAlertV1EmailAlertsAlertIdDelete Delete email alert

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param alertId
 @return ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest
*/
func (a *EmailAlertsAPIService) DeleteEmailAlertV1EmailAlertsAlertIdDelete(ctx context.Context, alertId string) ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest {
	return ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		alertId: alertId,
	}
}

// Execute executes the request
//  @return EmailAlertMessageResponse
func (a *EmailAlertsAPIService) DeleteEmailAlertV1EmailAlertsAlertIdDeleteExecute(r ApiDeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest) (*EmailAlertMessageResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmailAlertMessageResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EmailAlertsAPIService.DeleteEmailAlertV1EmailAlertsAlertIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/email-alerts/{alert_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"alert_id"+"}", url.PathEscape(parameterValueToString(r.alertId, "alertId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListEmailAlertsV1EmailAlertsGetRequest struct {
	ctx context.Context
	ApiService *EmailAlertsAPIService
	page *int32
	limit *int32
}

func (r ApiListEmailAlertsV1EmailAlertsGetRequest) Page(page int32) ApiListEmailAlertsV1EmailAlertsGetRequest {
	r.page = &page
	return r
}

func (r ApiListEmailAlertsV1EmailAlertsGetRequest) Limit(limit int32) ApiListEmailAlertsV1EmailAlertsGetRequest {
	r.limit = &limit
	return r
}

func (r ApiListEmailAlertsV1EmailAlertsGetRequest) Execute() (*EmailAlertListResponse, *http.Response, error) {
	return r.ApiService.ListEmailAlertsV1EmailAlertsGetExecute(r)
}

/*
ListEmailAlertsV1EmailAlertsGet List email alerts

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListEmailAlertsV1EmailAlertsGetRequest
*/
func (a *EmailAlertsAPIService) ListEmailAlertsV1EmailAlertsGet(ctx context.Context) ApiListEmailAlertsV1EmailAlertsGetRequest {
	return ApiListEmailAlertsV1EmailAlertsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EmailAlertListResponse
func (a *EmailAlertsAPIService) ListEmailAlertsV1EmailAlertsGetExecute(r ApiListEmailAlertsV1EmailAlertsGetRequest) (*EmailAlertListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmailAlertListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EmailAlertsAPIService.ListEmailAlertsV1EmailAlertsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/email-alerts"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int32 = 1
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", defaultValue, "form", "")
		r.page = &defaultValue
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest struct {
	ctx context.Context
	ApiService *EmailAlertsAPIService
	alertId string
	updateEmailAlertRequest *UpdateEmailAlertRequest
}

func (r ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest) UpdateEmailAlertRequest(updateEmailAlertRequest UpdateEmailAlertRequest) ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest {
	r.updateEmailAlertRequest = &updateEmailAlertRequest
	return r
}

func (r ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest) Execute() (*EmailAlertMessageResponse, *http.Response, error) {
	return r.ApiService.UpdateEmailAlertV1EmailAlertsAlertIdPutExecute(r)
}

/*
UpdateEmailAlertV1EmailAlertsAlertIdPut Update email alert

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param alertId
 @return ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest
*/
func (a *EmailAlertsAPIService) UpdateEmailAlertV1EmailAlertsAlertIdPut(ctx context.Context, alertId string) ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest {
	return ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest{
		ApiService: a,
		ctx: ctx,
		alertId: alertId,
	}
}

// Execute executes the request
//  @return EmailAlertMessageResponse
func (a *EmailAlertsAPIService) UpdateEmailAlertV1EmailAlertsAlertIdPutExecute(r ApiUpdateEmailAlertV1EmailAlertsAlertIdPutRequest) (*EmailAlertMessageResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmailAlertMessageResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EmailAlertsAPIService.UpdateEmailAlertV1EmailAlertsAlertIdPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/email-alerts/{alert_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"alert_id"+"}", url.PathEscape(parameterValueToString(r.alertId, "alertId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateEmailAlertRequest == nil {
		return localVarReturnValue, nil, reportError("updateEmailAlertRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateEmailAlertRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
