/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
)


// WhatsappAPIService WhatsappAPI service
type WhatsappAPIService service

type ApiExtractConversationsV1WhatsappExtractConversationsPostRequest struct {
	ctx context.Context
	ApiService *WhatsappAPIService
	file *os.File
	start *string
	end *string
	timezone *string
	dateFormat *string
	gapMinutes *float32
	minMessages *int32
	charsPerMinute *float32
	clientReferenceId *string
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) File(file *os.File) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.file = file
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) Start(start string) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.start = &start
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) End(end string) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.end = &end
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) Timezone(timezone string) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.timezone = &timezone
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) DateFormat(dateFormat string) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.dateFormat = &dateFormat
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) GapMinutes(gapMinutes float32) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.gapMinutes = &gapMinutes
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) MinMessages(minMessages int32) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.minMessages = &minMessages
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) CharsPerMinute(charsPerMinute float32) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.charsPerMinute = &charsPerMinute
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) ClientReferenceId(clientReferenceId string) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	r.clientReferenceId = &clientReferenceId
	return r
}

func (r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) Execute() (*WhatsappConversationsResponse, *http.Response, error) {
	return r.ApiService.ExtractConversationsV1WhatsappExtractConversationsPostExecute(r)
}

/*
ExtractConversationsV1WhatsappExtractConversationsPost Extract and segment WhatsApp conversations from an export

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiExtractConversationsV1WhatsappExtractConversationsPostRequest
*/
func (a *WhatsappAPIService) ExtractConversationsV1WhatsappExtractConversationsPost(ctx context.Context) ApiExtractConversationsV1WhatsappExtractConversationsPostRequest {
	return ApiExtractConversationsV1WhatsappExtractConversationsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WhatsappConversationsResponse
func (a *WhatsappAPIService) ExtractConversationsV1WhatsappExtractConversationsPostExecute(r ApiExtractConversationsV1WhatsappExtractConversationsPostRequest) (*WhatsappConversationsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WhatsappConversationsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WhatsappAPIService.ExtractConversationsV1WhatsappExtractConversationsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/whatsapp/extractConversations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}
	if r.start == nil {
		return localVarReturnValue, nil, reportError("start is required and must be specified")
	}
	if r.end == nil {
		return localVarReturnValue, nil, reportError("end is required and must be specified")
	}
	if r.timezone == nil {
		return localVarReturnValue, nil, reportError("timezone is required and must be specified")
	}
	if r.dateFormat == nil {
		return localVarReturnValue, nil, reportError("dateFormat is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	parameterAddToHeaderOrQuery(localVarFormParams, "start", r.start, "", "")
	parameterAddToHeaderOrQuery(localVarFormParams, "end", r.end, "", "")
	parameterAddToHeaderOrQuery(localVarFormParams, "timezone", r.timezone, "", "")
	parameterAddToHeaderOrQuery(localVarFormParams, "date_format", r.dateFormat, "", "")
	if r.gapMinutes != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "gap_minutes", r.gapMinutes, "", "")
	}
	if r.minMessages != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "min_messages", r.minMessages, "", "")
	}
	if r.charsPerMinute != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "chars_per_minute", r.charsPerMinute, "", "")
	}
	if r.clientReferenceId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "client_reference_id", r.clientReferenceId, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
