/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditParticipantsV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditParticipantsV2{}

// RiskAuditParticipantsV2 struct for RiskAuditParticipantsV2
type RiskAuditParticipantsV2 struct {
	// Identified participants
	Identified []RiskAuditParticipantV2 `json:"identified,omitempty"`
	// inbound/outbound
	CallDirection *string `json:"call_direction,omitempty"`
	// Role inference reliability
	RoleInferenceReliable *bool `json:"role_inference_reliable,omitempty"`
	// Identification status
	IdentificationStatus *string `json:"identification_status,omitempty"`
	// Unidentified items count
	UnidentifiedItemsCount *int32 `json:"unidentified_items_count,omitempty"`
}

// NewRiskAuditParticipantsV2 instantiates a new RiskAuditParticipantsV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditParticipantsV2() *RiskAuditParticipantsV2 {
	this := RiskAuditParticipantsV2{}
	var roleInferenceReliable bool = true
	this.RoleInferenceReliable = &roleInferenceReliable
	var identificationStatus string = "none"
	this.IdentificationStatus = &identificationStatus
	var unidentifiedItemsCount int32 = 0
	this.UnidentifiedItemsCount = &unidentifiedItemsCount
	return &this
}

// NewRiskAuditParticipantsV2WithDefaults instantiates a new RiskAuditParticipantsV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditParticipantsV2WithDefaults() *RiskAuditParticipantsV2 {
	this := RiskAuditParticipantsV2{}
	var roleInferenceReliable bool = true
	this.RoleInferenceReliable = &roleInferenceReliable
	var identificationStatus string = "none"
	this.IdentificationStatus = &identificationStatus
	var unidentifiedItemsCount int32 = 0
	this.UnidentifiedItemsCount = &unidentifiedItemsCount
	return &this
}

// GetIdentified returns the Identified field value if set, zero value otherwise.
func (o *RiskAuditParticipantsV2) GetIdentified() []RiskAuditParticipantV2 {
	if o == nil || IsNil(o.Identified) {
		var ret []RiskAuditParticipantV2
		return ret
	}
	return o.Identified
}

// GetIdentifiedOk returns a tuple with the Identified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditParticipantsV2) GetIdentifiedOk() ([]RiskAuditParticipantV2, bool) {
	if o == nil || IsNil(o.Identified) {
		return nil, false
	}
	return o.Identified, true
}

// HasIdentified returns a boolean if a field has been set.
func (o *RiskAuditParticipantsV2) HasIdentified() bool {
	if o != nil && !IsNil(o.Identified) {
		return true
	}

	return false
}

// SetIdentified gets a reference to the given []RiskAuditParticipantV2 and assigns it to the Identified field.
func (o *RiskAuditParticipantsV2) SetIdentified(v []RiskAuditParticipantV2) {
	o.Identified = v
}

// GetCallDirection returns the CallDirection field value if set, zero value otherwise.
func (o *RiskAuditParticipantsV2) GetCallDirection() string {
	if o == nil || IsNil(o.CallDirection) {
		var ret string
		return ret
	}
	return *o.CallDirection
}

// GetCallDirectionOk returns a tuple with the CallDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditParticipantsV2) GetCallDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.CallDirection) {
		return nil, false
	}
	return o.CallDirection, true
}

// HasCallDirection returns a boolean if a field has been set.
func (o *RiskAuditParticipantsV2) HasCallDirection() bool {
	if o != nil && !IsNil(o.CallDirection) {
		return true
	}

	return false
}

// SetCallDirection gets a reference to the given string and assigns it to the CallDirection field.
func (o *RiskAuditParticipantsV2) SetCallDirection(v string) {
	o.CallDirection = &v
}

// GetRoleInferenceReliable returns the RoleInferenceReliable field value if set, zero value otherwise.
func (o *RiskAuditParticipantsV2) GetRoleInferenceReliable() bool {
	if o == nil || IsNil(o.RoleInferenceReliable) {
		var ret bool
		return ret
	}
	return *o.RoleInferenceReliable
}

// GetRoleInferenceReliableOk returns a tuple with the RoleInferenceReliable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditParticipantsV2) GetRoleInferenceReliableOk() (*bool, bool) {
	if o == nil || IsNil(o.RoleInferenceReliable) {
		return nil, false
	}
	return o.RoleInferenceReliable, true
}

// HasRoleInferenceReliable returns a boolean if a field has been set.
func (o *RiskAuditParticipantsV2) HasRoleInferenceReliable() bool {
	if o != nil && !IsNil(o.RoleInferenceReliable) {
		return true
	}

	return false
}

// SetRoleInferenceReliable gets a reference to the given bool and assigns it to the RoleInferenceReliable field.
func (o *RiskAuditParticipantsV2) SetRoleInferenceReliable(v bool) {
	o.RoleInferenceReliable = &v
}

// GetIdentificationStatus returns the IdentificationStatus field value if set, zero value otherwise.
func (o *RiskAuditParticipantsV2) GetIdentificationStatus() string {
	if o == nil || IsNil(o.IdentificationStatus) {
		var ret string
		return ret
	}
	return *o.IdentificationStatus
}

// GetIdentificationStatusOk returns a tuple with the IdentificationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditParticipantsV2) GetIdentificationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.IdentificationStatus) {
		return nil, false
	}
	return o.IdentificationStatus, true
}

// HasIdentificationStatus returns a boolean if a field has been set.
func (o *RiskAuditParticipantsV2) HasIdentificationStatus() bool {
	if o != nil && !IsNil(o.IdentificationStatus) {
		return true
	}

	return false
}

// SetIdentificationStatus gets a reference to the given string and assigns it to the IdentificationStatus field.
func (o *RiskAuditParticipantsV2) SetIdentificationStatus(v string) {
	o.IdentificationStatus = &v
}

// GetUnidentifiedItemsCount returns the UnidentifiedItemsCount field value if set, zero value otherwise.
func (o *RiskAuditParticipantsV2) GetUnidentifiedItemsCount() int32 {
	if o == nil || IsNil(o.UnidentifiedItemsCount) {
		var ret int32
		return ret
	}
	return *o.UnidentifiedItemsCount
}

// GetUnidentifiedItemsCountOk returns a tuple with the UnidentifiedItemsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditParticipantsV2) GetUnidentifiedItemsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnidentifiedItemsCount) {
		return nil, false
	}
	return o.UnidentifiedItemsCount, true
}

// HasUnidentifiedItemsCount returns a boolean if a field has been set.
func (o *RiskAuditParticipantsV2) HasUnidentifiedItemsCount() bool {
	if o != nil && !IsNil(o.UnidentifiedItemsCount) {
		return true
	}

	return false
}

// SetUnidentifiedItemsCount gets a reference to the given int32 and assigns it to the UnidentifiedItemsCount field.
func (o *RiskAuditParticipantsV2) SetUnidentifiedItemsCount(v int32) {
	o.UnidentifiedItemsCount = &v
}

func (o RiskAuditParticipantsV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditParticipantsV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identified) {
		toSerialize["identified"] = o.Identified
	}
	if !IsNil(o.CallDirection) {
		toSerialize["call_direction"] = o.CallDirection
	}
	if !IsNil(o.RoleInferenceReliable) {
		toSerialize["role_inference_reliable"] = o.RoleInferenceReliable
	}
	if !IsNil(o.IdentificationStatus) {
		toSerialize["identification_status"] = o.IdentificationStatus
	}
	if !IsNil(o.UnidentifiedItemsCount) {
		toSerialize["unidentified_items_count"] = o.UnidentifiedItemsCount
	}
	return toSerialize, nil
}

type NullableRiskAuditParticipantsV2 struct {
	value *RiskAuditParticipantsV2
	isSet bool
}

func (v NullableRiskAuditParticipantsV2) Get() *RiskAuditParticipantsV2 {
	return v.value
}

func (v *NullableRiskAuditParticipantsV2) Set(val *RiskAuditParticipantsV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditParticipantsV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditParticipantsV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditParticipantsV2(val *RiskAuditParticipantsV2) *NullableRiskAuditParticipantsV2 {
	return &NullableRiskAuditParticipantsV2{value: val, isSet: true}
}

func (v NullableRiskAuditParticipantsV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditParticipantsV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


