/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AudioInputMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioInputMeta{}

// AudioInputMeta struct for AudioInputMeta
type AudioInputMeta struct {
	// Exact audio duration sent in seconds
	DurationS float32 `json:"duration_s"`
	// Original file format (wav, mp3, ogg, etc)
	OriginalFormat string `json:"original_format"`
	// Audio codec sent
	Codec string `json:"codec"`
	// Audio sample rate in Hz
	SampleRate int32 `json:"sample_rate"`
	// Number of channels (1=mono, 2=stereo)
	Channels int32 `json:"channels"`
}

type _AudioInputMeta AudioInputMeta

// NewAudioInputMeta instantiates a new AudioInputMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioInputMeta(durationS float32, originalFormat string, codec string, sampleRate int32, channels int32) *AudioInputMeta {
	this := AudioInputMeta{}
	this.DurationS = durationS
	this.OriginalFormat = originalFormat
	this.Codec = codec
	this.SampleRate = sampleRate
	this.Channels = channels
	return &this
}

// NewAudioInputMetaWithDefaults instantiates a new AudioInputMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioInputMetaWithDefaults() *AudioInputMeta {
	this := AudioInputMeta{}
	return &this
}

// GetDurationS returns the DurationS field value
func (o *AudioInputMeta) GetDurationS() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationS
}

// GetDurationSOk returns a tuple with the DurationS field value
// and a boolean to check if the value has been set.
func (o *AudioInputMeta) GetDurationSOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationS, true
}

// SetDurationS sets field value
func (o *AudioInputMeta) SetDurationS(v float32) {
	o.DurationS = v
}

// GetOriginalFormat returns the OriginalFormat field value
func (o *AudioInputMeta) GetOriginalFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalFormat
}

// GetOriginalFormatOk returns a tuple with the OriginalFormat field value
// and a boolean to check if the value has been set.
func (o *AudioInputMeta) GetOriginalFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalFormat, true
}

// SetOriginalFormat sets field value
func (o *AudioInputMeta) SetOriginalFormat(v string) {
	o.OriginalFormat = v
}

// GetCodec returns the Codec field value
func (o *AudioInputMeta) GetCodec() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Codec
}

// GetCodecOk returns a tuple with the Codec field value
// and a boolean to check if the value has been set.
func (o *AudioInputMeta) GetCodecOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Codec, true
}

// SetCodec sets field value
func (o *AudioInputMeta) SetCodec(v string) {
	o.Codec = v
}

// GetSampleRate returns the SampleRate field value
func (o *AudioInputMeta) GetSampleRate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SampleRate
}

// GetSampleRateOk returns a tuple with the SampleRate field value
// and a boolean to check if the value has been set.
func (o *AudioInputMeta) GetSampleRateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SampleRate, true
}

// SetSampleRate sets field value
func (o *AudioInputMeta) SetSampleRate(v int32) {
	o.SampleRate = v
}

// GetChannels returns the Channels field value
func (o *AudioInputMeta) GetChannels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *AudioInputMeta) GetChannelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channels, true
}

// SetChannels sets field value
func (o *AudioInputMeta) SetChannels(v int32) {
	o.Channels = v
}

func (o AudioInputMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioInputMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration_s"] = o.DurationS
	toSerialize["original_format"] = o.OriginalFormat
	toSerialize["codec"] = o.Codec
	toSerialize["sample_rate"] = o.SampleRate
	toSerialize["channels"] = o.Channels
	return toSerialize, nil
}

func (o *AudioInputMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration_s",
		"original_format",
		"codec",
		"sample_rate",
		"channels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudioInputMeta := _AudioInputMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAudioInputMeta)

	if err != nil {
		return err
	}

	*o = AudioInputMeta(varAudioInputMeta)

	return err
}

type NullableAudioInputMeta struct {
	value *AudioInputMeta
	isSet bool
}

func (v NullableAudioInputMeta) Get() *AudioInputMeta {
	return v.value
}

func (v *NullableAudioInputMeta) Set(val *AudioInputMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioInputMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioInputMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioInputMeta(val *AudioInputMeta) *NullableAudioInputMeta {
	return &NullableAudioInputMeta{value: val, isSet: true}
}

func (v NullableAudioInputMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioInputMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


