/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskAuditAppliedActionV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditAppliedActionV2{}

// RiskAuditAppliedActionV2 struct for RiskAuditAppliedActionV2
type RiskAuditAppliedActionV2 struct {
	// Action type code
	ActionType string `json:"action_type"`
	// Action label
	Label string `json:"label"`
	// Action description
	Description string `json:"description"`
	// CRITICO/ALTO/MEDIO/BAIXO
	Priority string `json:"priority"`
	// Color
	Color *string `json:"color,omitempty"`
	// Icon
	Icon *string `json:"icon,omitempty"`
	// Condition
	Condition *string `json:"condition,omitempty"`
	// Reason
	Reason *string `json:"reason,omitempty"`
}

type _RiskAuditAppliedActionV2 RiskAuditAppliedActionV2

// NewRiskAuditAppliedActionV2 instantiates a new RiskAuditAppliedActionV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditAppliedActionV2(actionType string, label string, description string, priority string) *RiskAuditAppliedActionV2 {
	this := RiskAuditAppliedActionV2{}
	this.ActionType = actionType
	this.Label = label
	this.Description = description
	this.Priority = priority
	var color string = ""
	this.Color = &color
	var icon string = ""
	this.Icon = &icon
	var reason string = ""
	this.Reason = &reason
	return &this
}

// NewRiskAuditAppliedActionV2WithDefaults instantiates a new RiskAuditAppliedActionV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditAppliedActionV2WithDefaults() *RiskAuditAppliedActionV2 {
	this := RiskAuditAppliedActionV2{}
	var color string = ""
	this.Color = &color
	var icon string = ""
	this.Icon = &icon
	var reason string = ""
	this.Reason = &reason
	return &this
}

// GetActionType returns the ActionType field value
func (o *RiskAuditAppliedActionV2) GetActionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionType
}

// GetActionTypeOk returns a tuple with the ActionType field value
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetActionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionType, true
}

// SetActionType sets field value
func (o *RiskAuditAppliedActionV2) SetActionType(v string) {
	o.ActionType = v
}

// GetLabel returns the Label field value
func (o *RiskAuditAppliedActionV2) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *RiskAuditAppliedActionV2) SetLabel(v string) {
	o.Label = v
}

// GetDescription returns the Description field value
func (o *RiskAuditAppliedActionV2) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RiskAuditAppliedActionV2) SetDescription(v string) {
	o.Description = v
}

// GetPriority returns the Priority field value
func (o *RiskAuditAppliedActionV2) GetPriority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetPriorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *RiskAuditAppliedActionV2) SetPriority(v string) {
	o.Priority = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *RiskAuditAppliedActionV2) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *RiskAuditAppliedActionV2) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *RiskAuditAppliedActionV2) SetColor(v string) {
	o.Color = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *RiskAuditAppliedActionV2) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *RiskAuditAppliedActionV2) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *RiskAuditAppliedActionV2) SetIcon(v string) {
	o.Icon = &v
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *RiskAuditAppliedActionV2) GetCondition() string {
	if o == nil || IsNil(o.Condition) {
		var ret string
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetConditionOk() (*string, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *RiskAuditAppliedActionV2) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given string and assigns it to the Condition field.
func (o *RiskAuditAppliedActionV2) SetCondition(v string) {
	o.Condition = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *RiskAuditAppliedActionV2) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAppliedActionV2) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *RiskAuditAppliedActionV2) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *RiskAuditAppliedActionV2) SetReason(v string) {
	o.Reason = &v
}

func (o RiskAuditAppliedActionV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditAppliedActionV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action_type"] = o.ActionType
	toSerialize["label"] = o.Label
	toSerialize["description"] = o.Description
	toSerialize["priority"] = o.Priority
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *RiskAuditAppliedActionV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action_type",
		"label",
		"description",
		"priority",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditAppliedActionV2 := _RiskAuditAppliedActionV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskAuditAppliedActionV2)

	if err != nil {
		return err
	}

	*o = RiskAuditAppliedActionV2(varRiskAuditAppliedActionV2)

	return err
}

type NullableRiskAuditAppliedActionV2 struct {
	value *RiskAuditAppliedActionV2
	isSet bool
}

func (v NullableRiskAuditAppliedActionV2) Get() *RiskAuditAppliedActionV2 {
	return v.value
}

func (v *NullableRiskAuditAppliedActionV2) Set(val *RiskAuditAppliedActionV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditAppliedActionV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditAppliedActionV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditAppliedActionV2(val *RiskAuditAppliedActionV2) *NullableRiskAuditAppliedActionV2 {
	return &NullableRiskAuditAppliedActionV2{value: val, isSet: true}
}

func (v NullableRiskAuditAppliedActionV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditAppliedActionV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


