/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditVerdictV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditVerdictV2{}

// RiskAuditVerdictV2 struct for RiskAuditVerdictV2
type RiskAuditVerdictV2 struct {
	// Human-readable verdict
	Label *string `json:"label,omitempty"`
	// Classification level code
	LevelCode *string `json:"level_code,omitempty"`
	// Level color
	Color *string `json:"color,omitempty"`
	// Level icon
	Icon *string `json:"icon,omitempty"`
	// Risk matrix
	RiskMatrix map[string]interface{} `json:"risk_matrix,omitempty"`
	// Applied actions
	AppliedActions []RiskAuditAppliedActionV2 `json:"applied_actions,omitempty"`
	// Decision details
	DecisionDetails interface{} `json:"decision_details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditVerdictV2 RiskAuditVerdictV2

// NewRiskAuditVerdictV2 instantiates a new RiskAuditVerdictV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditVerdictV2() *RiskAuditVerdictV2 {
	this := RiskAuditVerdictV2{}
	return &this
}

// NewRiskAuditVerdictV2WithDefaults instantiates a new RiskAuditVerdictV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditVerdictV2WithDefaults() *RiskAuditVerdictV2 {
	this := RiskAuditVerdictV2{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *RiskAuditVerdictV2) SetLabel(v string) {
	o.Label = &v
}

// GetLevelCode returns the LevelCode field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetLevelCode() string {
	if o == nil || IsNil(o.LevelCode) {
		var ret string
		return ret
	}
	return *o.LevelCode
}

// GetLevelCodeOk returns a tuple with the LevelCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetLevelCodeOk() (*string, bool) {
	if o == nil || IsNil(o.LevelCode) {
		return nil, false
	}
	return o.LevelCode, true
}

// HasLevelCode returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasLevelCode() bool {
	if o != nil && !IsNil(o.LevelCode) {
		return true
	}

	return false
}

// SetLevelCode gets a reference to the given string and assigns it to the LevelCode field.
func (o *RiskAuditVerdictV2) SetLevelCode(v string) {
	o.LevelCode = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *RiskAuditVerdictV2) SetColor(v string) {
	o.Color = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *RiskAuditVerdictV2) SetIcon(v string) {
	o.Icon = &v
}

// GetRiskMatrix returns the RiskMatrix field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetRiskMatrix() map[string]interface{} {
	if o == nil || IsNil(o.RiskMatrix) {
		var ret map[string]interface{}
		return ret
	}
	return o.RiskMatrix
}

// GetRiskMatrixOk returns a tuple with the RiskMatrix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetRiskMatrixOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RiskMatrix) {
		return map[string]interface{}{}, false
	}
	return o.RiskMatrix, true
}

// HasRiskMatrix returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasRiskMatrix() bool {
	if o != nil && !IsNil(o.RiskMatrix) {
		return true
	}

	return false
}

// SetRiskMatrix gets a reference to the given map[string]interface{} and assigns it to the RiskMatrix field.
func (o *RiskAuditVerdictV2) SetRiskMatrix(v map[string]interface{}) {
	o.RiskMatrix = v
}

// GetAppliedActions returns the AppliedActions field value if set, zero value otherwise.
func (o *RiskAuditVerdictV2) GetAppliedActions() []RiskAuditAppliedActionV2 {
	if o == nil || IsNil(o.AppliedActions) {
		var ret []RiskAuditAppliedActionV2
		return ret
	}
	return o.AppliedActions
}

// GetAppliedActionsOk returns a tuple with the AppliedActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditVerdictV2) GetAppliedActionsOk() ([]RiskAuditAppliedActionV2, bool) {
	if o == nil || IsNil(o.AppliedActions) {
		return nil, false
	}
	return o.AppliedActions, true
}

// HasAppliedActions returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasAppliedActions() bool {
	if o != nil && !IsNil(o.AppliedActions) {
		return true
	}

	return false
}

// SetAppliedActions gets a reference to the given []RiskAuditAppliedActionV2 and assigns it to the AppliedActions field.
func (o *RiskAuditVerdictV2) SetAppliedActions(v []RiskAuditAppliedActionV2) {
	o.AppliedActions = v
}

// GetDecisionDetails returns the DecisionDetails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditVerdictV2) GetDecisionDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DecisionDetails
}

// GetDecisionDetailsOk returns a tuple with the DecisionDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditVerdictV2) GetDecisionDetailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DecisionDetails) {
		return nil, false
	}
	return &o.DecisionDetails, true
}

// HasDecisionDetails returns a boolean if a field has been set.
func (o *RiskAuditVerdictV2) HasDecisionDetails() bool {
	if o != nil && !IsNil(o.DecisionDetails) {
		return true
	}

	return false
}

// SetDecisionDetails gets a reference to the given interface{} and assigns it to the DecisionDetails field.
func (o *RiskAuditVerdictV2) SetDecisionDetails(v interface{}) {
	o.DecisionDetails = v
}

func (o RiskAuditVerdictV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditVerdictV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.LevelCode) {
		toSerialize["level_code"] = o.LevelCode
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.RiskMatrix) {
		toSerialize["risk_matrix"] = o.RiskMatrix
	}
	if !IsNil(o.AppliedActions) {
		toSerialize["applied_actions"] = o.AppliedActions
	}
	if o.DecisionDetails != nil {
		toSerialize["decision_details"] = o.DecisionDetails
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditVerdictV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditVerdictV2 := _RiskAuditVerdictV2{}

	err = json.Unmarshal(data, &varRiskAuditVerdictV2)

	if err != nil {
		return err
	}

	*o = RiskAuditVerdictV2(varRiskAuditVerdictV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "label")
		delete(additionalProperties, "level_code")
		delete(additionalProperties, "color")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "risk_matrix")
		delete(additionalProperties, "applied_actions")
		delete(additionalProperties, "decision_details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditVerdictV2 struct {
	value *RiskAuditVerdictV2
	isSet bool
}

func (v NullableRiskAuditVerdictV2) Get() *RiskAuditVerdictV2 {
	return v.value
}

func (v *NullableRiskAuditVerdictV2) Set(val *RiskAuditVerdictV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditVerdictV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditVerdictV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditVerdictV2(val *RiskAuditVerdictV2) *NullableRiskAuditVerdictV2 {
	return &NullableRiskAuditVerdictV2{value: val, isSet: true}
}

func (v NullableRiskAuditVerdictV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditVerdictV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


