/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageLogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageLogResponse{}

// UsageLogResponse struct for UsageLogResponse
type UsageLogResponse struct {
	Data []UsageLogItem `json:"data"`
	Page int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type _UsageLogResponse UsageLogResponse

// NewUsageLogResponse instantiates a new UsageLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageLogResponse(data []UsageLogItem, page int32, limit int32) *UsageLogResponse {
	this := UsageLogResponse{}
	this.Data = data
	this.Page = page
	this.Limit = limit
	return &this
}

// NewUsageLogResponseWithDefaults instantiates a new UsageLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageLogResponseWithDefaults() *UsageLogResponse {
	this := UsageLogResponse{}
	return &this
}

// GetData returns the Data field value
func (o *UsageLogResponse) GetData() []UsageLogItem {
	if o == nil {
		var ret []UsageLogItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UsageLogResponse) GetDataOk() ([]UsageLogItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *UsageLogResponse) SetData(v []UsageLogItem) {
	o.Data = v
}

// GetPage returns the Page field value
func (o *UsageLogResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *UsageLogResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *UsageLogResponse) SetPage(v int32) {
	o.Page = v
}

// GetLimit returns the Limit field value
func (o *UsageLogResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *UsageLogResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *UsageLogResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o UsageLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageLogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["page"] = o.Page
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

func (o *UsageLogResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"page",
		"limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageLogResponse := _UsageLogResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageLogResponse)

	if err != nil {
		return err
	}

	*o = UsageLogResponse(varUsageLogResponse)

	return err
}

type NullableUsageLogResponse struct {
	value *UsageLogResponse
	isSet bool
}

func (v NullableUsageLogResponse) Get() *UsageLogResponse {
	return v.value
}

func (v *NullableUsageLogResponse) Set(val *UsageLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageLogResponse(val *UsageLogResponse) *NullableUsageLogResponse {
	return &NullableUsageLogResponse{value: val, isSet: true}
}

func (v NullableUsageLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


