/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WhatsappConversation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsappConversation{}

// WhatsappConversation struct for WhatsappConversation
type WhatsappConversation struct {
	// Conversation identifier in the batch
	ConversationId string `json:"conversation_id"`
	// Real start (wall-clock, ISO)
	FirstAt string `json:"first_at"`
	// Real end (wall-clock, ISO)
	LastAt string `json:"last_at"`
	// (last - first) + last turn duration
	DurationSeconds float32 `json:"duration_seconds"`
	// Speakers of THIS conversation (dynamic)
	Speakers []WhatsappSpeaker `json:"speakers"`
	// Lines 'Speaker N: [HH:MM:SS.mmm - HH:MM:SS.mmm] text' (real offset)
	Dialog string `json:"dialog"`
	// Number of messages
	MessageCount int32 `json:"message_count"`
	// Total characters of the conversation
	Characters int32 `json:"characters"`
}

type _WhatsappConversation WhatsappConversation

// NewWhatsappConversation instantiates a new WhatsappConversation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappConversation(conversationId string, firstAt string, lastAt string, durationSeconds float32, speakers []WhatsappSpeaker, dialog string, messageCount int32, characters int32) *WhatsappConversation {
	this := WhatsappConversation{}
	this.ConversationId = conversationId
	this.FirstAt = firstAt
	this.LastAt = lastAt
	this.DurationSeconds = durationSeconds
	this.Speakers = speakers
	this.Dialog = dialog
	this.MessageCount = messageCount
	this.Characters = characters
	return &this
}

// NewWhatsappConversationWithDefaults instantiates a new WhatsappConversation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappConversationWithDefaults() *WhatsappConversation {
	this := WhatsappConversation{}
	return &this
}

// GetConversationId returns the ConversationId field value
func (o *WhatsappConversation) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *WhatsappConversation) SetConversationId(v string) {
	o.ConversationId = v
}

// GetFirstAt returns the FirstAt field value
func (o *WhatsappConversation) GetFirstAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstAt
}

// GetFirstAtOk returns a tuple with the FirstAt field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetFirstAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstAt, true
}

// SetFirstAt sets field value
func (o *WhatsappConversation) SetFirstAt(v string) {
	o.FirstAt = v
}

// GetLastAt returns the LastAt field value
func (o *WhatsappConversation) GetLastAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastAt
}

// GetLastAtOk returns a tuple with the LastAt field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetLastAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastAt, true
}

// SetLastAt sets field value
func (o *WhatsappConversation) SetLastAt(v string) {
	o.LastAt = v
}

// GetDurationSeconds returns the DurationSeconds field value
func (o *WhatsappConversation) GetDurationSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationSeconds, true
}

// SetDurationSeconds sets field value
func (o *WhatsappConversation) SetDurationSeconds(v float32) {
	o.DurationSeconds = v
}

// GetSpeakers returns the Speakers field value
func (o *WhatsappConversation) GetSpeakers() []WhatsappSpeaker {
	if o == nil {
		var ret []WhatsappSpeaker
		return ret
	}

	return o.Speakers
}

// GetSpeakersOk returns a tuple with the Speakers field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetSpeakersOk() ([]WhatsappSpeaker, bool) {
	if o == nil {
		return nil, false
	}
	return o.Speakers, true
}

// SetSpeakers sets field value
func (o *WhatsappConversation) SetSpeakers(v []WhatsappSpeaker) {
	o.Speakers = v
}

// GetDialog returns the Dialog field value
func (o *WhatsappConversation) GetDialog() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dialog
}

// GetDialogOk returns a tuple with the Dialog field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetDialogOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dialog, true
}

// SetDialog sets field value
func (o *WhatsappConversation) SetDialog(v string) {
	o.Dialog = v
}

// GetMessageCount returns the MessageCount field value
func (o *WhatsappConversation) GetMessageCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MessageCount
}

// GetMessageCountOk returns a tuple with the MessageCount field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetMessageCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageCount, true
}

// SetMessageCount sets field value
func (o *WhatsappConversation) SetMessageCount(v int32) {
	o.MessageCount = v
}

// GetCharacters returns the Characters field value
func (o *WhatsappConversation) GetCharacters() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Characters
}

// GetCharactersOk returns a tuple with the Characters field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversation) GetCharactersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Characters, true
}

// SetCharacters sets field value
func (o *WhatsappConversation) SetCharacters(v int32) {
	o.Characters = v
}

func (o WhatsappConversation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsappConversation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conversation_id"] = o.ConversationId
	toSerialize["first_at"] = o.FirstAt
	toSerialize["last_at"] = o.LastAt
	toSerialize["duration_seconds"] = o.DurationSeconds
	toSerialize["speakers"] = o.Speakers
	toSerialize["dialog"] = o.Dialog
	toSerialize["message_count"] = o.MessageCount
	toSerialize["characters"] = o.Characters
	return toSerialize, nil
}

func (o *WhatsappConversation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conversation_id",
		"first_at",
		"last_at",
		"duration_seconds",
		"speakers",
		"dialog",
		"message_count",
		"characters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsappConversation := _WhatsappConversation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsappConversation)

	if err != nil {
		return err
	}

	*o = WhatsappConversation(varWhatsappConversation)

	return err
}

type NullableWhatsappConversation struct {
	value *WhatsappConversation
	isSet bool
}

func (v NullableWhatsappConversation) Get() *WhatsappConversation {
	return v.value
}

func (v *NullableWhatsappConversation) Set(val *WhatsappConversation) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappConversation) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappConversation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappConversation(val *WhatsappConversation) *NullableWhatsappConversation {
	return &NullableWhatsappConversation{value: val, isSet: true}
}

func (v NullableWhatsappConversation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappConversation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


