/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditSummaryV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditSummaryV2{}

// RiskAuditSummaryV2 struct for RiskAuditSummaryV2
type RiskAuditSummaryV2 struct {
	// Total turns
	TotalTurns *int32 `json:"total_turns,omitempty"`
	// Total calibrated detections
	TotalCalibrated *int32 `json:"total_calibrated,omitempty"`
	// Active detections
	Active *int32 `json:"active,omitempty"`
	// Tolerated detections
	Tolerated *int32 `json:"tolerated,omitempty"`
	// Blocked detections
	Blocked *int32 `json:"blocked,omitempty"`
	// Audio events used
	AudioEventsUsed *int32 `json:"audio_events_used,omitempty"`
	// Audio events aggravated
	AudioEventsAggravated *int32 `json:"audio_events_aggravated,omitempty"`
	// MAC audio applied
	MacAudioApplied interface{} `json:"mac_audio_applied,omitempty"`
	// MVAD applied
	MvadApplied interface{} `json:"mvad_applied,omitempty"`
	// Total participants
	TotalParticipants *int32 `json:"total_participants,omitempty"`
	// Total agents
	TotalAgents *int32 `json:"total_agents,omitempty"`
	// Total clients
	TotalClients *int32 `json:"total_clients,omitempty"`
	// Total bots
	TotalBots *int32 `json:"total_bots,omitempty"`
	// Total unknown
	TotalUnknown *int32 `json:"total_unknown,omitempty"`
	// Client risk alerts count
	ClientRiskAlertsCount *int32 `json:"client_risk_alerts_count,omitempty"`
	// Client behavior alerts count
	ClientBehaviorAlertsCount *int32 `json:"client_behavior_alerts_count,omitempty"`
}

// NewRiskAuditSummaryV2 instantiates a new RiskAuditSummaryV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditSummaryV2() *RiskAuditSummaryV2 {
	this := RiskAuditSummaryV2{}
	return &this
}

// NewRiskAuditSummaryV2WithDefaults instantiates a new RiskAuditSummaryV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditSummaryV2WithDefaults() *RiskAuditSummaryV2 {
	this := RiskAuditSummaryV2{}
	return &this
}

// GetTotalTurns returns the TotalTurns field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalTurns() int32 {
	if o == nil || IsNil(o.TotalTurns) {
		var ret int32
		return ret
	}
	return *o.TotalTurns
}

// GetTotalTurnsOk returns a tuple with the TotalTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalTurnsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTurns) {
		return nil, false
	}
	return o.TotalTurns, true
}

// HasTotalTurns returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalTurns() bool {
	if o != nil && !IsNil(o.TotalTurns) {
		return true
	}

	return false
}

// SetTotalTurns gets a reference to the given int32 and assigns it to the TotalTurns field.
func (o *RiskAuditSummaryV2) SetTotalTurns(v int32) {
	o.TotalTurns = &v
}

// GetTotalCalibrated returns the TotalCalibrated field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalCalibrated() int32 {
	if o == nil || IsNil(o.TotalCalibrated) {
		var ret int32
		return ret
	}
	return *o.TotalCalibrated
}

// GetTotalCalibratedOk returns a tuple with the TotalCalibrated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalCalibratedOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCalibrated) {
		return nil, false
	}
	return o.TotalCalibrated, true
}

// HasTotalCalibrated returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalCalibrated() bool {
	if o != nil && !IsNil(o.TotalCalibrated) {
		return true
	}

	return false
}

// SetTotalCalibrated gets a reference to the given int32 and assigns it to the TotalCalibrated field.
func (o *RiskAuditSummaryV2) SetTotalCalibrated(v int32) {
	o.TotalCalibrated = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetActive() int32 {
	if o == nil || IsNil(o.Active) {
		var ret int32
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetActiveOk() (*int32, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given int32 and assigns it to the Active field.
func (o *RiskAuditSummaryV2) SetActive(v int32) {
	o.Active = &v
}

// GetTolerated returns the Tolerated field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTolerated() int32 {
	if o == nil || IsNil(o.Tolerated) {
		var ret int32
		return ret
	}
	return *o.Tolerated
}

// GetToleratedOk returns a tuple with the Tolerated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetToleratedOk() (*int32, bool) {
	if o == nil || IsNil(o.Tolerated) {
		return nil, false
	}
	return o.Tolerated, true
}

// HasTolerated returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTolerated() bool {
	if o != nil && !IsNil(o.Tolerated) {
		return true
	}

	return false
}

// SetTolerated gets a reference to the given int32 and assigns it to the Tolerated field.
func (o *RiskAuditSummaryV2) SetTolerated(v int32) {
	o.Tolerated = &v
}

// GetBlocked returns the Blocked field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetBlocked() int32 {
	if o == nil || IsNil(o.Blocked) {
		var ret int32
		return ret
	}
	return *o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetBlockedOk() (*int32, bool) {
	if o == nil || IsNil(o.Blocked) {
		return nil, false
	}
	return o.Blocked, true
}

// HasBlocked returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasBlocked() bool {
	if o != nil && !IsNil(o.Blocked) {
		return true
	}

	return false
}

// SetBlocked gets a reference to the given int32 and assigns it to the Blocked field.
func (o *RiskAuditSummaryV2) SetBlocked(v int32) {
	o.Blocked = &v
}

// GetAudioEventsUsed returns the AudioEventsUsed field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetAudioEventsUsed() int32 {
	if o == nil || IsNil(o.AudioEventsUsed) {
		var ret int32
		return ret
	}
	return *o.AudioEventsUsed
}

// GetAudioEventsUsedOk returns a tuple with the AudioEventsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetAudioEventsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.AudioEventsUsed) {
		return nil, false
	}
	return o.AudioEventsUsed, true
}

// HasAudioEventsUsed returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasAudioEventsUsed() bool {
	if o != nil && !IsNil(o.AudioEventsUsed) {
		return true
	}

	return false
}

// SetAudioEventsUsed gets a reference to the given int32 and assigns it to the AudioEventsUsed field.
func (o *RiskAuditSummaryV2) SetAudioEventsUsed(v int32) {
	o.AudioEventsUsed = &v
}

// GetAudioEventsAggravated returns the AudioEventsAggravated field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetAudioEventsAggravated() int32 {
	if o == nil || IsNil(o.AudioEventsAggravated) {
		var ret int32
		return ret
	}
	return *o.AudioEventsAggravated
}

// GetAudioEventsAggravatedOk returns a tuple with the AudioEventsAggravated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetAudioEventsAggravatedOk() (*int32, bool) {
	if o == nil || IsNil(o.AudioEventsAggravated) {
		return nil, false
	}
	return o.AudioEventsAggravated, true
}

// HasAudioEventsAggravated returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasAudioEventsAggravated() bool {
	if o != nil && !IsNil(o.AudioEventsAggravated) {
		return true
	}

	return false
}

// SetAudioEventsAggravated gets a reference to the given int32 and assigns it to the AudioEventsAggravated field.
func (o *RiskAuditSummaryV2) SetAudioEventsAggravated(v int32) {
	o.AudioEventsAggravated = &v
}

// GetMacAudioApplied returns the MacAudioApplied field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditSummaryV2) GetMacAudioApplied() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MacAudioApplied
}

// GetMacAudioAppliedOk returns a tuple with the MacAudioApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditSummaryV2) GetMacAudioAppliedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MacAudioApplied) {
		return nil, false
	}
	return &o.MacAudioApplied, true
}

// HasMacAudioApplied returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasMacAudioApplied() bool {
	if o != nil && !IsNil(o.MacAudioApplied) {
		return true
	}

	return false
}

// SetMacAudioApplied gets a reference to the given interface{} and assigns it to the MacAudioApplied field.
func (o *RiskAuditSummaryV2) SetMacAudioApplied(v interface{}) {
	o.MacAudioApplied = v
}

// GetMvadApplied returns the MvadApplied field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditSummaryV2) GetMvadApplied() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MvadApplied
}

// GetMvadAppliedOk returns a tuple with the MvadApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditSummaryV2) GetMvadAppliedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MvadApplied) {
		return nil, false
	}
	return &o.MvadApplied, true
}

// HasMvadApplied returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasMvadApplied() bool {
	if o != nil && !IsNil(o.MvadApplied) {
		return true
	}

	return false
}

// SetMvadApplied gets a reference to the given interface{} and assigns it to the MvadApplied field.
func (o *RiskAuditSummaryV2) SetMvadApplied(v interface{}) {
	o.MvadApplied = v
}

// GetTotalParticipants returns the TotalParticipants field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalParticipants() int32 {
	if o == nil || IsNil(o.TotalParticipants) {
		var ret int32
		return ret
	}
	return *o.TotalParticipants
}

// GetTotalParticipantsOk returns a tuple with the TotalParticipants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalParticipantsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalParticipants) {
		return nil, false
	}
	return o.TotalParticipants, true
}

// HasTotalParticipants returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalParticipants() bool {
	if o != nil && !IsNil(o.TotalParticipants) {
		return true
	}

	return false
}

// SetTotalParticipants gets a reference to the given int32 and assigns it to the TotalParticipants field.
func (o *RiskAuditSummaryV2) SetTotalParticipants(v int32) {
	o.TotalParticipants = &v
}

// GetTotalAgents returns the TotalAgents field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalAgents() int32 {
	if o == nil || IsNil(o.TotalAgents) {
		var ret int32
		return ret
	}
	return *o.TotalAgents
}

// GetTotalAgentsOk returns a tuple with the TotalAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalAgentsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalAgents) {
		return nil, false
	}
	return o.TotalAgents, true
}

// HasTotalAgents returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalAgents() bool {
	if o != nil && !IsNil(o.TotalAgents) {
		return true
	}

	return false
}

// SetTotalAgents gets a reference to the given int32 and assigns it to the TotalAgents field.
func (o *RiskAuditSummaryV2) SetTotalAgents(v int32) {
	o.TotalAgents = &v
}

// GetTotalClients returns the TotalClients field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalClients() int32 {
	if o == nil || IsNil(o.TotalClients) {
		var ret int32
		return ret
	}
	return *o.TotalClients
}

// GetTotalClientsOk returns a tuple with the TotalClients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalClientsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalClients) {
		return nil, false
	}
	return o.TotalClients, true
}

// HasTotalClients returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalClients() bool {
	if o != nil && !IsNil(o.TotalClients) {
		return true
	}

	return false
}

// SetTotalClients gets a reference to the given int32 and assigns it to the TotalClients field.
func (o *RiskAuditSummaryV2) SetTotalClients(v int32) {
	o.TotalClients = &v
}

// GetTotalBots returns the TotalBots field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalBots() int32 {
	if o == nil || IsNil(o.TotalBots) {
		var ret int32
		return ret
	}
	return *o.TotalBots
}

// GetTotalBotsOk returns a tuple with the TotalBots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalBotsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalBots) {
		return nil, false
	}
	return o.TotalBots, true
}

// HasTotalBots returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalBots() bool {
	if o != nil && !IsNil(o.TotalBots) {
		return true
	}

	return false
}

// SetTotalBots gets a reference to the given int32 and assigns it to the TotalBots field.
func (o *RiskAuditSummaryV2) SetTotalBots(v int32) {
	o.TotalBots = &v
}

// GetTotalUnknown returns the TotalUnknown field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetTotalUnknown() int32 {
	if o == nil || IsNil(o.TotalUnknown) {
		var ret int32
		return ret
	}
	return *o.TotalUnknown
}

// GetTotalUnknownOk returns a tuple with the TotalUnknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetTotalUnknownOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalUnknown) {
		return nil, false
	}
	return o.TotalUnknown, true
}

// HasTotalUnknown returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasTotalUnknown() bool {
	if o != nil && !IsNil(o.TotalUnknown) {
		return true
	}

	return false
}

// SetTotalUnknown gets a reference to the given int32 and assigns it to the TotalUnknown field.
func (o *RiskAuditSummaryV2) SetTotalUnknown(v int32) {
	o.TotalUnknown = &v
}

// GetClientRiskAlertsCount returns the ClientRiskAlertsCount field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetClientRiskAlertsCount() int32 {
	if o == nil || IsNil(o.ClientRiskAlertsCount) {
		var ret int32
		return ret
	}
	return *o.ClientRiskAlertsCount
}

// GetClientRiskAlertsCountOk returns a tuple with the ClientRiskAlertsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetClientRiskAlertsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClientRiskAlertsCount) {
		return nil, false
	}
	return o.ClientRiskAlertsCount, true
}

// HasClientRiskAlertsCount returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasClientRiskAlertsCount() bool {
	if o != nil && !IsNil(o.ClientRiskAlertsCount) {
		return true
	}

	return false
}

// SetClientRiskAlertsCount gets a reference to the given int32 and assigns it to the ClientRiskAlertsCount field.
func (o *RiskAuditSummaryV2) SetClientRiskAlertsCount(v int32) {
	o.ClientRiskAlertsCount = &v
}

// GetClientBehaviorAlertsCount returns the ClientBehaviorAlertsCount field value if set, zero value otherwise.
func (o *RiskAuditSummaryV2) GetClientBehaviorAlertsCount() int32 {
	if o == nil || IsNil(o.ClientBehaviorAlertsCount) {
		var ret int32
		return ret
	}
	return *o.ClientBehaviorAlertsCount
}

// GetClientBehaviorAlertsCountOk returns a tuple with the ClientBehaviorAlertsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditSummaryV2) GetClientBehaviorAlertsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClientBehaviorAlertsCount) {
		return nil, false
	}
	return o.ClientBehaviorAlertsCount, true
}

// HasClientBehaviorAlertsCount returns a boolean if a field has been set.
func (o *RiskAuditSummaryV2) HasClientBehaviorAlertsCount() bool {
	if o != nil && !IsNil(o.ClientBehaviorAlertsCount) {
		return true
	}

	return false
}

// SetClientBehaviorAlertsCount gets a reference to the given int32 and assigns it to the ClientBehaviorAlertsCount field.
func (o *RiskAuditSummaryV2) SetClientBehaviorAlertsCount(v int32) {
	o.ClientBehaviorAlertsCount = &v
}

func (o RiskAuditSummaryV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditSummaryV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalTurns) {
		toSerialize["total_turns"] = o.TotalTurns
	}
	if !IsNil(o.TotalCalibrated) {
		toSerialize["total_calibrated"] = o.TotalCalibrated
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Tolerated) {
		toSerialize["tolerated"] = o.Tolerated
	}
	if !IsNil(o.Blocked) {
		toSerialize["blocked"] = o.Blocked
	}
	if !IsNil(o.AudioEventsUsed) {
		toSerialize["audio_events_used"] = o.AudioEventsUsed
	}
	if !IsNil(o.AudioEventsAggravated) {
		toSerialize["audio_events_aggravated"] = o.AudioEventsAggravated
	}
	if o.MacAudioApplied != nil {
		toSerialize["mac_audio_applied"] = o.MacAudioApplied
	}
	if o.MvadApplied != nil {
		toSerialize["mvad_applied"] = o.MvadApplied
	}
	if !IsNil(o.TotalParticipants) {
		toSerialize["total_participants"] = o.TotalParticipants
	}
	if !IsNil(o.TotalAgents) {
		toSerialize["total_agents"] = o.TotalAgents
	}
	if !IsNil(o.TotalClients) {
		toSerialize["total_clients"] = o.TotalClients
	}
	if !IsNil(o.TotalBots) {
		toSerialize["total_bots"] = o.TotalBots
	}
	if !IsNil(o.TotalUnknown) {
		toSerialize["total_unknown"] = o.TotalUnknown
	}
	if !IsNil(o.ClientRiskAlertsCount) {
		toSerialize["client_risk_alerts_count"] = o.ClientRiskAlertsCount
	}
	if !IsNil(o.ClientBehaviorAlertsCount) {
		toSerialize["client_behavior_alerts_count"] = o.ClientBehaviorAlertsCount
	}
	return toSerialize, nil
}

type NullableRiskAuditSummaryV2 struct {
	value *RiskAuditSummaryV2
	isSet bool
}

func (v NullableRiskAuditSummaryV2) Get() *RiskAuditSummaryV2 {
	return v.value
}

func (v *NullableRiskAuditSummaryV2) Set(val *RiskAuditSummaryV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditSummaryV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditSummaryV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditSummaryV2(val *RiskAuditSummaryV2) *NullableRiskAuditSummaryV2 {
	return &NullableRiskAuditSummaryV2{value: val, isSet: true}
}

func (v NullableRiskAuditSummaryV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditSummaryV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


