/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookItem{}

// WebhookItem struct for WebhookItem
type WebhookItem struct {
	// Webhook id
	Id string `json:"id"`
	// Owner user id
	UserId string `json:"user_id"`
	// Webhook name
	Name string `json:"name"`
	// Destination URL
	Url string `json:"url"`
	// HMAC signing secret
	Secret string `json:"secret"`
	// Subscribed events
	Events []string `json:"events"`
	// Is active
	Active bool `json:"active"`
	// Retry enabled
	RetryEnabled bool `json:"retry_enabled"`
	// ISO 8601 of last delivery
	LastDeliveryAt *string `json:"last_delivery_at,omitempty"`
	// Last HTTP status delivered
	LastStatus *int32 `json:"last_status,omitempty"`
	// Consecutive failures
	FailureCount *int32 `json:"failure_count,omitempty"`
	// ISO 8601 created
	CreatedAt string `json:"created_at"`
	// ISO 8601 updated
	UpdatedAt string `json:"updated_at"`
}

type _WebhookItem WebhookItem

// NewWebhookItem instantiates a new WebhookItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookItem(id string, userId string, name string, url string, secret string, events []string, active bool, retryEnabled bool, createdAt string, updatedAt string) *WebhookItem {
	this := WebhookItem{}
	this.Id = id
	this.UserId = userId
	this.Name = name
	this.Url = url
	this.Secret = secret
	this.Events = events
	this.Active = active
	this.RetryEnabled = retryEnabled
	var failureCount int32 = 0
	this.FailureCount = &failureCount
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewWebhookItemWithDefaults instantiates a new WebhookItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookItemWithDefaults() *WebhookItem {
	this := WebhookItem{}
	var failureCount int32 = 0
	this.FailureCount = &failureCount
	return &this
}

// GetId returns the Id field value
func (o *WebhookItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookItem) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *WebhookItem) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *WebhookItem) SetUserId(v string) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *WebhookItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebhookItem) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *WebhookItem) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookItem) SetUrl(v string) {
	o.Url = v
}

// GetSecret returns the Secret field value
func (o *WebhookItem) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *WebhookItem) SetSecret(v string) {
	o.Secret = v
}

// GetEvents returns the Events field value
func (o *WebhookItem) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookItem) SetEvents(v []string) {
	o.Events = v
}

// GetActive returns the Active field value
func (o *WebhookItem) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookItem) SetActive(v bool) {
	o.Active = v
}

// GetRetryEnabled returns the RetryEnabled field value
func (o *WebhookItem) GetRetryEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RetryEnabled
}

// GetRetryEnabledOk returns a tuple with the RetryEnabled field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetRetryEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryEnabled, true
}

// SetRetryEnabled sets field value
func (o *WebhookItem) SetRetryEnabled(v bool) {
	o.RetryEnabled = v
}

// GetLastDeliveryAt returns the LastDeliveryAt field value if set, zero value otherwise.
func (o *WebhookItem) GetLastDeliveryAt() string {
	if o == nil || IsNil(o.LastDeliveryAt) {
		var ret string
		return ret
	}
	return *o.LastDeliveryAt
}

// GetLastDeliveryAtOk returns a tuple with the LastDeliveryAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetLastDeliveryAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastDeliveryAt) {
		return nil, false
	}
	return o.LastDeliveryAt, true
}

// HasLastDeliveryAt returns a boolean if a field has been set.
func (o *WebhookItem) HasLastDeliveryAt() bool {
	if o != nil && !IsNil(o.LastDeliveryAt) {
		return true
	}

	return false
}

// SetLastDeliveryAt gets a reference to the given string and assigns it to the LastDeliveryAt field.
func (o *WebhookItem) SetLastDeliveryAt(v string) {
	o.LastDeliveryAt = &v
}

// GetLastStatus returns the LastStatus field value if set, zero value otherwise.
func (o *WebhookItem) GetLastStatus() int32 {
	if o == nil || IsNil(o.LastStatus) {
		var ret int32
		return ret
	}
	return *o.LastStatus
}

// GetLastStatusOk returns a tuple with the LastStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetLastStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.LastStatus) {
		return nil, false
	}
	return o.LastStatus, true
}

// HasLastStatus returns a boolean if a field has been set.
func (o *WebhookItem) HasLastStatus() bool {
	if o != nil && !IsNil(o.LastStatus) {
		return true
	}

	return false
}

// SetLastStatus gets a reference to the given int32 and assigns it to the LastStatus field.
func (o *WebhookItem) SetLastStatus(v int32) {
	o.LastStatus = &v
}

// GetFailureCount returns the FailureCount field value if set, zero value otherwise.
func (o *WebhookItem) GetFailureCount() int32 {
	if o == nil || IsNil(o.FailureCount) {
		var ret int32
		return ret
	}
	return *o.FailureCount
}

// GetFailureCountOk returns a tuple with the FailureCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetFailureCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FailureCount) {
		return nil, false
	}
	return o.FailureCount, true
}

// HasFailureCount returns a boolean if a field has been set.
func (o *WebhookItem) HasFailureCount() bool {
	if o != nil && !IsNil(o.FailureCount) {
		return true
	}

	return false
}

// SetFailureCount gets a reference to the given int32 and assigns it to the FailureCount field.
func (o *WebhookItem) SetFailureCount(v int32) {
	o.FailureCount = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WebhookItem) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WebhookItem) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o WebhookItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["user_id"] = o.UserId
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	toSerialize["secret"] = o.Secret
	toSerialize["events"] = o.Events
	toSerialize["active"] = o.Active
	toSerialize["retry_enabled"] = o.RetryEnabled
	if !IsNil(o.LastDeliveryAt) {
		toSerialize["last_delivery_at"] = o.LastDeliveryAt
	}
	if !IsNil(o.LastStatus) {
		toSerialize["last_status"] = o.LastStatus
	}
	if !IsNil(o.FailureCount) {
		toSerialize["failure_count"] = o.FailureCount
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *WebhookItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"user_id",
		"name",
		"url",
		"secret",
		"events",
		"active",
		"retry_enabled",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookItem := _WebhookItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookItem)

	if err != nil {
		return err
	}

	*o = WebhookItem(varWebhookItem)

	return err
}

type NullableWebhookItem struct {
	value *WebhookItem
	isSet bool
}

func (v NullableWebhookItem) Get() *WebhookItem {
	return v.value
}

func (v *NullableWebhookItem) Set(val *WebhookItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookItem(val *WebhookItem) *NullableWebhookItem {
	return &NullableWebhookItem{value: val, isSet: true}
}

func (v NullableWebhookItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


