/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"fmt"
)

// WebhookEvent the model 'WebhookEvent'
type WebhookEvent string

// List of WebhookEvent
const (
	WEBHOOKEVENT_SUBSCRIPTION_CREATED WebhookEvent = "subscription.created"
	WEBHOOKEVENT_AVULSO_COMPLETED WebhookEvent = "avulso.completed"
	WEBHOOKEVENT_SUBSCRIPTION_UPGRADED WebhookEvent = "subscription.upgraded"
	WEBHOOKEVENT_SUBSCRIPTION_DOWNGRADED WebhookEvent = "subscription.downgraded"
	WEBHOOKEVENT_SUBSCRIPTION_CANCELED WebhookEvent = "subscription.canceled"
	WEBHOOKEVENT_CREDITS_LOW WebhookEvent = "credits.low"
	WEBHOOKEVENT_CREDITS_EXHAUSTED WebhookEvent = "credits.exhausted"
	WEBHOOKEVENT_SUBSCRIPTION_RENEWED WebhookEvent = "subscription.renewed"
	WEBHOOKEVENT_SUBSCRIPTION_EXPIRED WebhookEvent = "subscription.expired"
	WEBHOOKEVENT_PAYMENT_FAILED WebhookEvent = "payment.failed"
)

// All allowed values of WebhookEvent enum
var AllowedWebhookEventEnumValues = []WebhookEvent{
	"subscription.created",
	"avulso.completed",
	"subscription.upgraded",
	"subscription.downgraded",
	"subscription.canceled",
	"credits.low",
	"credits.exhausted",
	"subscription.renewed",
	"subscription.expired",
	"payment.failed",
}

func (v *WebhookEvent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WebhookEvent(value)
	for _, existing := range AllowedWebhookEventEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WebhookEvent", value)
}

// NewWebhookEventFromValue returns a pointer to a valid WebhookEvent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWebhookEventFromValue(v string) (*WebhookEvent, error) {
	ev := WebhookEvent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WebhookEvent: valid values are %v", v, AllowedWebhookEventEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WebhookEvent) IsValid() bool {
	for _, existing := range AllowedWebhookEventEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WebhookEvent value
func (v WebhookEvent) Ptr() *WebhookEvent {
	return &v
}

type NullableWebhookEvent struct {
	value *WebhookEvent
	isSet bool
}

func (v NullableWebhookEvent) Get() *WebhookEvent {
	return v.value
}

func (v *NullableWebhookEvent) Set(val *WebhookEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEvent(val *WebhookEvent) *NullableWebhookEvent {
	return &NullableWebhookEvent{value: val, isSet: true}
}

func (v NullableWebhookEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

