/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageLogItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageLogItem{}

// UsageLogItem struct for UsageLogItem
type UsageLogItem struct {
	// Usage log entry id
	Id string `json:"id"`
	// Endpoint called
	Endpoint string `json:"endpoint"`
	// Credits consumed
	CreditsCost int32 `json:"credits_cost"`
	// Result status
	Status string `json:"status"`
	// Errors count
	ErrorsCount int32 `json:"errors_count"`
	// ISO 8601 timestamp
	CreatedAt string `json:"created_at"`
}

type _UsageLogItem UsageLogItem

// NewUsageLogItem instantiates a new UsageLogItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageLogItem(id string, endpoint string, creditsCost int32, status string, errorsCount int32, createdAt string) *UsageLogItem {
	this := UsageLogItem{}
	this.Id = id
	this.Endpoint = endpoint
	this.CreditsCost = creditsCost
	this.Status = status
	this.ErrorsCount = errorsCount
	this.CreatedAt = createdAt
	return &this
}

// NewUsageLogItemWithDefaults instantiates a new UsageLogItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageLogItemWithDefaults() *UsageLogItem {
	this := UsageLogItem{}
	return &this
}

// GetId returns the Id field value
func (o *UsageLogItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UsageLogItem) SetId(v string) {
	o.Id = v
}

// GetEndpoint returns the Endpoint field value
func (o *UsageLogItem) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *UsageLogItem) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetCreditsCost returns the CreditsCost field value
func (o *UsageLogItem) GetCreditsCost() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsCost
}

// GetCreditsCostOk returns a tuple with the CreditsCost field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetCreditsCostOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsCost, true
}

// SetCreditsCost sets field value
func (o *UsageLogItem) SetCreditsCost(v int32) {
	o.CreditsCost = v
}

// GetStatus returns the Status field value
func (o *UsageLogItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UsageLogItem) SetStatus(v string) {
	o.Status = v
}

// GetErrorsCount returns the ErrorsCount field value
func (o *UsageLogItem) GetErrorsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorsCount
}

// GetErrorsCountOk returns a tuple with the ErrorsCount field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetErrorsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorsCount, true
}

// SetErrorsCount sets field value
func (o *UsageLogItem) SetErrorsCount(v int32) {
	o.ErrorsCount = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UsageLogItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UsageLogItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UsageLogItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o UsageLogItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageLogItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["credits_cost"] = o.CreditsCost
	toSerialize["status"] = o.Status
	toSerialize["errors_count"] = o.ErrorsCount
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *UsageLogItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"endpoint",
		"credits_cost",
		"status",
		"errors_count",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageLogItem := _UsageLogItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageLogItem)

	if err != nil {
		return err
	}

	*o = UsageLogItem(varUsageLogItem)

	return err
}

type NullableUsageLogItem struct {
	value *UsageLogItem
	isSet bool
}

func (v NullableUsageLogItem) Get() *UsageLogItem {
	return v.value
}

func (v *NullableUsageLogItem) Set(val *UsageLogItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageLogItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageLogItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageLogItem(val *UsageLogItem) *NullableUsageLogItem {
	return &NullableUsageLogItem{value: val, isSet: true}
}

func (v NullableUsageLogItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageLogItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


