/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WhatsappMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsappMeta{}

// WhatsappMeta struct for WhatsappMeta
type WhatsappMeta struct {
	// Uploaded file name
	File string `json:"file"`
	// chat.txt entry name inside the export
	ChatTxt string `json:"chat_txt"`
	// Detected format: Android | iOS
	Format string `json:"format"`
	// Date order used
	DateFormat string `json:"date_format"`
	// Timezone informed
	Timezone string `json:"timezone"`
	// Window start (ISO)
	Start string `json:"start"`
	// Window end (ISO)
	End string `json:"end"`
	// Gap used to split conversations
	GapMinutes float32 `json:"gap_minutes"`
	// Minimum messages per conversation
	MinMessages int32 `json:"min_messages"`
	// Chars per minute used to estimate duration
	CharsPerMinute float32 `json:"chars_per_minute"`
	// Total parsed turns
	Turns int32 `json:"turns"`
	// System lines ignored
	SystemLines int32 `json:"system_lines"`
	// Conversations before window filter
	ConversationsTotal int32 `json:"conversations_total"`
	// Conversations overlapping the window
	ConversationsInWindow int32 `json:"conversations_in_window"`
	// Single-speaker conversations dropped
	MonologuesDropped int32 `json:"monologues_dropped"`
	// Final conversations returned
	ConversationsSelected int32 `json:"conversations_selected"`
}

type _WhatsappMeta WhatsappMeta

// NewWhatsappMeta instantiates a new WhatsappMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappMeta(file string, chatTxt string, format string, dateFormat string, timezone string, start string, end string, gapMinutes float32, minMessages int32, charsPerMinute float32, turns int32, systemLines int32, conversationsTotal int32, conversationsInWindow int32, monologuesDropped int32, conversationsSelected int32) *WhatsappMeta {
	this := WhatsappMeta{}
	this.File = file
	this.ChatTxt = chatTxt
	this.Format = format
	this.DateFormat = dateFormat
	this.Timezone = timezone
	this.Start = start
	this.End = end
	this.GapMinutes = gapMinutes
	this.MinMessages = minMessages
	this.CharsPerMinute = charsPerMinute
	this.Turns = turns
	this.SystemLines = systemLines
	this.ConversationsTotal = conversationsTotal
	this.ConversationsInWindow = conversationsInWindow
	this.MonologuesDropped = monologuesDropped
	this.ConversationsSelected = conversationsSelected
	return &this
}

// NewWhatsappMetaWithDefaults instantiates a new WhatsappMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappMetaWithDefaults() *WhatsappMeta {
	this := WhatsappMeta{}
	return &this
}

// GetFile returns the File field value
func (o *WhatsappMeta) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *WhatsappMeta) SetFile(v string) {
	o.File = v
}

// GetChatTxt returns the ChatTxt field value
func (o *WhatsappMeta) GetChatTxt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChatTxt
}

// GetChatTxtOk returns a tuple with the ChatTxt field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetChatTxtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChatTxt, true
}

// SetChatTxt sets field value
func (o *WhatsappMeta) SetChatTxt(v string) {
	o.ChatTxt = v
}

// GetFormat returns the Format field value
func (o *WhatsappMeta) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *WhatsappMeta) SetFormat(v string) {
	o.Format = v
}

// GetDateFormat returns the DateFormat field value
func (o *WhatsappMeta) GetDateFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateFormat
}

// GetDateFormatOk returns a tuple with the DateFormat field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetDateFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateFormat, true
}

// SetDateFormat sets field value
func (o *WhatsappMeta) SetDateFormat(v string) {
	o.DateFormat = v
}

// GetTimezone returns the Timezone field value
func (o *WhatsappMeta) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *WhatsappMeta) SetTimezone(v string) {
	o.Timezone = v
}

// GetStart returns the Start field value
func (o *WhatsappMeta) GetStart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *WhatsappMeta) SetStart(v string) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *WhatsappMeta) GetEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *WhatsappMeta) SetEnd(v string) {
	o.End = v
}

// GetGapMinutes returns the GapMinutes field value
func (o *WhatsappMeta) GetGapMinutes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.GapMinutes
}

// GetGapMinutesOk returns a tuple with the GapMinutes field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetGapMinutesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GapMinutes, true
}

// SetGapMinutes sets field value
func (o *WhatsappMeta) SetGapMinutes(v float32) {
	o.GapMinutes = v
}

// GetMinMessages returns the MinMessages field value
func (o *WhatsappMeta) GetMinMessages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinMessages
}

// GetMinMessagesOk returns a tuple with the MinMessages field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetMinMessagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinMessages, true
}

// SetMinMessages sets field value
func (o *WhatsappMeta) SetMinMessages(v int32) {
	o.MinMessages = v
}

// GetCharsPerMinute returns the CharsPerMinute field value
func (o *WhatsappMeta) GetCharsPerMinute() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CharsPerMinute
}

// GetCharsPerMinuteOk returns a tuple with the CharsPerMinute field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetCharsPerMinuteOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharsPerMinute, true
}

// SetCharsPerMinute sets field value
func (o *WhatsappMeta) SetCharsPerMinute(v float32) {
	o.CharsPerMinute = v
}

// GetTurns returns the Turns field value
func (o *WhatsappMeta) GetTurns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Turns
}

// GetTurnsOk returns a tuple with the Turns field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Turns, true
}

// SetTurns sets field value
func (o *WhatsappMeta) SetTurns(v int32) {
	o.Turns = v
}

// GetSystemLines returns the SystemLines field value
func (o *WhatsappMeta) GetSystemLines() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SystemLines
}

// GetSystemLinesOk returns a tuple with the SystemLines field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetSystemLinesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SystemLines, true
}

// SetSystemLines sets field value
func (o *WhatsappMeta) SetSystemLines(v int32) {
	o.SystemLines = v
}

// GetConversationsTotal returns the ConversationsTotal field value
func (o *WhatsappMeta) GetConversationsTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConversationsTotal
}

// GetConversationsTotalOk returns a tuple with the ConversationsTotal field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetConversationsTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationsTotal, true
}

// SetConversationsTotal sets field value
func (o *WhatsappMeta) SetConversationsTotal(v int32) {
	o.ConversationsTotal = v
}

// GetConversationsInWindow returns the ConversationsInWindow field value
func (o *WhatsappMeta) GetConversationsInWindow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConversationsInWindow
}

// GetConversationsInWindowOk returns a tuple with the ConversationsInWindow field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetConversationsInWindowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationsInWindow, true
}

// SetConversationsInWindow sets field value
func (o *WhatsappMeta) SetConversationsInWindow(v int32) {
	o.ConversationsInWindow = v
}

// GetMonologuesDropped returns the MonologuesDropped field value
func (o *WhatsappMeta) GetMonologuesDropped() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MonologuesDropped
}

// GetMonologuesDroppedOk returns a tuple with the MonologuesDropped field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetMonologuesDroppedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonologuesDropped, true
}

// SetMonologuesDropped sets field value
func (o *WhatsappMeta) SetMonologuesDropped(v int32) {
	o.MonologuesDropped = v
}

// GetConversationsSelected returns the ConversationsSelected field value
func (o *WhatsappMeta) GetConversationsSelected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConversationsSelected
}

// GetConversationsSelectedOk returns a tuple with the ConversationsSelected field value
// and a boolean to check if the value has been set.
func (o *WhatsappMeta) GetConversationsSelectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationsSelected, true
}

// SetConversationsSelected sets field value
func (o *WhatsappMeta) SetConversationsSelected(v int32) {
	o.ConversationsSelected = v
}

func (o WhatsappMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsappMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	toSerialize["chat_txt"] = o.ChatTxt
	toSerialize["format"] = o.Format
	toSerialize["date_format"] = o.DateFormat
	toSerialize["timezone"] = o.Timezone
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	toSerialize["gap_minutes"] = o.GapMinutes
	toSerialize["min_messages"] = o.MinMessages
	toSerialize["chars_per_minute"] = o.CharsPerMinute
	toSerialize["turns"] = o.Turns
	toSerialize["system_lines"] = o.SystemLines
	toSerialize["conversations_total"] = o.ConversationsTotal
	toSerialize["conversations_in_window"] = o.ConversationsInWindow
	toSerialize["monologues_dropped"] = o.MonologuesDropped
	toSerialize["conversations_selected"] = o.ConversationsSelected
	return toSerialize, nil
}

func (o *WhatsappMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
		"chat_txt",
		"format",
		"date_format",
		"timezone",
		"start",
		"end",
		"gap_minutes",
		"min_messages",
		"chars_per_minute",
		"turns",
		"system_lines",
		"conversations_total",
		"conversations_in_window",
		"monologues_dropped",
		"conversations_selected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsappMeta := _WhatsappMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsappMeta)

	if err != nil {
		return err
	}

	*o = WhatsappMeta(varWhatsappMeta)

	return err
}

type NullableWhatsappMeta struct {
	value *WhatsappMeta
	isSet bool
}

func (v NullableWhatsappMeta) Get() *WhatsappMeta {
	return v.value
}

func (v *NullableWhatsappMeta) Set(val *WhatsappMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappMeta(val *WhatsappMeta) *NullableWhatsappMeta {
	return &NullableWhatsappMeta{value: val, isSet: true}
}

func (v NullableWhatsappMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


