/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookListResponse{}

// WebhookListResponse struct for WebhookListResponse
type WebhookListResponse struct {
	Data []WebhookItem `json:"data"`
	Page int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type _WebhookListResponse WebhookListResponse

// NewWebhookListResponse instantiates a new WebhookListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookListResponse(data []WebhookItem, page int32, limit int32) *WebhookListResponse {
	this := WebhookListResponse{}
	this.Data = data
	this.Page = page
	this.Limit = limit
	return &this
}

// NewWebhookListResponseWithDefaults instantiates a new WebhookListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookListResponseWithDefaults() *WebhookListResponse {
	this := WebhookListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *WebhookListResponse) GetData() []WebhookItem {
	if o == nil {
		var ret []WebhookItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookListResponse) GetDataOk() ([]WebhookItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *WebhookListResponse) SetData(v []WebhookItem) {
	o.Data = v
}

// GetPage returns the Page field value
func (o *WebhookListResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *WebhookListResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *WebhookListResponse) SetPage(v int32) {
	o.Page = v
}

// GetLimit returns the Limit field value
func (o *WebhookListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *WebhookListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *WebhookListResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o WebhookListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["page"] = o.Page
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

func (o *WebhookListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"page",
		"limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookListResponse := _WebhookListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookListResponse)

	if err != nil {
		return err
	}

	*o = WebhookListResponse(varWebhookListResponse)

	return err
}

type NullableWebhookListResponse struct {
	value *WebhookListResponse
	isSet bool
}

func (v NullableWebhookListResponse) Get() *WebhookListResponse {
	return v.value
}

func (v *NullableWebhookListResponse) Set(val *WebhookListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookListResponse(val *WebhookListResponse) *NullableWebhookListResponse {
	return &NullableWebhookListResponse{value: val, isSet: true}
}

func (v NullableWebhookListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


