/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiagnosticAudioEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticAudioEvent{}

// DiagnosticAudioEvent struct for DiagnosticAudioEvent
type DiagnosticAudioEvent struct {
	// Audio event type. E.g.: [laughter], [sigh]
	Event string `json:"event"`
	// Start time in seconds
	StartS *float32 `json:"start_s,omitempty"`
	// End time in seconds
	EndS *float32 `json:"end_s,omitempty"`
	// Duration in seconds
	DurationS *float32 `json:"duration_s,omitempty"`
	// Formatted timestamp (HH:MM:SS.ms)
	FormattedTimestamp *string `json:"formatted_timestamp,omitempty"`
}

type _DiagnosticAudioEvent DiagnosticAudioEvent

// NewDiagnosticAudioEvent instantiates a new DiagnosticAudioEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticAudioEvent(event string) *DiagnosticAudioEvent {
	this := DiagnosticAudioEvent{}
	this.Event = event
	return &this
}

// NewDiagnosticAudioEventWithDefaults instantiates a new DiagnosticAudioEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticAudioEventWithDefaults() *DiagnosticAudioEvent {
	this := DiagnosticAudioEvent{}
	return &this
}

// GetEvent returns the Event field value
func (o *DiagnosticAudioEvent) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *DiagnosticAudioEvent) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *DiagnosticAudioEvent) SetEvent(v string) {
	o.Event = v
}

// GetStartS returns the StartS field value if set, zero value otherwise.
func (o *DiagnosticAudioEvent) GetStartS() float32 {
	if o == nil || IsNil(o.StartS) {
		var ret float32
		return ret
	}
	return *o.StartS
}

// GetStartSOk returns a tuple with the StartS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticAudioEvent) GetStartSOk() (*float32, bool) {
	if o == nil || IsNil(o.StartS) {
		return nil, false
	}
	return o.StartS, true
}

// HasStartS returns a boolean if a field has been set.
func (o *DiagnosticAudioEvent) HasStartS() bool {
	if o != nil && !IsNil(o.StartS) {
		return true
	}

	return false
}

// SetStartS gets a reference to the given float32 and assigns it to the StartS field.
func (o *DiagnosticAudioEvent) SetStartS(v float32) {
	o.StartS = &v
}

// GetEndS returns the EndS field value if set, zero value otherwise.
func (o *DiagnosticAudioEvent) GetEndS() float32 {
	if o == nil || IsNil(o.EndS) {
		var ret float32
		return ret
	}
	return *o.EndS
}

// GetEndSOk returns a tuple with the EndS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticAudioEvent) GetEndSOk() (*float32, bool) {
	if o == nil || IsNil(o.EndS) {
		return nil, false
	}
	return o.EndS, true
}

// HasEndS returns a boolean if a field has been set.
func (o *DiagnosticAudioEvent) HasEndS() bool {
	if o != nil && !IsNil(o.EndS) {
		return true
	}

	return false
}

// SetEndS gets a reference to the given float32 and assigns it to the EndS field.
func (o *DiagnosticAudioEvent) SetEndS(v float32) {
	o.EndS = &v
}

// GetDurationS returns the DurationS field value if set, zero value otherwise.
func (o *DiagnosticAudioEvent) GetDurationS() float32 {
	if o == nil || IsNil(o.DurationS) {
		var ret float32
		return ret
	}
	return *o.DurationS
}

// GetDurationSOk returns a tuple with the DurationS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticAudioEvent) GetDurationSOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationS) {
		return nil, false
	}
	return o.DurationS, true
}

// HasDurationS returns a boolean if a field has been set.
func (o *DiagnosticAudioEvent) HasDurationS() bool {
	if o != nil && !IsNil(o.DurationS) {
		return true
	}

	return false
}

// SetDurationS gets a reference to the given float32 and assigns it to the DurationS field.
func (o *DiagnosticAudioEvent) SetDurationS(v float32) {
	o.DurationS = &v
}

// GetFormattedTimestamp returns the FormattedTimestamp field value if set, zero value otherwise.
func (o *DiagnosticAudioEvent) GetFormattedTimestamp() string {
	if o == nil || IsNil(o.FormattedTimestamp) {
		var ret string
		return ret
	}
	return *o.FormattedTimestamp
}

// GetFormattedTimestampOk returns a tuple with the FormattedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticAudioEvent) GetFormattedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.FormattedTimestamp) {
		return nil, false
	}
	return o.FormattedTimestamp, true
}

// HasFormattedTimestamp returns a boolean if a field has been set.
func (o *DiagnosticAudioEvent) HasFormattedTimestamp() bool {
	if o != nil && !IsNil(o.FormattedTimestamp) {
		return true
	}

	return false
}

// SetFormattedTimestamp gets a reference to the given string and assigns it to the FormattedTimestamp field.
func (o *DiagnosticAudioEvent) SetFormattedTimestamp(v string) {
	o.FormattedTimestamp = &v
}

func (o DiagnosticAudioEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticAudioEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	if !IsNil(o.StartS) {
		toSerialize["start_s"] = o.StartS
	}
	if !IsNil(o.EndS) {
		toSerialize["end_s"] = o.EndS
	}
	if !IsNil(o.DurationS) {
		toSerialize["duration_s"] = o.DurationS
	}
	if !IsNil(o.FormattedTimestamp) {
		toSerialize["formatted_timestamp"] = o.FormattedTimestamp
	}
	return toSerialize, nil
}

func (o *DiagnosticAudioEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiagnosticAudioEvent := _DiagnosticAudioEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiagnosticAudioEvent)

	if err != nil {
		return err
	}

	*o = DiagnosticAudioEvent(varDiagnosticAudioEvent)

	return err
}

type NullableDiagnosticAudioEvent struct {
	value *DiagnosticAudioEvent
	isSet bool
}

func (v NullableDiagnosticAudioEvent) Get() *DiagnosticAudioEvent {
	return v.value
}

func (v *NullableDiagnosticAudioEvent) Set(val *DiagnosticAudioEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticAudioEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticAudioEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticAudioEvent(val *DiagnosticAudioEvent) *NullableDiagnosticAudioEvent {
	return &NullableDiagnosticAudioEvent{value: val, isSet: true}
}

func (v NullableDiagnosticAudioEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticAudioEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


