/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskAuditMetaV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditMetaV2{}

// RiskAuditMetaV2 struct for RiskAuditMetaV2
type RiskAuditMetaV2 struct {
	// Analysis id
	Id string `json:"id"`
	// Object type
	Object *string `json:"object,omitempty"`
	// Call duration (s)
	CallDurationS *float32 `json:"call_duration_s,omitempty"`
	// ISO 8601 analyzed timestamp
	AnalyzedAt *string `json:"analyzed_at,omitempty"`
	// Usage block
	Usage RiskAuditUsageV2 `json:"usage"`
	// Echoed client reference id
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
}

type _RiskAuditMetaV2 RiskAuditMetaV2

// NewRiskAuditMetaV2 instantiates a new RiskAuditMetaV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditMetaV2(id string, usage RiskAuditUsageV2) *RiskAuditMetaV2 {
	this := RiskAuditMetaV2{}
	this.Id = id
	var object string = "risk_audit"
	this.Object = &object
	this.Usage = usage
	return &this
}

// NewRiskAuditMetaV2WithDefaults instantiates a new RiskAuditMetaV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditMetaV2WithDefaults() *RiskAuditMetaV2 {
	this := RiskAuditMetaV2{}
	var object string = "risk_audit"
	this.Object = &object
	return &this
}

// GetId returns the Id field value
func (o *RiskAuditMetaV2) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RiskAuditMetaV2) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *RiskAuditMetaV2) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *RiskAuditMetaV2) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *RiskAuditMetaV2) SetObject(v string) {
	o.Object = &v
}

// GetCallDurationS returns the CallDurationS field value if set, zero value otherwise.
func (o *RiskAuditMetaV2) GetCallDurationS() float32 {
	if o == nil || IsNil(o.CallDurationS) {
		var ret float32
		return ret
	}
	return *o.CallDurationS
}

// GetCallDurationSOk returns a tuple with the CallDurationS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetCallDurationSOk() (*float32, bool) {
	if o == nil || IsNil(o.CallDurationS) {
		return nil, false
	}
	return o.CallDurationS, true
}

// HasCallDurationS returns a boolean if a field has been set.
func (o *RiskAuditMetaV2) HasCallDurationS() bool {
	if o != nil && !IsNil(o.CallDurationS) {
		return true
	}

	return false
}

// SetCallDurationS gets a reference to the given float32 and assigns it to the CallDurationS field.
func (o *RiskAuditMetaV2) SetCallDurationS(v float32) {
	o.CallDurationS = &v
}

// GetAnalyzedAt returns the AnalyzedAt field value if set, zero value otherwise.
func (o *RiskAuditMetaV2) GetAnalyzedAt() string {
	if o == nil || IsNil(o.AnalyzedAt) {
		var ret string
		return ret
	}
	return *o.AnalyzedAt
}

// GetAnalyzedAtOk returns a tuple with the AnalyzedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetAnalyzedAtOk() (*string, bool) {
	if o == nil || IsNil(o.AnalyzedAt) {
		return nil, false
	}
	return o.AnalyzedAt, true
}

// HasAnalyzedAt returns a boolean if a field has been set.
func (o *RiskAuditMetaV2) HasAnalyzedAt() bool {
	if o != nil && !IsNil(o.AnalyzedAt) {
		return true
	}

	return false
}

// SetAnalyzedAt gets a reference to the given string and assigns it to the AnalyzedAt field.
func (o *RiskAuditMetaV2) SetAnalyzedAt(v string) {
	o.AnalyzedAt = &v
}

// GetUsage returns the Usage field value
func (o *RiskAuditMetaV2) GetUsage() RiskAuditUsageV2 {
	if o == nil {
		var ret RiskAuditUsageV2
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetUsageOk() (*RiskAuditUsageV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *RiskAuditMetaV2) SetUsage(v RiskAuditUsageV2) {
	o.Usage = v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *RiskAuditMetaV2) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditMetaV2) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *RiskAuditMetaV2) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *RiskAuditMetaV2) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

func (o RiskAuditMetaV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditMetaV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.CallDurationS) {
		toSerialize["call_duration_s"] = o.CallDurationS
	}
	if !IsNil(o.AnalyzedAt) {
		toSerialize["analyzed_at"] = o.AnalyzedAt
	}
	toSerialize["usage"] = o.Usage
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	return toSerialize, nil
}

func (o *RiskAuditMetaV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"usage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditMetaV2 := _RiskAuditMetaV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskAuditMetaV2)

	if err != nil {
		return err
	}

	*o = RiskAuditMetaV2(varRiskAuditMetaV2)

	return err
}

type NullableRiskAuditMetaV2 struct {
	value *RiskAuditMetaV2
	isSet bool
}

func (v NullableRiskAuditMetaV2) Get() *RiskAuditMetaV2 {
	return v.value
}

func (v *NullableRiskAuditMetaV2) Set(val *RiskAuditMetaV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditMetaV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditMetaV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditMetaV2(val *RiskAuditMetaV2) *NullableRiskAuditMetaV2 {
	return &NullableRiskAuditMetaV2{value: val, isSet: true}
}

func (v NullableRiskAuditMetaV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditMetaV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


