/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskAuditV2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditV2Response{}

// RiskAuditV2Response struct for RiskAuditV2Response
type RiskAuditV2Response struct {
	// Public response V2 — always returned
	Response RiskAuditV2 `json:"response"`
}

type _RiskAuditV2Response RiskAuditV2Response

// NewRiskAuditV2Response instantiates a new RiskAuditV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditV2Response(response RiskAuditV2) *RiskAuditV2Response {
	this := RiskAuditV2Response{}
	this.Response = response
	return &this
}

// NewRiskAuditV2ResponseWithDefaults instantiates a new RiskAuditV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditV2ResponseWithDefaults() *RiskAuditV2Response {
	this := RiskAuditV2Response{}
	return &this
}

// GetResponse returns the Response field value
func (o *RiskAuditV2Response) GetResponse() RiskAuditV2 {
	if o == nil {
		var ret RiskAuditV2
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2Response) GetResponseOk() (*RiskAuditV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *RiskAuditV2Response) SetResponse(v RiskAuditV2) {
	o.Response = v
}

func (o RiskAuditV2Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditV2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["response"] = o.Response
	return toSerialize, nil
}

func (o *RiskAuditV2Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditV2Response := _RiskAuditV2Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskAuditV2Response)

	if err != nil {
		return err
	}

	*o = RiskAuditV2Response(varRiskAuditV2Response)

	return err
}

type NullableRiskAuditV2Response struct {
	value *RiskAuditV2Response
	isSet bool
}

func (v NullableRiskAuditV2Response) Get() *RiskAuditV2Response {
	return v.value
}

func (v *NullableRiskAuditV2Response) Set(val *RiskAuditV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditV2Response(val *RiskAuditV2Response) *NullableRiskAuditV2Response {
	return &NullableRiskAuditV2Response{value: val, isSet: true}
}

func (v NullableRiskAuditV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


