/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailAlertItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAlertItem{}

// EmailAlertItem struct for EmailAlertItem
type EmailAlertItem struct {
	// Email alert id
	Id string `json:"id"`
	// Owner user id
	UserId string `json:"user_id"`
	// Email alert name
	Name string `json:"name"`
	// Destination email
	Email string `json:"email"`
	// Subscribed events
	Events []string `json:"events"`
	// Is active
	Active bool `json:"active"`
	// ISO 8601 created
	CreatedAt string `json:"created_at"`
	// ISO 8601 updated
	UpdatedAt string `json:"updated_at"`
}

type _EmailAlertItem EmailAlertItem

// NewEmailAlertItem instantiates a new EmailAlertItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAlertItem(id string, userId string, name string, email string, events []string, active bool, createdAt string, updatedAt string) *EmailAlertItem {
	this := EmailAlertItem{}
	this.Id = id
	this.UserId = userId
	this.Name = name
	this.Email = email
	this.Events = events
	this.Active = active
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEmailAlertItemWithDefaults instantiates a new EmailAlertItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailAlertItemWithDefaults() *EmailAlertItem {
	this := EmailAlertItem{}
	return &this
}

// GetId returns the Id field value
func (o *EmailAlertItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmailAlertItem) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *EmailAlertItem) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *EmailAlertItem) SetUserId(v string) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *EmailAlertItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmailAlertItem) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *EmailAlertItem) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailAlertItem) SetEmail(v string) {
	o.Email = v
}

// GetEvents returns the Events field value
func (o *EmailAlertItem) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EmailAlertItem) SetEvents(v []string) {
	o.Events = v
}

// GetActive returns the Active field value
func (o *EmailAlertItem) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *EmailAlertItem) SetActive(v bool) {
	o.Active = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmailAlertItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmailAlertItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EmailAlertItem) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EmailAlertItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EmailAlertItem) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o EmailAlertItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAlertItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["user_id"] = o.UserId
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	toSerialize["events"] = o.Events
	toSerialize["active"] = o.Active
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *EmailAlertItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"user_id",
		"name",
		"email",
		"events",
		"active",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailAlertItem := _EmailAlertItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailAlertItem)

	if err != nil {
		return err
	}

	*o = EmailAlertItem(varEmailAlertItem)

	return err
}

type NullableEmailAlertItem struct {
	value *EmailAlertItem
	isSet bool
}

func (v NullableEmailAlertItem) Get() *EmailAlertItem {
	return v.value
}

func (v *NullableEmailAlertItem) Set(val *EmailAlertItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAlertItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAlertItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAlertItem(val *EmailAlertItem) *NullableEmailAlertItem {
	return &NullableEmailAlertItem{value: val, isSet: true}
}

func (v NullableEmailAlertItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAlertItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


