/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiagnosticRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticRequest{}

// DiagnosticRequest struct for DiagnosticRequest
type DiagnosticRequest struct {
	// Analysis model. Always 'falaai-diagnostic-1'
	Model *string `json:"model,omitempty"`
	// Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
	Text *string `json:"text,omitempty"`
	// Diarized transcript with speaker turns. PRIMARY source. At least one of 'dialog' or 'text' required. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
	Dialog *string `json:"dialog,omitempty"`
	// Detected audio events with timestamps (required when using dialog)
	AudioEvents []DiagnosticAudioEvent `json:"audio_events,omitempty"`
	// Transcript language. Required. Accepted: en-US, pt-BR, es-ES, es-MX, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB
	Language string `json:"language"`
	// Language for the analysis results (labels, categories, levels). Can differ from 'language' (input). If omitted, uses 'language'. Accepted: en-US, es-ES, es-MX, pt-BR, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB.
	ResponseLanguage *string `json:"response_language,omitempty"`
	// Total audio duration in seconds. Required. Max 3h (10800s).
	DurationSeconds float32 `json:"duration_seconds"`
	// Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
	// Who originated the call. inbound=client called, outbound=company called. If omitted, the LLM infers from context.
	CallDirection *string `json:"call_direction,omitempty"`
	// Explicit participant roles. If omitted, the LLM infers from the dialog. When provided, used as ground truth (no inference) and echoed in analysis.participants_identified.
	Participants []DiagnosticParticipant `json:"participants,omitempty"`
}

type _DiagnosticRequest DiagnosticRequest

// NewDiagnosticRequest instantiates a new DiagnosticRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticRequest(language string, durationSeconds float32) *DiagnosticRequest {
	this := DiagnosticRequest{}
	var model string = "falaai-diagnostic-1"
	this.Model = &model
	var text string = ""
	this.Text = &text
	var dialog string = ""
	this.Dialog = &dialog
	this.Language = language
	this.DurationSeconds = durationSeconds
	return &this
}

// NewDiagnosticRequestWithDefaults instantiates a new DiagnosticRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticRequestWithDefaults() *DiagnosticRequest {
	this := DiagnosticRequest{}
	var model string = "falaai-diagnostic-1"
	this.Model = &model
	var text string = ""
	this.Text = &text
	var dialog string = ""
	this.Dialog = &dialog
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *DiagnosticRequest) SetModel(v string) {
	o.Model = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *DiagnosticRequest) SetText(v string) {
	o.Text = &v
}

// GetDialog returns the Dialog field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetDialog() string {
	if o == nil || IsNil(o.Dialog) {
		var ret string
		return ret
	}
	return *o.Dialog
}

// GetDialogOk returns a tuple with the Dialog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetDialogOk() (*string, bool) {
	if o == nil || IsNil(o.Dialog) {
		return nil, false
	}
	return o.Dialog, true
}

// HasDialog returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasDialog() bool {
	if o != nil && !IsNil(o.Dialog) {
		return true
	}

	return false
}

// SetDialog gets a reference to the given string and assigns it to the Dialog field.
func (o *DiagnosticRequest) SetDialog(v string) {
	o.Dialog = &v
}

// GetAudioEvents returns the AudioEvents field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetAudioEvents() []DiagnosticAudioEvent {
	if o == nil || IsNil(o.AudioEvents) {
		var ret []DiagnosticAudioEvent
		return ret
	}
	return o.AudioEvents
}

// GetAudioEventsOk returns a tuple with the AudioEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetAudioEventsOk() ([]DiagnosticAudioEvent, bool) {
	if o == nil || IsNil(o.AudioEvents) {
		return nil, false
	}
	return o.AudioEvents, true
}

// HasAudioEvents returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasAudioEvents() bool {
	if o != nil && !IsNil(o.AudioEvents) {
		return true
	}

	return false
}

// SetAudioEvents gets a reference to the given []DiagnosticAudioEvent and assigns it to the AudioEvents field.
func (o *DiagnosticRequest) SetAudioEvents(v []DiagnosticAudioEvent) {
	o.AudioEvents = v
}

// GetLanguage returns the Language field value
func (o *DiagnosticRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *DiagnosticRequest) SetLanguage(v string) {
	o.Language = v
}

// GetResponseLanguage returns the ResponseLanguage field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetResponseLanguage() string {
	if o == nil || IsNil(o.ResponseLanguage) {
		var ret string
		return ret
	}
	return *o.ResponseLanguage
}

// GetResponseLanguageOk returns a tuple with the ResponseLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetResponseLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseLanguage) {
		return nil, false
	}
	return o.ResponseLanguage, true
}

// HasResponseLanguage returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasResponseLanguage() bool {
	if o != nil && !IsNil(o.ResponseLanguage) {
		return true
	}

	return false
}

// SetResponseLanguage gets a reference to the given string and assigns it to the ResponseLanguage field.
func (o *DiagnosticRequest) SetResponseLanguage(v string) {
	o.ResponseLanguage = &v
}

// GetDurationSeconds returns the DurationSeconds field value
func (o *DiagnosticRequest) GetDurationSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationSeconds, true
}

// SetDurationSeconds sets field value
func (o *DiagnosticRequest) SetDurationSeconds(v float32) {
	o.DurationSeconds = v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *DiagnosticRequest) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

// GetCallDirection returns the CallDirection field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetCallDirection() string {
	if o == nil || IsNil(o.CallDirection) {
		var ret string
		return ret
	}
	return *o.CallDirection
}

// GetCallDirectionOk returns a tuple with the CallDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetCallDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.CallDirection) {
		return nil, false
	}
	return o.CallDirection, true
}

// HasCallDirection returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasCallDirection() bool {
	if o != nil && !IsNil(o.CallDirection) {
		return true
	}

	return false
}

// SetCallDirection gets a reference to the given string and assigns it to the CallDirection field.
func (o *DiagnosticRequest) SetCallDirection(v string) {
	o.CallDirection = &v
}

// GetParticipants returns the Participants field value if set, zero value otherwise.
func (o *DiagnosticRequest) GetParticipants() []DiagnosticParticipant {
	if o == nil || IsNil(o.Participants) {
		var ret []DiagnosticParticipant
		return ret
	}
	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticRequest) GetParticipantsOk() ([]DiagnosticParticipant, bool) {
	if o == nil || IsNil(o.Participants) {
		return nil, false
	}
	return o.Participants, true
}

// HasParticipants returns a boolean if a field has been set.
func (o *DiagnosticRequest) HasParticipants() bool {
	if o != nil && !IsNil(o.Participants) {
		return true
	}

	return false
}

// SetParticipants gets a reference to the given []DiagnosticParticipant and assigns it to the Participants field.
func (o *DiagnosticRequest) SetParticipants(v []DiagnosticParticipant) {
	o.Participants = v
}

func (o DiagnosticRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Dialog) {
		toSerialize["dialog"] = o.Dialog
	}
	if !IsNil(o.AudioEvents) {
		toSerialize["audio_events"] = o.AudioEvents
	}
	toSerialize["language"] = o.Language
	if !IsNil(o.ResponseLanguage) {
		toSerialize["response_language"] = o.ResponseLanguage
	}
	toSerialize["duration_seconds"] = o.DurationSeconds
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	if !IsNil(o.CallDirection) {
		toSerialize["call_direction"] = o.CallDirection
	}
	if !IsNil(o.Participants) {
		toSerialize["participants"] = o.Participants
	}
	return toSerialize, nil
}

func (o *DiagnosticRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"language",
		"duration_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiagnosticRequest := _DiagnosticRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiagnosticRequest)

	if err != nil {
		return err
	}

	*o = DiagnosticRequest(varDiagnosticRequest)

	return err
}

type NullableDiagnosticRequest struct {
	value *DiagnosticRequest
	isSet bool
}

func (v NullableDiagnosticRequest) Get() *DiagnosticRequest {
	return v.value
}

func (v *NullableDiagnosticRequest) Set(val *DiagnosticRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticRequest(val *DiagnosticRequest) *NullableDiagnosticRequest {
	return &NullableDiagnosticRequest{value: val, isSet: true}
}

func (v NullableDiagnosticRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


