/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditDetectionsV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditDetectionsV2{}

// RiskAuditDetectionsV2 struct for RiskAuditDetectionsV2
type RiskAuditDetectionsV2 struct {
	// Active violations
	Violations []RiskAuditDetectionItemV2 `json:"violations,omitempty"`
	// Active positives
	Positives []RiskAuditDetectionItemV2 `json:"positives,omitempty"`
	// Client risk alerts
	ClientRiskAlerts []map[string]interface{} `json:"client_risk_alerts,omitempty"`
	// Client behavior alerts
	ClientBehaviorAlerts []map[string]interface{} `json:"client_behavior_alerts,omitempty"`
	// Client negatives
	ClientNegatives []RiskAuditDetectionItemV2 `json:"client_negatives,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditDetectionsV2 RiskAuditDetectionsV2

// NewRiskAuditDetectionsV2 instantiates a new RiskAuditDetectionsV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditDetectionsV2() *RiskAuditDetectionsV2 {
	this := RiskAuditDetectionsV2{}
	return &this
}

// NewRiskAuditDetectionsV2WithDefaults instantiates a new RiskAuditDetectionsV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditDetectionsV2WithDefaults() *RiskAuditDetectionsV2 {
	this := RiskAuditDetectionsV2{}
	return &this
}

// GetViolations returns the Violations field value if set, zero value otherwise.
func (o *RiskAuditDetectionsV2) GetViolations() []RiskAuditDetectionItemV2 {
	if o == nil || IsNil(o.Violations) {
		var ret []RiskAuditDetectionItemV2
		return ret
	}
	return o.Violations
}

// GetViolationsOk returns a tuple with the Violations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditDetectionsV2) GetViolationsOk() ([]RiskAuditDetectionItemV2, bool) {
	if o == nil || IsNil(o.Violations) {
		return nil, false
	}
	return o.Violations, true
}

// HasViolations returns a boolean if a field has been set.
func (o *RiskAuditDetectionsV2) HasViolations() bool {
	if o != nil && !IsNil(o.Violations) {
		return true
	}

	return false
}

// SetViolations gets a reference to the given []RiskAuditDetectionItemV2 and assigns it to the Violations field.
func (o *RiskAuditDetectionsV2) SetViolations(v []RiskAuditDetectionItemV2) {
	o.Violations = v
}

// GetPositives returns the Positives field value if set, zero value otherwise.
func (o *RiskAuditDetectionsV2) GetPositives() []RiskAuditDetectionItemV2 {
	if o == nil || IsNil(o.Positives) {
		var ret []RiskAuditDetectionItemV2
		return ret
	}
	return o.Positives
}

// GetPositivesOk returns a tuple with the Positives field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditDetectionsV2) GetPositivesOk() ([]RiskAuditDetectionItemV2, bool) {
	if o == nil || IsNil(o.Positives) {
		return nil, false
	}
	return o.Positives, true
}

// HasPositives returns a boolean if a field has been set.
func (o *RiskAuditDetectionsV2) HasPositives() bool {
	if o != nil && !IsNil(o.Positives) {
		return true
	}

	return false
}

// SetPositives gets a reference to the given []RiskAuditDetectionItemV2 and assigns it to the Positives field.
func (o *RiskAuditDetectionsV2) SetPositives(v []RiskAuditDetectionItemV2) {
	o.Positives = v
}

// GetClientRiskAlerts returns the ClientRiskAlerts field value if set, zero value otherwise.
func (o *RiskAuditDetectionsV2) GetClientRiskAlerts() []map[string]interface{} {
	if o == nil || IsNil(o.ClientRiskAlerts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ClientRiskAlerts
}

// GetClientRiskAlertsOk returns a tuple with the ClientRiskAlerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditDetectionsV2) GetClientRiskAlertsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ClientRiskAlerts) {
		return nil, false
	}
	return o.ClientRiskAlerts, true
}

// HasClientRiskAlerts returns a boolean if a field has been set.
func (o *RiskAuditDetectionsV2) HasClientRiskAlerts() bool {
	if o != nil && !IsNil(o.ClientRiskAlerts) {
		return true
	}

	return false
}

// SetClientRiskAlerts gets a reference to the given []map[string]interface{} and assigns it to the ClientRiskAlerts field.
func (o *RiskAuditDetectionsV2) SetClientRiskAlerts(v []map[string]interface{}) {
	o.ClientRiskAlerts = v
}

// GetClientBehaviorAlerts returns the ClientBehaviorAlerts field value if set, zero value otherwise.
func (o *RiskAuditDetectionsV2) GetClientBehaviorAlerts() []map[string]interface{} {
	if o == nil || IsNil(o.ClientBehaviorAlerts) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ClientBehaviorAlerts
}

// GetClientBehaviorAlertsOk returns a tuple with the ClientBehaviorAlerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditDetectionsV2) GetClientBehaviorAlertsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ClientBehaviorAlerts) {
		return nil, false
	}
	return o.ClientBehaviorAlerts, true
}

// HasClientBehaviorAlerts returns a boolean if a field has been set.
func (o *RiskAuditDetectionsV2) HasClientBehaviorAlerts() bool {
	if o != nil && !IsNil(o.ClientBehaviorAlerts) {
		return true
	}

	return false
}

// SetClientBehaviorAlerts gets a reference to the given []map[string]interface{} and assigns it to the ClientBehaviorAlerts field.
func (o *RiskAuditDetectionsV2) SetClientBehaviorAlerts(v []map[string]interface{}) {
	o.ClientBehaviorAlerts = v
}

// GetClientNegatives returns the ClientNegatives field value if set, zero value otherwise.
func (o *RiskAuditDetectionsV2) GetClientNegatives() []RiskAuditDetectionItemV2 {
	if o == nil || IsNil(o.ClientNegatives) {
		var ret []RiskAuditDetectionItemV2
		return ret
	}
	return o.ClientNegatives
}

// GetClientNegativesOk returns a tuple with the ClientNegatives field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditDetectionsV2) GetClientNegativesOk() ([]RiskAuditDetectionItemV2, bool) {
	if o == nil || IsNil(o.ClientNegatives) {
		return nil, false
	}
	return o.ClientNegatives, true
}

// HasClientNegatives returns a boolean if a field has been set.
func (o *RiskAuditDetectionsV2) HasClientNegatives() bool {
	if o != nil && !IsNil(o.ClientNegatives) {
		return true
	}

	return false
}

// SetClientNegatives gets a reference to the given []RiskAuditDetectionItemV2 and assigns it to the ClientNegatives field.
func (o *RiskAuditDetectionsV2) SetClientNegatives(v []RiskAuditDetectionItemV2) {
	o.ClientNegatives = v
}

func (o RiskAuditDetectionsV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditDetectionsV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Violations) {
		toSerialize["violations"] = o.Violations
	}
	if !IsNil(o.Positives) {
		toSerialize["positives"] = o.Positives
	}
	if !IsNil(o.ClientRiskAlerts) {
		toSerialize["client_risk_alerts"] = o.ClientRiskAlerts
	}
	if !IsNil(o.ClientBehaviorAlerts) {
		toSerialize["client_behavior_alerts"] = o.ClientBehaviorAlerts
	}
	if !IsNil(o.ClientNegatives) {
		toSerialize["client_negatives"] = o.ClientNegatives
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditDetectionsV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditDetectionsV2 := _RiskAuditDetectionsV2{}

	err = json.Unmarshal(data, &varRiskAuditDetectionsV2)

	if err != nil {
		return err
	}

	*o = RiskAuditDetectionsV2(varRiskAuditDetectionsV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "violations")
		delete(additionalProperties, "positives")
		delete(additionalProperties, "client_risk_alerts")
		delete(additionalProperties, "client_behavior_alerts")
		delete(additionalProperties, "client_negatives")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditDetectionsV2 struct {
	value *RiskAuditDetectionsV2
	isSet bool
}

func (v NullableRiskAuditDetectionsV2) Get() *RiskAuditDetectionsV2 {
	return v.value
}

func (v *NullableRiskAuditDetectionsV2) Set(val *RiskAuditDetectionsV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditDetectionsV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditDetectionsV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditDetectionsV2(val *RiskAuditDetectionsV2) *NullableRiskAuditDetectionsV2 {
	return &NullableRiskAuditDetectionsV2{value: val, isSet: true}
}

func (v NullableRiskAuditDetectionsV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditDetectionsV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


