/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TranscriptionUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptionUsage{}

// TranscriptionUsage struct for TranscriptionUsage
type TranscriptionUsage struct {
	// Actual audio duration processed in seconds
	AudioSeconds float32 `json:"audio_seconds"`
	// Number of credits consumed in this request
	CreditsConsumed int32 `json:"credits_consumed"`
	// Total processing time in milliseconds
	ProcessingMs int32 `json:"processing_ms"`
}

type _TranscriptionUsage TranscriptionUsage

// NewTranscriptionUsage instantiates a new TranscriptionUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptionUsage(audioSeconds float32, creditsConsumed int32, processingMs int32) *TranscriptionUsage {
	this := TranscriptionUsage{}
	this.AudioSeconds = audioSeconds
	this.CreditsConsumed = creditsConsumed
	this.ProcessingMs = processingMs
	return &this
}

// NewTranscriptionUsageWithDefaults instantiates a new TranscriptionUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptionUsageWithDefaults() *TranscriptionUsage {
	this := TranscriptionUsage{}
	return &this
}

// GetAudioSeconds returns the AudioSeconds field value
func (o *TranscriptionUsage) GetAudioSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AudioSeconds
}

// GetAudioSecondsOk returns a tuple with the AudioSeconds field value
// and a boolean to check if the value has been set.
func (o *TranscriptionUsage) GetAudioSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioSeconds, true
}

// SetAudioSeconds sets field value
func (o *TranscriptionUsage) SetAudioSeconds(v float32) {
	o.AudioSeconds = v
}

// GetCreditsConsumed returns the CreditsConsumed field value
func (o *TranscriptionUsage) GetCreditsConsumed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsConsumed
}

// GetCreditsConsumedOk returns a tuple with the CreditsConsumed field value
// and a boolean to check if the value has been set.
func (o *TranscriptionUsage) GetCreditsConsumedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsConsumed, true
}

// SetCreditsConsumed sets field value
func (o *TranscriptionUsage) SetCreditsConsumed(v int32) {
	o.CreditsConsumed = v
}

// GetProcessingMs returns the ProcessingMs field value
func (o *TranscriptionUsage) GetProcessingMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessingMs
}

// GetProcessingMsOk returns a tuple with the ProcessingMs field value
// and a boolean to check if the value has been set.
func (o *TranscriptionUsage) GetProcessingMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingMs, true
}

// SetProcessingMs sets field value
func (o *TranscriptionUsage) SetProcessingMs(v int32) {
	o.ProcessingMs = v
}

func (o TranscriptionUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptionUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audio_seconds"] = o.AudioSeconds
	toSerialize["credits_consumed"] = o.CreditsConsumed
	toSerialize["processing_ms"] = o.ProcessingMs
	return toSerialize, nil
}

func (o *TranscriptionUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audio_seconds",
		"credits_consumed",
		"processing_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscriptionUsage := _TranscriptionUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTranscriptionUsage)

	if err != nil {
		return err
	}

	*o = TranscriptionUsage(varTranscriptionUsage)

	return err
}

type NullableTranscriptionUsage struct {
	value *TranscriptionUsage
	isSet bool
}

func (v NullableTranscriptionUsage) Get() *TranscriptionUsage {
	return v.value
}

func (v *NullableTranscriptionUsage) Set(val *TranscriptionUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptionUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptionUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptionUsage(val *TranscriptionUsage) *NullableTranscriptionUsage {
	return &NullableTranscriptionUsage{value: val, isSet: true}
}

func (v NullableTranscriptionUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptionUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


