/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"fmt"
)

// EmailEvent the model 'EmailEvent'
type EmailEvent string

// List of EmailEvent
const (
	EMAILEVENT_SUBSCRIPTION_CREATED EmailEvent = "subscription.created"
	EMAILEVENT_AVULSO_COMPLETED EmailEvent = "avulso.completed"
	EMAILEVENT_SUBSCRIPTION_UPGRADED EmailEvent = "subscription.upgraded"
	EMAILEVENT_SUBSCRIPTION_DOWNGRADED EmailEvent = "subscription.downgraded"
	EMAILEVENT_SUBSCRIPTION_CANCELED EmailEvent = "subscription.canceled"
	EMAILEVENT_CREDITS_LOW EmailEvent = "credits.low"
	EMAILEVENT_CREDITS_EXHAUSTED EmailEvent = "credits.exhausted"
	EMAILEVENT_SUBSCRIPTION_RENEWED EmailEvent = "subscription.renewed"
	EMAILEVENT_PAYMENT_FAILED EmailEvent = "payment.failed"
)

// All allowed values of EmailEvent enum
var AllowedEmailEventEnumValues = []EmailEvent{
	"subscription.created",
	"avulso.completed",
	"subscription.upgraded",
	"subscription.downgraded",
	"subscription.canceled",
	"credits.low",
	"credits.exhausted",
	"subscription.renewed",
	"payment.failed",
}

func (v *EmailEvent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EmailEvent(value)
	for _, existing := range AllowedEmailEventEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EmailEvent", value)
}

// NewEmailEventFromValue returns a pointer to a valid EmailEvent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEmailEventFromValue(v string) (*EmailEvent, error) {
	ev := EmailEvent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EmailEvent: valid values are %v", v, AllowedEmailEventEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EmailEvent) IsValid() bool {
	for _, existing := range AllowedEmailEventEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EmailEvent value
func (v EmailEvent) Ptr() *EmailEvent {
	return &v
}

type NullableEmailEvent struct {
	value *EmailEvent
	isSet bool
}

func (v NullableEmailEvent) Get() *EmailEvent {
	return v.value
}

func (v *NullableEmailEvent) Set(val *EmailEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailEvent(val *EmailEvent) *NullableEmailEvent {
	return &NullableEmailEvent{value: val, isSet: true}
}

func (v NullableEmailEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

