/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditTimelineV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditTimelineV2{}

// RiskAuditTimelineV2 struct for RiskAuditTimelineV2
type RiskAuditTimelineV2 struct {
	// Per-turn sentiment
	TurnsSentiment []map[string]interface{} `json:"turns_sentiment,omitempty"`
	// Audio events (i18n)
	AudioEvents []map[string]interface{} `json:"audio_events,omitempty"`
	// Audio groups found
	AudioGroupsFound []map[string]interface{} `json:"audio_groups_found,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditTimelineV2 RiskAuditTimelineV2

// NewRiskAuditTimelineV2 instantiates a new RiskAuditTimelineV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditTimelineV2() *RiskAuditTimelineV2 {
	this := RiskAuditTimelineV2{}
	return &this
}

// NewRiskAuditTimelineV2WithDefaults instantiates a new RiskAuditTimelineV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditTimelineV2WithDefaults() *RiskAuditTimelineV2 {
	this := RiskAuditTimelineV2{}
	return &this
}

// GetTurnsSentiment returns the TurnsSentiment field value if set, zero value otherwise.
func (o *RiskAuditTimelineV2) GetTurnsSentiment() []map[string]interface{} {
	if o == nil || IsNil(o.TurnsSentiment) {
		var ret []map[string]interface{}
		return ret
	}
	return o.TurnsSentiment
}

// GetTurnsSentimentOk returns a tuple with the TurnsSentiment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditTimelineV2) GetTurnsSentimentOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.TurnsSentiment) {
		return nil, false
	}
	return o.TurnsSentiment, true
}

// HasTurnsSentiment returns a boolean if a field has been set.
func (o *RiskAuditTimelineV2) HasTurnsSentiment() bool {
	if o != nil && !IsNil(o.TurnsSentiment) {
		return true
	}

	return false
}

// SetTurnsSentiment gets a reference to the given []map[string]interface{} and assigns it to the TurnsSentiment field.
func (o *RiskAuditTimelineV2) SetTurnsSentiment(v []map[string]interface{}) {
	o.TurnsSentiment = v
}

// GetAudioEvents returns the AudioEvents field value if set, zero value otherwise.
func (o *RiskAuditTimelineV2) GetAudioEvents() []map[string]interface{} {
	if o == nil || IsNil(o.AudioEvents) {
		var ret []map[string]interface{}
		return ret
	}
	return o.AudioEvents
}

// GetAudioEventsOk returns a tuple with the AudioEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditTimelineV2) GetAudioEventsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AudioEvents) {
		return nil, false
	}
	return o.AudioEvents, true
}

// HasAudioEvents returns a boolean if a field has been set.
func (o *RiskAuditTimelineV2) HasAudioEvents() bool {
	if o != nil && !IsNil(o.AudioEvents) {
		return true
	}

	return false
}

// SetAudioEvents gets a reference to the given []map[string]interface{} and assigns it to the AudioEvents field.
func (o *RiskAuditTimelineV2) SetAudioEvents(v []map[string]interface{}) {
	o.AudioEvents = v
}

// GetAudioGroupsFound returns the AudioGroupsFound field value if set, zero value otherwise.
func (o *RiskAuditTimelineV2) GetAudioGroupsFound() []map[string]interface{} {
	if o == nil || IsNil(o.AudioGroupsFound) {
		var ret []map[string]interface{}
		return ret
	}
	return o.AudioGroupsFound
}

// GetAudioGroupsFoundOk returns a tuple with the AudioGroupsFound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditTimelineV2) GetAudioGroupsFoundOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AudioGroupsFound) {
		return nil, false
	}
	return o.AudioGroupsFound, true
}

// HasAudioGroupsFound returns a boolean if a field has been set.
func (o *RiskAuditTimelineV2) HasAudioGroupsFound() bool {
	if o != nil && !IsNil(o.AudioGroupsFound) {
		return true
	}

	return false
}

// SetAudioGroupsFound gets a reference to the given []map[string]interface{} and assigns it to the AudioGroupsFound field.
func (o *RiskAuditTimelineV2) SetAudioGroupsFound(v []map[string]interface{}) {
	o.AudioGroupsFound = v
}

func (o RiskAuditTimelineV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditTimelineV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TurnsSentiment) {
		toSerialize["turns_sentiment"] = o.TurnsSentiment
	}
	if !IsNil(o.AudioEvents) {
		toSerialize["audio_events"] = o.AudioEvents
	}
	if !IsNil(o.AudioGroupsFound) {
		toSerialize["audio_groups_found"] = o.AudioGroupsFound
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditTimelineV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditTimelineV2 := _RiskAuditTimelineV2{}

	err = json.Unmarshal(data, &varRiskAuditTimelineV2)

	if err != nil {
		return err
	}

	*o = RiskAuditTimelineV2(varRiskAuditTimelineV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "turns_sentiment")
		delete(additionalProperties, "audio_events")
		delete(additionalProperties, "audio_groups_found")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditTimelineV2 struct {
	value *RiskAuditTimelineV2
	isSet bool
}

func (v NullableRiskAuditTimelineV2) Get() *RiskAuditTimelineV2 {
	return v.value
}

func (v *NullableRiskAuditTimelineV2) Set(val *RiskAuditTimelineV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditTimelineV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditTimelineV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditTimelineV2(val *RiskAuditTimelineV2) *NullableRiskAuditTimelineV2 {
	return &NullableRiskAuditTimelineV2{value: val, isSet: true}
}

func (v NullableRiskAuditTimelineV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditTimelineV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


