/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditIndexerV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditIndexerV2{}

// RiskAuditIndexerV2 struct for RiskAuditIndexerV2
type RiskAuditIndexerV2 struct {
	// Suggested terms for bank
	SuggestedTermsForBank []map[string]interface{} `json:"suggested_terms_for_bank,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditIndexerV2 RiskAuditIndexerV2

// NewRiskAuditIndexerV2 instantiates a new RiskAuditIndexerV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditIndexerV2() *RiskAuditIndexerV2 {
	this := RiskAuditIndexerV2{}
	return &this
}

// NewRiskAuditIndexerV2WithDefaults instantiates a new RiskAuditIndexerV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditIndexerV2WithDefaults() *RiskAuditIndexerV2 {
	this := RiskAuditIndexerV2{}
	return &this
}

// GetSuggestedTermsForBank returns the SuggestedTermsForBank field value if set, zero value otherwise.
func (o *RiskAuditIndexerV2) GetSuggestedTermsForBank() []map[string]interface{} {
	if o == nil || IsNil(o.SuggestedTermsForBank) {
		var ret []map[string]interface{}
		return ret
	}
	return o.SuggestedTermsForBank
}

// GetSuggestedTermsForBankOk returns a tuple with the SuggestedTermsForBank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditIndexerV2) GetSuggestedTermsForBankOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.SuggestedTermsForBank) {
		return nil, false
	}
	return o.SuggestedTermsForBank, true
}

// HasSuggestedTermsForBank returns a boolean if a field has been set.
func (o *RiskAuditIndexerV2) HasSuggestedTermsForBank() bool {
	if o != nil && !IsNil(o.SuggestedTermsForBank) {
		return true
	}

	return false
}

// SetSuggestedTermsForBank gets a reference to the given []map[string]interface{} and assigns it to the SuggestedTermsForBank field.
func (o *RiskAuditIndexerV2) SetSuggestedTermsForBank(v []map[string]interface{}) {
	o.SuggestedTermsForBank = v
}

func (o RiskAuditIndexerV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditIndexerV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SuggestedTermsForBank) {
		toSerialize["suggested_terms_for_bank"] = o.SuggestedTermsForBank
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditIndexerV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditIndexerV2 := _RiskAuditIndexerV2{}

	err = json.Unmarshal(data, &varRiskAuditIndexerV2)

	if err != nil {
		return err
	}

	*o = RiskAuditIndexerV2(varRiskAuditIndexerV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "suggested_terms_for_bank")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditIndexerV2 struct {
	value *RiskAuditIndexerV2
	isSet bool
}

func (v NullableRiskAuditIndexerV2) Get() *RiskAuditIndexerV2 {
	return v.value
}

func (v *NullableRiskAuditIndexerV2) Set(val *RiskAuditIndexerV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditIndexerV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditIndexerV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditIndexerV2(val *RiskAuditIndexerV2) *NullableRiskAuditIndexerV2 {
	return &NullableRiskAuditIndexerV2{value: val, isSet: true}
}

func (v NullableRiskAuditIndexerV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditIndexerV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


