/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskAuditRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditRequest{}

// RiskAuditRequest struct for RiskAuditRequest
type RiskAuditRequest struct {
	// Analysis model. Always 'falaai-risk-audit-1'
	Model *string `json:"model,omitempty"`
	// Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
	Text *string `json:"text,omitempty"`
	// Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
	Dialog *string `json:"dialog,omitempty"`
	// Audio events with timestamps (correlated with turns when diarization is present)
	AudioEvents []DiagnosticAudioEvent `json:"audio_events,omitempty"`
	// Total audio duration in seconds. Required. Max 3h (10800s).
	DurationSeconds float32 `json:"duration_seconds"`
	// Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
	Language string `json:"language"`
	// Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from 'language'. Accepted: pt-BR, en-US, es-ES.
	ResponseLanguage string `json:"response_language"`
	// Who originated the call. inbound=client called, outbound=company called. If omitted, LLM infers from context.
	CallDirection *string `json:"call_direction,omitempty"`
	// Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth — no inference.
	Participants []Participant `json:"participants,omitempty"`
	// Response format version. Only 'v2' (structured EN-US blocks) is available today.
	ResponseFormat *string `json:"response_format,omitempty"`
	// Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
}

type _RiskAuditRequest RiskAuditRequest

// NewRiskAuditRequest instantiates a new RiskAuditRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditRequest(durationSeconds float32, language string, responseLanguage string) *RiskAuditRequest {
	this := RiskAuditRequest{}
	var model string = "falaai-risk-audit-1"
	this.Model = &model
	var text string = ""
	this.Text = &text
	var dialog string = ""
	this.Dialog = &dialog
	this.DurationSeconds = durationSeconds
	this.Language = language
	this.ResponseLanguage = responseLanguage
	var responseFormat string = "v2"
	this.ResponseFormat = &responseFormat
	return &this
}

// NewRiskAuditRequestWithDefaults instantiates a new RiskAuditRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditRequestWithDefaults() *RiskAuditRequest {
	this := RiskAuditRequest{}
	var model string = "falaai-risk-audit-1"
	this.Model = &model
	var text string = ""
	this.Text = &text
	var dialog string = ""
	this.Dialog = &dialog
	var responseFormat string = "v2"
	this.ResponseFormat = &responseFormat
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *RiskAuditRequest) SetModel(v string) {
	o.Model = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RiskAuditRequest) SetText(v string) {
	o.Text = &v
}

// GetDialog returns the Dialog field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetDialog() string {
	if o == nil || IsNil(o.Dialog) {
		var ret string
		return ret
	}
	return *o.Dialog
}

// GetDialogOk returns a tuple with the Dialog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetDialogOk() (*string, bool) {
	if o == nil || IsNil(o.Dialog) {
		return nil, false
	}
	return o.Dialog, true
}

// HasDialog returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasDialog() bool {
	if o != nil && !IsNil(o.Dialog) {
		return true
	}

	return false
}

// SetDialog gets a reference to the given string and assigns it to the Dialog field.
func (o *RiskAuditRequest) SetDialog(v string) {
	o.Dialog = &v
}

// GetAudioEvents returns the AudioEvents field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetAudioEvents() []DiagnosticAudioEvent {
	if o == nil || IsNil(o.AudioEvents) {
		var ret []DiagnosticAudioEvent
		return ret
	}
	return o.AudioEvents
}

// GetAudioEventsOk returns a tuple with the AudioEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetAudioEventsOk() ([]DiagnosticAudioEvent, bool) {
	if o == nil || IsNil(o.AudioEvents) {
		return nil, false
	}
	return o.AudioEvents, true
}

// HasAudioEvents returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasAudioEvents() bool {
	if o != nil && !IsNil(o.AudioEvents) {
		return true
	}

	return false
}

// SetAudioEvents gets a reference to the given []DiagnosticAudioEvent and assigns it to the AudioEvents field.
func (o *RiskAuditRequest) SetAudioEvents(v []DiagnosticAudioEvent) {
	o.AudioEvents = v
}

// GetDurationSeconds returns the DurationSeconds field value
func (o *RiskAuditRequest) GetDurationSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationSeconds, true
}

// SetDurationSeconds sets field value
func (o *RiskAuditRequest) SetDurationSeconds(v float32) {
	o.DurationSeconds = v
}

// GetLanguage returns the Language field value
func (o *RiskAuditRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *RiskAuditRequest) SetLanguage(v string) {
	o.Language = v
}

// GetResponseLanguage returns the ResponseLanguage field value
func (o *RiskAuditRequest) GetResponseLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseLanguage
}

// GetResponseLanguageOk returns a tuple with the ResponseLanguage field value
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetResponseLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseLanguage, true
}

// SetResponseLanguage sets field value
func (o *RiskAuditRequest) SetResponseLanguage(v string) {
	o.ResponseLanguage = v
}

// GetCallDirection returns the CallDirection field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetCallDirection() string {
	if o == nil || IsNil(o.CallDirection) {
		var ret string
		return ret
	}
	return *o.CallDirection
}

// GetCallDirectionOk returns a tuple with the CallDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetCallDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.CallDirection) {
		return nil, false
	}
	return o.CallDirection, true
}

// HasCallDirection returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasCallDirection() bool {
	if o != nil && !IsNil(o.CallDirection) {
		return true
	}

	return false
}

// SetCallDirection gets a reference to the given string and assigns it to the CallDirection field.
func (o *RiskAuditRequest) SetCallDirection(v string) {
	o.CallDirection = &v
}

// GetParticipants returns the Participants field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetParticipants() []Participant {
	if o == nil || IsNil(o.Participants) {
		var ret []Participant
		return ret
	}
	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetParticipantsOk() ([]Participant, bool) {
	if o == nil || IsNil(o.Participants) {
		return nil, false
	}
	return o.Participants, true
}

// HasParticipants returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasParticipants() bool {
	if o != nil && !IsNil(o.Participants) {
		return true
	}

	return false
}

// SetParticipants gets a reference to the given []Participant and assigns it to the Participants field.
func (o *RiskAuditRequest) SetParticipants(v []Participant) {
	o.Participants = v
}

// GetResponseFormat returns the ResponseFormat field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetResponseFormat() string {
	if o == nil || IsNil(o.ResponseFormat) {
		var ret string
		return ret
	}
	return *o.ResponseFormat
}

// GetResponseFormatOk returns a tuple with the ResponseFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetResponseFormatOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseFormat) {
		return nil, false
	}
	return o.ResponseFormat, true
}

// HasResponseFormat returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasResponseFormat() bool {
	if o != nil && !IsNil(o.ResponseFormat) {
		return true
	}

	return false
}

// SetResponseFormat gets a reference to the given string and assigns it to the ResponseFormat field.
func (o *RiskAuditRequest) SetResponseFormat(v string) {
	o.ResponseFormat = &v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *RiskAuditRequest) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditRequest) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *RiskAuditRequest) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *RiskAuditRequest) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

func (o RiskAuditRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Dialog) {
		toSerialize["dialog"] = o.Dialog
	}
	if !IsNil(o.AudioEvents) {
		toSerialize["audio_events"] = o.AudioEvents
	}
	toSerialize["duration_seconds"] = o.DurationSeconds
	toSerialize["language"] = o.Language
	toSerialize["response_language"] = o.ResponseLanguage
	if !IsNil(o.CallDirection) {
		toSerialize["call_direction"] = o.CallDirection
	}
	if !IsNil(o.Participants) {
		toSerialize["participants"] = o.Participants
	}
	if !IsNil(o.ResponseFormat) {
		toSerialize["response_format"] = o.ResponseFormat
	}
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	return toSerialize, nil
}

func (o *RiskAuditRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration_seconds",
		"language",
		"response_language",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditRequest := _RiskAuditRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskAuditRequest)

	if err != nil {
		return err
	}

	*o = RiskAuditRequest(varRiskAuditRequest)

	return err
}

type NullableRiskAuditRequest struct {
	value *RiskAuditRequest
	isSet bool
}

func (v NullableRiskAuditRequest) Get() *RiskAuditRequest {
	return v.value
}

func (v *NullableRiskAuditRequest) Set(val *RiskAuditRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditRequest(val *RiskAuditRequest) *NullableRiskAuditRequest {
	return &NullableRiskAuditRequest{value: val, isSet: true}
}

func (v NullableRiskAuditRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


