/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditConversationScoresV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditConversationScoresV2{}

// RiskAuditConversationScoresV2 struct for RiskAuditConversationScoresV2
type RiskAuditConversationScoresV2 struct {
	// Consolidated score
	ConsolidatedScore *float32 `json:"consolidated_score,omitempty"`
	// Violation density/min
	ViolationDensityPerMin *float32 `json:"violation_density_per_min,omitempty"`
	// Sentiment trend
	SentimentTrend interface{} `json:"sentiment_trend,omitempty"`
	// % turns with violation
	PctTurnsWithViolation *float32 `json:"pct_turns_with_violation,omitempty"`
	// Most critical turn
	MostCriticalTurn interface{} `json:"most_critical_turn,omitempty"`
	// Positive:negative ratio
	PositiveNegativeRatio interface{} `json:"positive_negative_ratio,omitempty"`
	// Global risk severity code
	GlobalRiskSeverity *string `json:"global_risk_severity,omitempty"`
	// Global risk severity label
	GlobalRiskSeverityLabel *string `json:"global_risk_severity_label,omitempty"`
	// Global risk severity color
	GlobalRiskSeverityColor *string `json:"global_risk_severity_color,omitempty"`
	// Risk likelihood avg
	RiskLikelihoodAvg *float32 `json:"risk_likelihood_avg,omitempty"`
	// Risk impact avg
	RiskImpactAvg *float32 `json:"risk_impact_avg,omitempty"`
}

// NewRiskAuditConversationScoresV2 instantiates a new RiskAuditConversationScoresV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditConversationScoresV2() *RiskAuditConversationScoresV2 {
	this := RiskAuditConversationScoresV2{}
	return &this
}

// NewRiskAuditConversationScoresV2WithDefaults instantiates a new RiskAuditConversationScoresV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditConversationScoresV2WithDefaults() *RiskAuditConversationScoresV2 {
	this := RiskAuditConversationScoresV2{}
	return &this
}

// GetConsolidatedScore returns the ConsolidatedScore field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetConsolidatedScore() float32 {
	if o == nil || IsNil(o.ConsolidatedScore) {
		var ret float32
		return ret
	}
	return *o.ConsolidatedScore
}

// GetConsolidatedScoreOk returns a tuple with the ConsolidatedScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetConsolidatedScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ConsolidatedScore) {
		return nil, false
	}
	return o.ConsolidatedScore, true
}

// HasConsolidatedScore returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasConsolidatedScore() bool {
	if o != nil && !IsNil(o.ConsolidatedScore) {
		return true
	}

	return false
}

// SetConsolidatedScore gets a reference to the given float32 and assigns it to the ConsolidatedScore field.
func (o *RiskAuditConversationScoresV2) SetConsolidatedScore(v float32) {
	o.ConsolidatedScore = &v
}

// GetViolationDensityPerMin returns the ViolationDensityPerMin field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetViolationDensityPerMin() float32 {
	if o == nil || IsNil(o.ViolationDensityPerMin) {
		var ret float32
		return ret
	}
	return *o.ViolationDensityPerMin
}

// GetViolationDensityPerMinOk returns a tuple with the ViolationDensityPerMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetViolationDensityPerMinOk() (*float32, bool) {
	if o == nil || IsNil(o.ViolationDensityPerMin) {
		return nil, false
	}
	return o.ViolationDensityPerMin, true
}

// HasViolationDensityPerMin returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasViolationDensityPerMin() bool {
	if o != nil && !IsNil(o.ViolationDensityPerMin) {
		return true
	}

	return false
}

// SetViolationDensityPerMin gets a reference to the given float32 and assigns it to the ViolationDensityPerMin field.
func (o *RiskAuditConversationScoresV2) SetViolationDensityPerMin(v float32) {
	o.ViolationDensityPerMin = &v
}

// GetSentimentTrend returns the SentimentTrend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditConversationScoresV2) GetSentimentTrend() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SentimentTrend
}

// GetSentimentTrendOk returns a tuple with the SentimentTrend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditConversationScoresV2) GetSentimentTrendOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SentimentTrend) {
		return nil, false
	}
	return &o.SentimentTrend, true
}

// HasSentimentTrend returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasSentimentTrend() bool {
	if o != nil && !IsNil(o.SentimentTrend) {
		return true
	}

	return false
}

// SetSentimentTrend gets a reference to the given interface{} and assigns it to the SentimentTrend field.
func (o *RiskAuditConversationScoresV2) SetSentimentTrend(v interface{}) {
	o.SentimentTrend = v
}

// GetPctTurnsWithViolation returns the PctTurnsWithViolation field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetPctTurnsWithViolation() float32 {
	if o == nil || IsNil(o.PctTurnsWithViolation) {
		var ret float32
		return ret
	}
	return *o.PctTurnsWithViolation
}

// GetPctTurnsWithViolationOk returns a tuple with the PctTurnsWithViolation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetPctTurnsWithViolationOk() (*float32, bool) {
	if o == nil || IsNil(o.PctTurnsWithViolation) {
		return nil, false
	}
	return o.PctTurnsWithViolation, true
}

// HasPctTurnsWithViolation returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasPctTurnsWithViolation() bool {
	if o != nil && !IsNil(o.PctTurnsWithViolation) {
		return true
	}

	return false
}

// SetPctTurnsWithViolation gets a reference to the given float32 and assigns it to the PctTurnsWithViolation field.
func (o *RiskAuditConversationScoresV2) SetPctTurnsWithViolation(v float32) {
	o.PctTurnsWithViolation = &v
}

// GetMostCriticalTurn returns the MostCriticalTurn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditConversationScoresV2) GetMostCriticalTurn() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MostCriticalTurn
}

// GetMostCriticalTurnOk returns a tuple with the MostCriticalTurn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditConversationScoresV2) GetMostCriticalTurnOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MostCriticalTurn) {
		return nil, false
	}
	return &o.MostCriticalTurn, true
}

// HasMostCriticalTurn returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasMostCriticalTurn() bool {
	if o != nil && !IsNil(o.MostCriticalTurn) {
		return true
	}

	return false
}

// SetMostCriticalTurn gets a reference to the given interface{} and assigns it to the MostCriticalTurn field.
func (o *RiskAuditConversationScoresV2) SetMostCriticalTurn(v interface{}) {
	o.MostCriticalTurn = v
}

// GetPositiveNegativeRatio returns the PositiveNegativeRatio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RiskAuditConversationScoresV2) GetPositiveNegativeRatio() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PositiveNegativeRatio
}

// GetPositiveNegativeRatioOk returns a tuple with the PositiveNegativeRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RiskAuditConversationScoresV2) GetPositiveNegativeRatioOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PositiveNegativeRatio) {
		return nil, false
	}
	return &o.PositiveNegativeRatio, true
}

// HasPositiveNegativeRatio returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasPositiveNegativeRatio() bool {
	if o != nil && !IsNil(o.PositiveNegativeRatio) {
		return true
	}

	return false
}

// SetPositiveNegativeRatio gets a reference to the given interface{} and assigns it to the PositiveNegativeRatio field.
func (o *RiskAuditConversationScoresV2) SetPositiveNegativeRatio(v interface{}) {
	o.PositiveNegativeRatio = v
}

// GetGlobalRiskSeverity returns the GlobalRiskSeverity field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverity() string {
	if o == nil || IsNil(o.GlobalRiskSeverity) {
		var ret string
		return ret
	}
	return *o.GlobalRiskSeverity
}

// GetGlobalRiskSeverityOk returns a tuple with the GlobalRiskSeverity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalRiskSeverity) {
		return nil, false
	}
	return o.GlobalRiskSeverity, true
}

// HasGlobalRiskSeverity returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasGlobalRiskSeverity() bool {
	if o != nil && !IsNil(o.GlobalRiskSeverity) {
		return true
	}

	return false
}

// SetGlobalRiskSeverity gets a reference to the given string and assigns it to the GlobalRiskSeverity field.
func (o *RiskAuditConversationScoresV2) SetGlobalRiskSeverity(v string) {
	o.GlobalRiskSeverity = &v
}

// GetGlobalRiskSeverityLabel returns the GlobalRiskSeverityLabel field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverityLabel() string {
	if o == nil || IsNil(o.GlobalRiskSeverityLabel) {
		var ret string
		return ret
	}
	return *o.GlobalRiskSeverityLabel
}

// GetGlobalRiskSeverityLabelOk returns a tuple with the GlobalRiskSeverityLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverityLabelOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalRiskSeverityLabel) {
		return nil, false
	}
	return o.GlobalRiskSeverityLabel, true
}

// HasGlobalRiskSeverityLabel returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasGlobalRiskSeverityLabel() bool {
	if o != nil && !IsNil(o.GlobalRiskSeverityLabel) {
		return true
	}

	return false
}

// SetGlobalRiskSeverityLabel gets a reference to the given string and assigns it to the GlobalRiskSeverityLabel field.
func (o *RiskAuditConversationScoresV2) SetGlobalRiskSeverityLabel(v string) {
	o.GlobalRiskSeverityLabel = &v
}

// GetGlobalRiskSeverityColor returns the GlobalRiskSeverityColor field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverityColor() string {
	if o == nil || IsNil(o.GlobalRiskSeverityColor) {
		var ret string
		return ret
	}
	return *o.GlobalRiskSeverityColor
}

// GetGlobalRiskSeverityColorOk returns a tuple with the GlobalRiskSeverityColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetGlobalRiskSeverityColorOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalRiskSeverityColor) {
		return nil, false
	}
	return o.GlobalRiskSeverityColor, true
}

// HasGlobalRiskSeverityColor returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasGlobalRiskSeverityColor() bool {
	if o != nil && !IsNil(o.GlobalRiskSeverityColor) {
		return true
	}

	return false
}

// SetGlobalRiskSeverityColor gets a reference to the given string and assigns it to the GlobalRiskSeverityColor field.
func (o *RiskAuditConversationScoresV2) SetGlobalRiskSeverityColor(v string) {
	o.GlobalRiskSeverityColor = &v
}

// GetRiskLikelihoodAvg returns the RiskLikelihoodAvg field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetRiskLikelihoodAvg() float32 {
	if o == nil || IsNil(o.RiskLikelihoodAvg) {
		var ret float32
		return ret
	}
	return *o.RiskLikelihoodAvg
}

// GetRiskLikelihoodAvgOk returns a tuple with the RiskLikelihoodAvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetRiskLikelihoodAvgOk() (*float32, bool) {
	if o == nil || IsNil(o.RiskLikelihoodAvg) {
		return nil, false
	}
	return o.RiskLikelihoodAvg, true
}

// HasRiskLikelihoodAvg returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasRiskLikelihoodAvg() bool {
	if o != nil && !IsNil(o.RiskLikelihoodAvg) {
		return true
	}

	return false
}

// SetRiskLikelihoodAvg gets a reference to the given float32 and assigns it to the RiskLikelihoodAvg field.
func (o *RiskAuditConversationScoresV2) SetRiskLikelihoodAvg(v float32) {
	o.RiskLikelihoodAvg = &v
}

// GetRiskImpactAvg returns the RiskImpactAvg field value if set, zero value otherwise.
func (o *RiskAuditConversationScoresV2) GetRiskImpactAvg() float32 {
	if o == nil || IsNil(o.RiskImpactAvg) {
		var ret float32
		return ret
	}
	return *o.RiskImpactAvg
}

// GetRiskImpactAvgOk returns a tuple with the RiskImpactAvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditConversationScoresV2) GetRiskImpactAvgOk() (*float32, bool) {
	if o == nil || IsNil(o.RiskImpactAvg) {
		return nil, false
	}
	return o.RiskImpactAvg, true
}

// HasRiskImpactAvg returns a boolean if a field has been set.
func (o *RiskAuditConversationScoresV2) HasRiskImpactAvg() bool {
	if o != nil && !IsNil(o.RiskImpactAvg) {
		return true
	}

	return false
}

// SetRiskImpactAvg gets a reference to the given float32 and assigns it to the RiskImpactAvg field.
func (o *RiskAuditConversationScoresV2) SetRiskImpactAvg(v float32) {
	o.RiskImpactAvg = &v
}

func (o RiskAuditConversationScoresV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditConversationScoresV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsolidatedScore) {
		toSerialize["consolidated_score"] = o.ConsolidatedScore
	}
	if !IsNil(o.ViolationDensityPerMin) {
		toSerialize["violation_density_per_min"] = o.ViolationDensityPerMin
	}
	if o.SentimentTrend != nil {
		toSerialize["sentiment_trend"] = o.SentimentTrend
	}
	if !IsNil(o.PctTurnsWithViolation) {
		toSerialize["pct_turns_with_violation"] = o.PctTurnsWithViolation
	}
	if o.MostCriticalTurn != nil {
		toSerialize["most_critical_turn"] = o.MostCriticalTurn
	}
	if o.PositiveNegativeRatio != nil {
		toSerialize["positive_negative_ratio"] = o.PositiveNegativeRatio
	}
	if !IsNil(o.GlobalRiskSeverity) {
		toSerialize["global_risk_severity"] = o.GlobalRiskSeverity
	}
	if !IsNil(o.GlobalRiskSeverityLabel) {
		toSerialize["global_risk_severity_label"] = o.GlobalRiskSeverityLabel
	}
	if !IsNil(o.GlobalRiskSeverityColor) {
		toSerialize["global_risk_severity_color"] = o.GlobalRiskSeverityColor
	}
	if !IsNil(o.RiskLikelihoodAvg) {
		toSerialize["risk_likelihood_avg"] = o.RiskLikelihoodAvg
	}
	if !IsNil(o.RiskImpactAvg) {
		toSerialize["risk_impact_avg"] = o.RiskImpactAvg
	}
	return toSerialize, nil
}

type NullableRiskAuditConversationScoresV2 struct {
	value *RiskAuditConversationScoresV2
	isSet bool
}

func (v NullableRiskAuditConversationScoresV2) Get() *RiskAuditConversationScoresV2 {
	return v.value
}

func (v *NullableRiskAuditConversationScoresV2) Set(val *RiskAuditConversationScoresV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditConversationScoresV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditConversationScoresV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditConversationScoresV2(val *RiskAuditConversationScoresV2) *NullableRiskAuditConversationScoresV2 {
	return &NullableRiskAuditConversationScoresV2{value: val, isSet: true}
}

func (v NullableRiskAuditConversationScoresV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditConversationScoresV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


