/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiagnosticParticipant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticParticipant{}

// DiagnosticParticipant struct for DiagnosticParticipant
type DiagnosticParticipant struct {
	// Exact speaker label from the dialog (e.g. 'Speaker 1')
	Interlocutor string `json:"interlocutor"`
	// Participant name (optional)
	Name *string `json:"name,omitempty"`
	// agent | client | bot
	Role string `json:"role"`
}

type _DiagnosticParticipant DiagnosticParticipant

// NewDiagnosticParticipant instantiates a new DiagnosticParticipant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticParticipant(interlocutor string, role string) *DiagnosticParticipant {
	this := DiagnosticParticipant{}
	this.Interlocutor = interlocutor
	this.Role = role
	return &this
}

// NewDiagnosticParticipantWithDefaults instantiates a new DiagnosticParticipant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticParticipantWithDefaults() *DiagnosticParticipant {
	this := DiagnosticParticipant{}
	return &this
}

// GetInterlocutor returns the Interlocutor field value
func (o *DiagnosticParticipant) GetInterlocutor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interlocutor
}

// GetInterlocutorOk returns a tuple with the Interlocutor field value
// and a boolean to check if the value has been set.
func (o *DiagnosticParticipant) GetInterlocutorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interlocutor, true
}

// SetInterlocutor sets field value
func (o *DiagnosticParticipant) SetInterlocutor(v string) {
	o.Interlocutor = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DiagnosticParticipant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticParticipant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DiagnosticParticipant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DiagnosticParticipant) SetName(v string) {
	o.Name = &v
}

// GetRole returns the Role field value
func (o *DiagnosticParticipant) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *DiagnosticParticipant) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *DiagnosticParticipant) SetRole(v string) {
	o.Role = v
}

func (o DiagnosticParticipant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticParticipant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["interlocutor"] = o.Interlocutor
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *DiagnosticParticipant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interlocutor",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiagnosticParticipant := _DiagnosticParticipant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiagnosticParticipant)

	if err != nil {
		return err
	}

	*o = DiagnosticParticipant(varDiagnosticParticipant)

	return err
}

type NullableDiagnosticParticipant struct {
	value *DiagnosticParticipant
	isSet bool
}

func (v NullableDiagnosticParticipant) Get() *DiagnosticParticipant {
	return v.value
}

func (v *NullableDiagnosticParticipant) Set(val *DiagnosticParticipant) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticParticipant) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticParticipant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticParticipant(val *DiagnosticParticipant) *NullableDiagnosticParticipant {
	return &NullableDiagnosticParticipant{value: val, isSet: true}
}

func (v NullableDiagnosticParticipant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticParticipant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


