/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailAlertMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAlertMessageResponse{}

// EmailAlertMessageResponse struct for EmailAlertMessageResponse
type EmailAlertMessageResponse struct {
	// Operation result message
	Message string `json:"message"`
}

type _EmailAlertMessageResponse EmailAlertMessageResponse

// NewEmailAlertMessageResponse instantiates a new EmailAlertMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAlertMessageResponse(message string) *EmailAlertMessageResponse {
	this := EmailAlertMessageResponse{}
	this.Message = message
	return &this
}

// NewEmailAlertMessageResponseWithDefaults instantiates a new EmailAlertMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailAlertMessageResponseWithDefaults() *EmailAlertMessageResponse {
	this := EmailAlertMessageResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *EmailAlertMessageResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *EmailAlertMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *EmailAlertMessageResponse) SetMessage(v string) {
	o.Message = v
}

func (o EmailAlertMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAlertMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *EmailAlertMessageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailAlertMessageResponse := _EmailAlertMessageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailAlertMessageResponse)

	if err != nil {
		return err
	}

	*o = EmailAlertMessageResponse(varEmailAlertMessageResponse)

	return err
}

type NullableEmailAlertMessageResponse struct {
	value *EmailAlertMessageResponse
	isSet bool
}

func (v NullableEmailAlertMessageResponse) Get() *EmailAlertMessageResponse {
	return v.value
}

func (v *NullableEmailAlertMessageResponse) Set(val *EmailAlertMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAlertMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAlertMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAlertMessageResponse(val *EmailAlertMessageResponse) *NullableEmailAlertMessageResponse {
	return &NullableEmailAlertMessageResponse{value: val, isSet: true}
}

func (v NullableEmailAlertMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAlertMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


