/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiagnosticUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticUsage{}

// DiagnosticUsage struct for DiagnosticUsage
type DiagnosticUsage struct {
	// Total characters analyzed
	Characters int32 `json:"characters"`
	// Credits consumed: max(ceil(chars/500)*3, 3) * 5
	CreditsConsumed int32 `json:"credits_consumed"`
	// Total processing time in milliseconds
	ProcessingMs int32 `json:"processing_ms"`
}

type _DiagnosticUsage DiagnosticUsage

// NewDiagnosticUsage instantiates a new DiagnosticUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticUsage(characters int32, creditsConsumed int32, processingMs int32) *DiagnosticUsage {
	this := DiagnosticUsage{}
	this.Characters = characters
	this.CreditsConsumed = creditsConsumed
	this.ProcessingMs = processingMs
	return &this
}

// NewDiagnosticUsageWithDefaults instantiates a new DiagnosticUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticUsageWithDefaults() *DiagnosticUsage {
	this := DiagnosticUsage{}
	return &this
}

// GetCharacters returns the Characters field value
func (o *DiagnosticUsage) GetCharacters() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Characters
}

// GetCharactersOk returns a tuple with the Characters field value
// and a boolean to check if the value has been set.
func (o *DiagnosticUsage) GetCharactersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Characters, true
}

// SetCharacters sets field value
func (o *DiagnosticUsage) SetCharacters(v int32) {
	o.Characters = v
}

// GetCreditsConsumed returns the CreditsConsumed field value
func (o *DiagnosticUsage) GetCreditsConsumed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsConsumed
}

// GetCreditsConsumedOk returns a tuple with the CreditsConsumed field value
// and a boolean to check if the value has been set.
func (o *DiagnosticUsage) GetCreditsConsumedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsConsumed, true
}

// SetCreditsConsumed sets field value
func (o *DiagnosticUsage) SetCreditsConsumed(v int32) {
	o.CreditsConsumed = v
}

// GetProcessingMs returns the ProcessingMs field value
func (o *DiagnosticUsage) GetProcessingMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessingMs
}

// GetProcessingMsOk returns a tuple with the ProcessingMs field value
// and a boolean to check if the value has been set.
func (o *DiagnosticUsage) GetProcessingMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingMs, true
}

// SetProcessingMs sets field value
func (o *DiagnosticUsage) SetProcessingMs(v int32) {
	o.ProcessingMs = v
}

func (o DiagnosticUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["characters"] = o.Characters
	toSerialize["credits_consumed"] = o.CreditsConsumed
	toSerialize["processing_ms"] = o.ProcessingMs
	return toSerialize, nil
}

func (o *DiagnosticUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"characters",
		"credits_consumed",
		"processing_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiagnosticUsage := _DiagnosticUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiagnosticUsage)

	if err != nil {
		return err
	}

	*o = DiagnosticUsage(varDiagnosticUsage)

	return err
}

type NullableDiagnosticUsage struct {
	value *DiagnosticUsage
	isSet bool
}

func (v NullableDiagnosticUsage) Get() *DiagnosticUsage {
	return v.value
}

func (v *NullableDiagnosticUsage) Set(val *DiagnosticUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticUsage(val *DiagnosticUsage) *NullableDiagnosticUsage {
	return &NullableDiagnosticUsage{value: val, isSet: true}
}

func (v NullableDiagnosticUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


