/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditAnalysisV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditAnalysisV2{}

// RiskAuditAnalysisV2 struct for RiskAuditAnalysisV2
type RiskAuditAnalysisV2 struct {
	// Global metrics
	GlobalMetrics map[string]interface{} `json:"global_metrics,omitempty"`
	// Final analysis
	FinalAnalysis map[string]interface{} `json:"final_analysis,omitempty"`
	// Frameworks (COPC/ISO/Kirkpatrick/CES)
	Frameworks map[string]interface{} `json:"frameworks,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditAnalysisV2 RiskAuditAnalysisV2

// NewRiskAuditAnalysisV2 instantiates a new RiskAuditAnalysisV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditAnalysisV2() *RiskAuditAnalysisV2 {
	this := RiskAuditAnalysisV2{}
	return &this
}

// NewRiskAuditAnalysisV2WithDefaults instantiates a new RiskAuditAnalysisV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditAnalysisV2WithDefaults() *RiskAuditAnalysisV2 {
	this := RiskAuditAnalysisV2{}
	return &this
}

// GetGlobalMetrics returns the GlobalMetrics field value if set, zero value otherwise.
func (o *RiskAuditAnalysisV2) GetGlobalMetrics() map[string]interface{} {
	if o == nil || IsNil(o.GlobalMetrics) {
		var ret map[string]interface{}
		return ret
	}
	return o.GlobalMetrics
}

// GetGlobalMetricsOk returns a tuple with the GlobalMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAnalysisV2) GetGlobalMetricsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.GlobalMetrics) {
		return map[string]interface{}{}, false
	}
	return o.GlobalMetrics, true
}

// HasGlobalMetrics returns a boolean if a field has been set.
func (o *RiskAuditAnalysisV2) HasGlobalMetrics() bool {
	if o != nil && !IsNil(o.GlobalMetrics) {
		return true
	}

	return false
}

// SetGlobalMetrics gets a reference to the given map[string]interface{} and assigns it to the GlobalMetrics field.
func (o *RiskAuditAnalysisV2) SetGlobalMetrics(v map[string]interface{}) {
	o.GlobalMetrics = v
}

// GetFinalAnalysis returns the FinalAnalysis field value if set, zero value otherwise.
func (o *RiskAuditAnalysisV2) GetFinalAnalysis() map[string]interface{} {
	if o == nil || IsNil(o.FinalAnalysis) {
		var ret map[string]interface{}
		return ret
	}
	return o.FinalAnalysis
}

// GetFinalAnalysisOk returns a tuple with the FinalAnalysis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAnalysisV2) GetFinalAnalysisOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FinalAnalysis) {
		return map[string]interface{}{}, false
	}
	return o.FinalAnalysis, true
}

// HasFinalAnalysis returns a boolean if a field has been set.
func (o *RiskAuditAnalysisV2) HasFinalAnalysis() bool {
	if o != nil && !IsNil(o.FinalAnalysis) {
		return true
	}

	return false
}

// SetFinalAnalysis gets a reference to the given map[string]interface{} and assigns it to the FinalAnalysis field.
func (o *RiskAuditAnalysisV2) SetFinalAnalysis(v map[string]interface{}) {
	o.FinalAnalysis = v
}

// GetFrameworks returns the Frameworks field value if set, zero value otherwise.
func (o *RiskAuditAnalysisV2) GetFrameworks() map[string]interface{} {
	if o == nil || IsNil(o.Frameworks) {
		var ret map[string]interface{}
		return ret
	}
	return o.Frameworks
}

// GetFrameworksOk returns a tuple with the Frameworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAnalysisV2) GetFrameworksOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Frameworks) {
		return map[string]interface{}{}, false
	}
	return o.Frameworks, true
}

// HasFrameworks returns a boolean if a field has been set.
func (o *RiskAuditAnalysisV2) HasFrameworks() bool {
	if o != nil && !IsNil(o.Frameworks) {
		return true
	}

	return false
}

// SetFrameworks gets a reference to the given map[string]interface{} and assigns it to the Frameworks field.
func (o *RiskAuditAnalysisV2) SetFrameworks(v map[string]interface{}) {
	o.Frameworks = v
}

func (o RiskAuditAnalysisV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditAnalysisV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalMetrics) {
		toSerialize["global_metrics"] = o.GlobalMetrics
	}
	if !IsNil(o.FinalAnalysis) {
		toSerialize["final_analysis"] = o.FinalAnalysis
	}
	if !IsNil(o.Frameworks) {
		toSerialize["frameworks"] = o.Frameworks
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditAnalysisV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditAnalysisV2 := _RiskAuditAnalysisV2{}

	err = json.Unmarshal(data, &varRiskAuditAnalysisV2)

	if err != nil {
		return err
	}

	*o = RiskAuditAnalysisV2(varRiskAuditAnalysisV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "global_metrics")
		delete(additionalProperties, "final_analysis")
		delete(additionalProperties, "frameworks")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditAnalysisV2 struct {
	value *RiskAuditAnalysisV2
	isSet bool
}

func (v NullableRiskAuditAnalysisV2) Get() *RiskAuditAnalysisV2 {
	return v.value
}

func (v *NullableRiskAuditAnalysisV2) Set(val *RiskAuditAnalysisV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditAnalysisV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditAnalysisV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditAnalysisV2(val *RiskAuditAnalysisV2) *NullableRiskAuditAnalysisV2 {
	return &NullableRiskAuditAnalysisV2{value: val, isSet: true}
}

func (v NullableRiskAuditAnalysisV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditAnalysisV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


