/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the UpdateEmailAlertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEmailAlertRequest{}

// UpdateEmailAlertRequest struct for UpdateEmailAlertRequest
type UpdateEmailAlertRequest struct {
	Name *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Events []EmailEvent `json:"events,omitempty"`
	Active *bool `json:"active,omitempty"`
}

// NewUpdateEmailAlertRequest instantiates a new UpdateEmailAlertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEmailAlertRequest() *UpdateEmailAlertRequest {
	this := UpdateEmailAlertRequest{}
	return &this
}

// NewUpdateEmailAlertRequestWithDefaults instantiates a new UpdateEmailAlertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEmailAlertRequestWithDefaults() *UpdateEmailAlertRequest {
	this := UpdateEmailAlertRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEmailAlertRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailAlertRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEmailAlertRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEmailAlertRequest) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UpdateEmailAlertRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailAlertRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UpdateEmailAlertRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UpdateEmailAlertRequest) SetEmail(v string) {
	o.Email = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *UpdateEmailAlertRequest) GetEvents() []EmailEvent {
	if o == nil || IsNil(o.Events) {
		var ret []EmailEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailAlertRequest) GetEventsOk() ([]EmailEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *UpdateEmailAlertRequest) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []EmailEvent and assigns it to the Events field.
func (o *UpdateEmailAlertRequest) SetEvents(v []EmailEvent) {
	o.Events = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *UpdateEmailAlertRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailAlertRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *UpdateEmailAlertRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *UpdateEmailAlertRequest) SetActive(v bool) {
	o.Active = &v
}

func (o UpdateEmailAlertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEmailAlertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullableUpdateEmailAlertRequest struct {
	value *UpdateEmailAlertRequest
	isSet bool
}

func (v NullableUpdateEmailAlertRequest) Get() *UpdateEmailAlertRequest {
	return v.value
}

func (v *NullableUpdateEmailAlertRequest) Set(val *UpdateEmailAlertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEmailAlertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEmailAlertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEmailAlertRequest(val *UpdateEmailAlertRequest) *NullableUpdateEmailAlertRequest {
	return &NullableUpdateEmailAlertRequest{value: val, isSet: true}
}

func (v NullableUpdateEmailAlertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEmailAlertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


