/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEmailAlertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEmailAlertRequest{}

// CreateEmailAlertRequest struct for CreateEmailAlertRequest
type CreateEmailAlertRequest struct {
	// Nome identificador
	Name string `json:"name"`
	// Email destino
	Email string `json:"email"`
	// Eventos subscritos
	Events []EmailEvent `json:"events"`
}

type _CreateEmailAlertRequest CreateEmailAlertRequest

// NewCreateEmailAlertRequest instantiates a new CreateEmailAlertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEmailAlertRequest(name string, email string, events []EmailEvent) *CreateEmailAlertRequest {
	this := CreateEmailAlertRequest{}
	this.Name = name
	this.Email = email
	this.Events = events
	return &this
}

// NewCreateEmailAlertRequestWithDefaults instantiates a new CreateEmailAlertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEmailAlertRequestWithDefaults() *CreateEmailAlertRequest {
	this := CreateEmailAlertRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEmailAlertRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEmailAlertRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEmailAlertRequest) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CreateEmailAlertRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateEmailAlertRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateEmailAlertRequest) SetEmail(v string) {
	o.Email = v
}

// GetEvents returns the Events field value
func (o *CreateEmailAlertRequest) GetEvents() []EmailEvent {
	if o == nil {
		var ret []EmailEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *CreateEmailAlertRequest) GetEventsOk() ([]EmailEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *CreateEmailAlertRequest) SetEvents(v []EmailEvent) {
	o.Events = v
}

func (o CreateEmailAlertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEmailAlertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *CreateEmailAlertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEmailAlertRequest := _CreateEmailAlertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEmailAlertRequest)

	if err != nil {
		return err
	}

	*o = CreateEmailAlertRequest(varCreateEmailAlertRequest)

	return err
}

type NullableCreateEmailAlertRequest struct {
	value *CreateEmailAlertRequest
	isSet bool
}

func (v NullableCreateEmailAlertRequest) Get() *CreateEmailAlertRequest {
	return v.value
}

func (v *NullableCreateEmailAlertRequest) Set(val *CreateEmailAlertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEmailAlertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEmailAlertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEmailAlertRequest(val *CreateEmailAlertRequest) *NullableCreateEmailAlertRequest {
	return &NullableCreateEmailAlertRequest{value: val, isSet: true}
}

func (v NullableCreateEmailAlertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEmailAlertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


