/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TranscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptionResponse{}

// TranscriptionResponse struct for TranscriptionResponse
type TranscriptionResponse struct {
	// Unique transcription identifier. Prefix 'tr-' followed by UUID
	Id string `json:"id"`
	// Returned object type. Always 'transcription'
	Object string `json:"object"`
	// Model used for transcription. Ex: 'falaai-transcribe-1'
	Model string `json:"model"`
	// Original audio file name uploaded
	Filename string `json:"filename"`
	// Processing datetime in ISO 8601 UTC format
	ProcessedAt string `json:"processed_at"`
	// Usage and processing information
	Usage TranscriptionUsage `json:"usage"`
	// ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)
	Language string `json:"language"`
	// Language detection confidence level (0.0 to 1.0). Higher is more reliable
	LanguageConfidence *float32 `json:"language_confidence,omitempty"`
	// Total audio duration in seconds
	DurationSeconds float32 `json:"duration_seconds"`
	// Full transcription as plain text, including audio events in brackets
	Text string `json:"text"`
	// Turn-by-turn formatted transcript with speaker identification and start/end timestamps
	Dialog string `json:"dialog"`
	// List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration
	AudioEvents []AudioEvent `json:"audio_events"`
	// Unique audio event types found in transcription, alphabetically sorted
	EventTypes []string `json:"event_types"`
	// Total number of recognized words in transcription
	WordCount int32 `json:"word_count"`
	// Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais)
	Input AudioInputMeta `json:"input"`
	// Client-supplied ID echoed verbatim (if provided in request)
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
}

type _TranscriptionResponse TranscriptionResponse

// NewTranscriptionResponse instantiates a new TranscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptionResponse(id string, object string, model string, filename string, processedAt string, usage TranscriptionUsage, language string, durationSeconds float32, text string, dialog string, audioEvents []AudioEvent, eventTypes []string, wordCount int32, input AudioInputMeta) *TranscriptionResponse {
	this := TranscriptionResponse{}
	this.Id = id
	this.Object = object
	this.Model = model
	this.Filename = filename
	this.ProcessedAt = processedAt
	this.Usage = usage
	this.Language = language
	this.DurationSeconds = durationSeconds
	this.Text = text
	this.Dialog = dialog
	this.AudioEvents = audioEvents
	this.EventTypes = eventTypes
	this.WordCount = wordCount
	this.Input = input
	return &this
}

// NewTranscriptionResponseWithDefaults instantiates a new TranscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptionResponseWithDefaults() *TranscriptionResponse {
	this := TranscriptionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *TranscriptionResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TranscriptionResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *TranscriptionResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *TranscriptionResponse) SetObject(v string) {
	o.Object = v
}

// GetModel returns the Model field value
func (o *TranscriptionResponse) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *TranscriptionResponse) SetModel(v string) {
	o.Model = v
}

// GetFilename returns the Filename field value
func (o *TranscriptionResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *TranscriptionResponse) SetFilename(v string) {
	o.Filename = v
}

// GetProcessedAt returns the ProcessedAt field value
func (o *TranscriptionResponse) GetProcessedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessedAt
}

// GetProcessedAtOk returns a tuple with the ProcessedAt field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetProcessedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessedAt, true
}

// SetProcessedAt sets field value
func (o *TranscriptionResponse) SetProcessedAt(v string) {
	o.ProcessedAt = v
}

// GetUsage returns the Usage field value
func (o *TranscriptionResponse) GetUsage() TranscriptionUsage {
	if o == nil {
		var ret TranscriptionUsage
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetUsageOk() (*TranscriptionUsage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *TranscriptionResponse) SetUsage(v TranscriptionUsage) {
	o.Usage = v
}

// GetLanguage returns the Language field value
func (o *TranscriptionResponse) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *TranscriptionResponse) SetLanguage(v string) {
	o.Language = v
}

// GetLanguageConfidence returns the LanguageConfidence field value if set, zero value otherwise.
func (o *TranscriptionResponse) GetLanguageConfidence() float32 {
	if o == nil || IsNil(o.LanguageConfidence) {
		var ret float32
		return ret
	}
	return *o.LanguageConfidence
}

// GetLanguageConfidenceOk returns a tuple with the LanguageConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetLanguageConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.LanguageConfidence) {
		return nil, false
	}
	return o.LanguageConfidence, true
}

// HasLanguageConfidence returns a boolean if a field has been set.
func (o *TranscriptionResponse) HasLanguageConfidence() bool {
	if o != nil && !IsNil(o.LanguageConfidence) {
		return true
	}

	return false
}

// SetLanguageConfidence gets a reference to the given float32 and assigns it to the LanguageConfidence field.
func (o *TranscriptionResponse) SetLanguageConfidence(v float32) {
	o.LanguageConfidence = &v
}

// GetDurationSeconds returns the DurationSeconds field value
func (o *TranscriptionResponse) GetDurationSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DurationSeconds
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationSeconds, true
}

// SetDurationSeconds sets field value
func (o *TranscriptionResponse) SetDurationSeconds(v float32) {
	o.DurationSeconds = v
}

// GetText returns the Text field value
func (o *TranscriptionResponse) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *TranscriptionResponse) SetText(v string) {
	o.Text = v
}

// GetDialog returns the Dialog field value
func (o *TranscriptionResponse) GetDialog() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dialog
}

// GetDialogOk returns a tuple with the Dialog field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetDialogOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dialog, true
}

// SetDialog sets field value
func (o *TranscriptionResponse) SetDialog(v string) {
	o.Dialog = v
}

// GetAudioEvents returns the AudioEvents field value
func (o *TranscriptionResponse) GetAudioEvents() []AudioEvent {
	if o == nil {
		var ret []AudioEvent
		return ret
	}

	return o.AudioEvents
}

// GetAudioEventsOk returns a tuple with the AudioEvents field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetAudioEventsOk() ([]AudioEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioEvents, true
}

// SetAudioEvents sets field value
func (o *TranscriptionResponse) SetAudioEvents(v []AudioEvent) {
	o.AudioEvents = v
}

// GetEventTypes returns the EventTypes field value
func (o *TranscriptionResponse) GetEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypes, true
}

// SetEventTypes sets field value
func (o *TranscriptionResponse) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetWordCount returns the WordCount field value
func (o *TranscriptionResponse) GetWordCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WordCount
}

// GetWordCountOk returns a tuple with the WordCount field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetWordCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WordCount, true
}

// SetWordCount sets field value
func (o *TranscriptionResponse) SetWordCount(v int32) {
	o.WordCount = v
}

// GetInput returns the Input field value
func (o *TranscriptionResponse) GetInput() AudioInputMeta {
	if o == nil {
		var ret AudioInputMeta
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetInputOk() (*AudioInputMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *TranscriptionResponse) SetInput(v AudioInputMeta) {
	o.Input = v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *TranscriptionResponse) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscriptionResponse) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *TranscriptionResponse) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *TranscriptionResponse) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

func (o TranscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["model"] = o.Model
	toSerialize["filename"] = o.Filename
	toSerialize["processed_at"] = o.ProcessedAt
	toSerialize["usage"] = o.Usage
	toSerialize["language"] = o.Language
	if !IsNil(o.LanguageConfidence) {
		toSerialize["language_confidence"] = o.LanguageConfidence
	}
	toSerialize["duration_seconds"] = o.DurationSeconds
	toSerialize["text"] = o.Text
	toSerialize["dialog"] = o.Dialog
	toSerialize["audio_events"] = o.AudioEvents
	toSerialize["event_types"] = o.EventTypes
	toSerialize["word_count"] = o.WordCount
	toSerialize["input"] = o.Input
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	return toSerialize, nil
}

func (o *TranscriptionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"model",
		"filename",
		"processed_at",
		"usage",
		"language",
		"duration_seconds",
		"text",
		"dialog",
		"audio_events",
		"event_types",
		"word_count",
		"input",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscriptionResponse := _TranscriptionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTranscriptionResponse)

	if err != nil {
		return err
	}

	*o = TranscriptionResponse(varTranscriptionResponse)

	return err
}

type NullableTranscriptionResponse struct {
	value *TranscriptionResponse
	isSet bool
}

func (v NullableTranscriptionResponse) Get() *TranscriptionResponse {
	return v.value
}

func (v *NullableTranscriptionResponse) Set(val *TranscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptionResponse(val *TranscriptionResponse) *NullableTranscriptionResponse {
	return &NullableTranscriptionResponse{value: val, isSet: true}
}

func (v NullableTranscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


