/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWebhookRequest{}

// CreateWebhookRequest struct for CreateWebhookRequest
type CreateWebhookRequest struct {
	// Nome identificador do webhook
	Name string `json:"name"`
	// URL HTTPS que recebera POST com HMAC FalaAI-Signature
	Url string `json:"url"`
	// Eventos subscritos (10 alertas)
	Events []WebhookEvent `json:"events"`
	// Retry exponencial 5 tentativas quando true (false=1 tentativa)
	RetryEnabled *bool `json:"retry_enabled,omitempty"`
}

type _CreateWebhookRequest CreateWebhookRequest

// NewCreateWebhookRequest instantiates a new CreateWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWebhookRequest(name string, url string, events []WebhookEvent) *CreateWebhookRequest {
	this := CreateWebhookRequest{}
	this.Name = name
	this.Url = url
	this.Events = events
	var retryEnabled bool = false
	this.RetryEnabled = &retryEnabled
	return &this
}

// NewCreateWebhookRequestWithDefaults instantiates a new CreateWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWebhookRequestWithDefaults() *CreateWebhookRequest {
	this := CreateWebhookRequest{}
	var retryEnabled bool = false
	this.RetryEnabled = &retryEnabled
	return &this
}

// GetName returns the Name field value
func (o *CreateWebhookRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateWebhookRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateWebhookRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *CreateWebhookRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateWebhookRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateWebhookRequest) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *CreateWebhookRequest) GetEvents() []WebhookEvent {
	if o == nil {
		var ret []WebhookEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *CreateWebhookRequest) GetEventsOk() ([]WebhookEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *CreateWebhookRequest) SetEvents(v []WebhookEvent) {
	o.Events = v
}

// GetRetryEnabled returns the RetryEnabled field value if set, zero value otherwise.
func (o *CreateWebhookRequest) GetRetryEnabled() bool {
	if o == nil || IsNil(o.RetryEnabled) {
		var ret bool
		return ret
	}
	return *o.RetryEnabled
}

// GetRetryEnabledOk returns a tuple with the RetryEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWebhookRequest) GetRetryEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RetryEnabled) {
		return nil, false
	}
	return o.RetryEnabled, true
}

// HasRetryEnabled returns a boolean if a field has been set.
func (o *CreateWebhookRequest) HasRetryEnabled() bool {
	if o != nil && !IsNil(o.RetryEnabled) {
		return true
	}

	return false
}

// SetRetryEnabled gets a reference to the given bool and assigns it to the RetryEnabled field.
func (o *CreateWebhookRequest) SetRetryEnabled(v bool) {
	o.RetryEnabled = &v
}

func (o CreateWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	if !IsNil(o.RetryEnabled) {
		toSerialize["retry_enabled"] = o.RetryEnabled
	}
	return toSerialize, nil
}

func (o *CreateWebhookRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWebhookRequest := _CreateWebhookRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWebhookRequest)

	if err != nil {
		return err
	}

	*o = CreateWebhookRequest(varCreateWebhookRequest)

	return err
}

type NullableCreateWebhookRequest struct {
	value *CreateWebhookRequest
	isSet bool
}

func (v NullableCreateWebhookRequest) Get() *CreateWebhookRequest {
	return v.value
}

func (v *NullableCreateWebhookRequest) Set(val *CreateWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWebhookRequest(val *CreateWebhookRequest) *NullableCreateWebhookRequest {
	return &NullableCreateWebhookRequest{value: val, isSet: true}
}

func (v NullableCreateWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


