/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageByKeyItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageByKeyItem{}

// UsageByKeyItem struct for UsageByKeyItem
type UsageByKeyItem struct {
	// API key id
	KeyId string `json:"key_id"`
	// API key name
	KeyName string `json:"key_name"`
	// Total credits consumed by the key
	TotalCredits int32 `json:"total_credits"`
	// Number of requests
	RequestCount int32 `json:"request_count"`
	// ISO 8601 of last use (null if never)
	LastUsed *string `json:"last_used,omitempty"`
}

type _UsageByKeyItem UsageByKeyItem

// NewUsageByKeyItem instantiates a new UsageByKeyItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageByKeyItem(keyId string, keyName string, totalCredits int32, requestCount int32) *UsageByKeyItem {
	this := UsageByKeyItem{}
	this.KeyId = keyId
	this.KeyName = keyName
	this.TotalCredits = totalCredits
	this.RequestCount = requestCount
	return &this
}

// NewUsageByKeyItemWithDefaults instantiates a new UsageByKeyItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageByKeyItemWithDefaults() *UsageByKeyItem {
	this := UsageByKeyItem{}
	return &this
}

// GetKeyId returns the KeyId field value
func (o *UsageByKeyItem) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *UsageByKeyItem) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *UsageByKeyItem) SetKeyId(v string) {
	o.KeyId = v
}

// GetKeyName returns the KeyName field value
func (o *UsageByKeyItem) GetKeyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyName
}

// GetKeyNameOk returns a tuple with the KeyName field value
// and a boolean to check if the value has been set.
func (o *UsageByKeyItem) GetKeyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyName, true
}

// SetKeyName sets field value
func (o *UsageByKeyItem) SetKeyName(v string) {
	o.KeyName = v
}

// GetTotalCredits returns the TotalCredits field value
func (o *UsageByKeyItem) GetTotalCredits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCredits
}

// GetTotalCreditsOk returns a tuple with the TotalCredits field value
// and a boolean to check if the value has been set.
func (o *UsageByKeyItem) GetTotalCreditsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCredits, true
}

// SetTotalCredits sets field value
func (o *UsageByKeyItem) SetTotalCredits(v int32) {
	o.TotalCredits = v
}

// GetRequestCount returns the RequestCount field value
func (o *UsageByKeyItem) GetRequestCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RequestCount
}

// GetRequestCountOk returns a tuple with the RequestCount field value
// and a boolean to check if the value has been set.
func (o *UsageByKeyItem) GetRequestCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestCount, true
}

// SetRequestCount sets field value
func (o *UsageByKeyItem) SetRequestCount(v int32) {
	o.RequestCount = v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise.
func (o *UsageByKeyItem) GetLastUsed() string {
	if o == nil || IsNil(o.LastUsed) {
		var ret string
		return ret
	}
	return *o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageByKeyItem) GetLastUsedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsed) {
		return nil, false
	}
	return o.LastUsed, true
}

// HasLastUsed returns a boolean if a field has been set.
func (o *UsageByKeyItem) HasLastUsed() bool {
	if o != nil && !IsNil(o.LastUsed) {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given string and assigns it to the LastUsed field.
func (o *UsageByKeyItem) SetLastUsed(v string) {
	o.LastUsed = &v
}

func (o UsageByKeyItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageByKeyItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_id"] = o.KeyId
	toSerialize["key_name"] = o.KeyName
	toSerialize["total_credits"] = o.TotalCredits
	toSerialize["request_count"] = o.RequestCount
	if !IsNil(o.LastUsed) {
		toSerialize["last_used"] = o.LastUsed
	}
	return toSerialize, nil
}

func (o *UsageByKeyItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_id",
		"key_name",
		"total_credits",
		"request_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageByKeyItem := _UsageByKeyItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageByKeyItem)

	if err != nil {
		return err
	}

	*o = UsageByKeyItem(varUsageByKeyItem)

	return err
}

type NullableUsageByKeyItem struct {
	value *UsageByKeyItem
	isSet bool
}

func (v NullableUsageByKeyItem) Get() *UsageByKeyItem {
	return v.value
}

func (v *NullableUsageByKeyItem) Set(val *UsageByKeyItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageByKeyItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageByKeyItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageByKeyItem(val *UsageByKeyItem) *NullableUsageByKeyItem {
	return &NullableUsageByKeyItem{value: val, isSet: true}
}

func (v NullableUsageByKeyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageByKeyItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


