/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"fmt"
)

// checks if the RiskAuditV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditV2{}

// RiskAuditV2 Response V2 (build_public_response_v2) — blocos logicos EN-US. Fonte: response_builder.py.
type RiskAuditV2 struct {
	// Identification + usage
	Meta RiskAuditMetaV2 `json:"meta"`
	// Participants/roles/direction
	Participants RiskAuditParticipantsV2 `json:"participants"`
	// Verdict + level + applied actions
	Verdict RiskAuditVerdictV2 `json:"verdict"`
	// Consolidated + per-participant scores
	Scores RiskAuditScoresV2 `json:"scores"`
	// violations/positives/client alerts
	Detections RiskAuditDetectionsV2 `json:"detections"`
	// global_metrics + final_analysis + frameworks
	Analysis RiskAuditAnalysisV2 `json:"analysis"`
	// turns_sentiment + audio_events + groups
	Timeline RiskAuditTimelineV2 `json:"timeline"`
	// MAC audio event semantics
	AudioEventModel RiskAuditAudioEventModelV2 `json:"audio_event_model"`
	// Per-category summary (keyed by category)
	CategoriesSummary map[string]interface{} `json:"categories_summary"`
	// Suggested terms for bank
	Indexer RiskAuditIndexerV2 `json:"indexer"`
	// Executive summary counts
	Summary RiskAuditSummaryV2 `json:"summary"`
	// Used actions i18n catalog (keyed by action)
	ActionsI18n map[string]interface{} `json:"actions_i18n"`
	// Risk origin + validator changes
	AuditDecisions RiskAuditAuditDecisionsV2 `json:"audit_decisions"`
	// Score composition explanation
	ScoringExplanation RiskAuditScoringExplanationV2 `json:"scoring_explanation"`
	// HTML report (base64 gzip)
	HtmlReport string `json:"html_report"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditV2 RiskAuditV2

// NewRiskAuditV2 instantiates a new RiskAuditV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditV2(meta RiskAuditMetaV2, participants RiskAuditParticipantsV2, verdict RiskAuditVerdictV2, scores RiskAuditScoresV2, detections RiskAuditDetectionsV2, analysis RiskAuditAnalysisV2, timeline RiskAuditTimelineV2, audioEventModel RiskAuditAudioEventModelV2, categoriesSummary map[string]interface{}, indexer RiskAuditIndexerV2, summary RiskAuditSummaryV2, actionsI18n map[string]interface{}, auditDecisions RiskAuditAuditDecisionsV2, scoringExplanation RiskAuditScoringExplanationV2, htmlReport string) *RiskAuditV2 {
	this := RiskAuditV2{}
	this.Meta = meta
	this.Participants = participants
	this.Verdict = verdict
	this.Scores = scores
	this.Detections = detections
	this.Analysis = analysis
	this.Timeline = timeline
	this.AudioEventModel = audioEventModel
	this.CategoriesSummary = categoriesSummary
	this.Indexer = indexer
	this.Summary = summary
	this.ActionsI18n = actionsI18n
	this.AuditDecisions = auditDecisions
	this.ScoringExplanation = scoringExplanation
	this.HtmlReport = htmlReport
	return &this
}

// NewRiskAuditV2WithDefaults instantiates a new RiskAuditV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditV2WithDefaults() *RiskAuditV2 {
	this := RiskAuditV2{}
	return &this
}

// GetMeta returns the Meta field value
func (o *RiskAuditV2) GetMeta() RiskAuditMetaV2 {
	if o == nil {
		var ret RiskAuditMetaV2
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetMetaOk() (*RiskAuditMetaV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *RiskAuditV2) SetMeta(v RiskAuditMetaV2) {
	o.Meta = v
}

// GetParticipants returns the Participants field value
func (o *RiskAuditV2) GetParticipants() RiskAuditParticipantsV2 {
	if o == nil {
		var ret RiskAuditParticipantsV2
		return ret
	}

	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetParticipantsOk() (*RiskAuditParticipantsV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Participants, true
}

// SetParticipants sets field value
func (o *RiskAuditV2) SetParticipants(v RiskAuditParticipantsV2) {
	o.Participants = v
}

// GetVerdict returns the Verdict field value
func (o *RiskAuditV2) GetVerdict() RiskAuditVerdictV2 {
	if o == nil {
		var ret RiskAuditVerdictV2
		return ret
	}

	return o.Verdict
}

// GetVerdictOk returns a tuple with the Verdict field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetVerdictOk() (*RiskAuditVerdictV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verdict, true
}

// SetVerdict sets field value
func (o *RiskAuditV2) SetVerdict(v RiskAuditVerdictV2) {
	o.Verdict = v
}

// GetScores returns the Scores field value
func (o *RiskAuditV2) GetScores() RiskAuditScoresV2 {
	if o == nil {
		var ret RiskAuditScoresV2
		return ret
	}

	return o.Scores
}

// GetScoresOk returns a tuple with the Scores field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetScoresOk() (*RiskAuditScoresV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scores, true
}

// SetScores sets field value
func (o *RiskAuditV2) SetScores(v RiskAuditScoresV2) {
	o.Scores = v
}

// GetDetections returns the Detections field value
func (o *RiskAuditV2) GetDetections() RiskAuditDetectionsV2 {
	if o == nil {
		var ret RiskAuditDetectionsV2
		return ret
	}

	return o.Detections
}

// GetDetectionsOk returns a tuple with the Detections field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetDetectionsOk() (*RiskAuditDetectionsV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detections, true
}

// SetDetections sets field value
func (o *RiskAuditV2) SetDetections(v RiskAuditDetectionsV2) {
	o.Detections = v
}

// GetAnalysis returns the Analysis field value
func (o *RiskAuditV2) GetAnalysis() RiskAuditAnalysisV2 {
	if o == nil {
		var ret RiskAuditAnalysisV2
		return ret
	}

	return o.Analysis
}

// GetAnalysisOk returns a tuple with the Analysis field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetAnalysisOk() (*RiskAuditAnalysisV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Analysis, true
}

// SetAnalysis sets field value
func (o *RiskAuditV2) SetAnalysis(v RiskAuditAnalysisV2) {
	o.Analysis = v
}

// GetTimeline returns the Timeline field value
func (o *RiskAuditV2) GetTimeline() RiskAuditTimelineV2 {
	if o == nil {
		var ret RiskAuditTimelineV2
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetTimelineOk() (*RiskAuditTimelineV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeline, true
}

// SetTimeline sets field value
func (o *RiskAuditV2) SetTimeline(v RiskAuditTimelineV2) {
	o.Timeline = v
}

// GetAudioEventModel returns the AudioEventModel field value
func (o *RiskAuditV2) GetAudioEventModel() RiskAuditAudioEventModelV2 {
	if o == nil {
		var ret RiskAuditAudioEventModelV2
		return ret
	}

	return o.AudioEventModel
}

// GetAudioEventModelOk returns a tuple with the AudioEventModel field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetAudioEventModelOk() (*RiskAuditAudioEventModelV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioEventModel, true
}

// SetAudioEventModel sets field value
func (o *RiskAuditV2) SetAudioEventModel(v RiskAuditAudioEventModelV2) {
	o.AudioEventModel = v
}

// GetCategoriesSummary returns the CategoriesSummary field value
func (o *RiskAuditV2) GetCategoriesSummary() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.CategoriesSummary
}

// GetCategoriesSummaryOk returns a tuple with the CategoriesSummary field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetCategoriesSummaryOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.CategoriesSummary, true
}

// SetCategoriesSummary sets field value
func (o *RiskAuditV2) SetCategoriesSummary(v map[string]interface{}) {
	o.CategoriesSummary = v
}

// GetIndexer returns the Indexer field value
func (o *RiskAuditV2) GetIndexer() RiskAuditIndexerV2 {
	if o == nil {
		var ret RiskAuditIndexerV2
		return ret
	}

	return o.Indexer
}

// GetIndexerOk returns a tuple with the Indexer field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetIndexerOk() (*RiskAuditIndexerV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Indexer, true
}

// SetIndexer sets field value
func (o *RiskAuditV2) SetIndexer(v RiskAuditIndexerV2) {
	o.Indexer = v
}

// GetSummary returns the Summary field value
func (o *RiskAuditV2) GetSummary() RiskAuditSummaryV2 {
	if o == nil {
		var ret RiskAuditSummaryV2
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetSummaryOk() (*RiskAuditSummaryV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *RiskAuditV2) SetSummary(v RiskAuditSummaryV2) {
	o.Summary = v
}

// GetActionsI18n returns the ActionsI18n field value
func (o *RiskAuditV2) GetActionsI18n() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ActionsI18n
}

// GetActionsI18nOk returns a tuple with the ActionsI18n field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetActionsI18nOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ActionsI18n, true
}

// SetActionsI18n sets field value
func (o *RiskAuditV2) SetActionsI18n(v map[string]interface{}) {
	o.ActionsI18n = v
}

// GetAuditDecisions returns the AuditDecisions field value
func (o *RiskAuditV2) GetAuditDecisions() RiskAuditAuditDecisionsV2 {
	if o == nil {
		var ret RiskAuditAuditDecisionsV2
		return ret
	}

	return o.AuditDecisions
}

// GetAuditDecisionsOk returns a tuple with the AuditDecisions field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetAuditDecisionsOk() (*RiskAuditAuditDecisionsV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditDecisions, true
}

// SetAuditDecisions sets field value
func (o *RiskAuditV2) SetAuditDecisions(v RiskAuditAuditDecisionsV2) {
	o.AuditDecisions = v
}

// GetScoringExplanation returns the ScoringExplanation field value
func (o *RiskAuditV2) GetScoringExplanation() RiskAuditScoringExplanationV2 {
	if o == nil {
		var ret RiskAuditScoringExplanationV2
		return ret
	}

	return o.ScoringExplanation
}

// GetScoringExplanationOk returns a tuple with the ScoringExplanation field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetScoringExplanationOk() (*RiskAuditScoringExplanationV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoringExplanation, true
}

// SetScoringExplanation sets field value
func (o *RiskAuditV2) SetScoringExplanation(v RiskAuditScoringExplanationV2) {
	o.ScoringExplanation = v
}

// GetHtmlReport returns the HtmlReport field value
func (o *RiskAuditV2) GetHtmlReport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HtmlReport
}

// GetHtmlReportOk returns a tuple with the HtmlReport field value
// and a boolean to check if the value has been set.
func (o *RiskAuditV2) GetHtmlReportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HtmlReport, true
}

// SetHtmlReport sets field value
func (o *RiskAuditV2) SetHtmlReport(v string) {
	o.HtmlReport = v
}

func (o RiskAuditV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["participants"] = o.Participants
	toSerialize["verdict"] = o.Verdict
	toSerialize["scores"] = o.Scores
	toSerialize["detections"] = o.Detections
	toSerialize["analysis"] = o.Analysis
	toSerialize["timeline"] = o.Timeline
	toSerialize["audio_event_model"] = o.AudioEventModel
	toSerialize["categories_summary"] = o.CategoriesSummary
	toSerialize["indexer"] = o.Indexer
	toSerialize["summary"] = o.Summary
	toSerialize["actions_i18n"] = o.ActionsI18n
	toSerialize["audit_decisions"] = o.AuditDecisions
	toSerialize["scoring_explanation"] = o.ScoringExplanation
	toSerialize["html_report"] = o.HtmlReport

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"participants",
		"verdict",
		"scores",
		"detections",
		"analysis",
		"timeline",
		"audio_event_model",
		"categories_summary",
		"indexer",
		"summary",
		"actions_i18n",
		"audit_decisions",
		"scoring_explanation",
		"html_report",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditV2 := _RiskAuditV2{}

	err = json.Unmarshal(data, &varRiskAuditV2)

	if err != nil {
		return err
	}

	*o = RiskAuditV2(varRiskAuditV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "meta")
		delete(additionalProperties, "participants")
		delete(additionalProperties, "verdict")
		delete(additionalProperties, "scores")
		delete(additionalProperties, "detections")
		delete(additionalProperties, "analysis")
		delete(additionalProperties, "timeline")
		delete(additionalProperties, "audio_event_model")
		delete(additionalProperties, "categories_summary")
		delete(additionalProperties, "indexer")
		delete(additionalProperties, "summary")
		delete(additionalProperties, "actions_i18n")
		delete(additionalProperties, "audit_decisions")
		delete(additionalProperties, "scoring_explanation")
		delete(additionalProperties, "html_report")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditV2 struct {
	value *RiskAuditV2
	isSet bool
}

func (v NullableRiskAuditV2) Get() *RiskAuditV2 {
	return v.value
}

func (v *NullableRiskAuditV2) Set(val *RiskAuditV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditV2(val *RiskAuditV2) *NullableRiskAuditV2 {
	return &NullableRiskAuditV2{value: val, isSet: true}
}

func (v NullableRiskAuditV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


