/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RiskAuditUsageV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditUsageV2{}

// RiskAuditUsageV2 struct for RiskAuditUsageV2
type RiskAuditUsageV2 struct {
	// Characters analyzed
	Characters int32 `json:"characters"`
	// Credits consumed
	CreditsConsumed int32 `json:"credits_consumed"`
	// Processing time (ms)
	ProcessingMs int32 `json:"processing_ms"`
}

type _RiskAuditUsageV2 RiskAuditUsageV2

// NewRiskAuditUsageV2 instantiates a new RiskAuditUsageV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditUsageV2(characters int32, creditsConsumed int32, processingMs int32) *RiskAuditUsageV2 {
	this := RiskAuditUsageV2{}
	this.Characters = characters
	this.CreditsConsumed = creditsConsumed
	this.ProcessingMs = processingMs
	return &this
}

// NewRiskAuditUsageV2WithDefaults instantiates a new RiskAuditUsageV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditUsageV2WithDefaults() *RiskAuditUsageV2 {
	this := RiskAuditUsageV2{}
	return &this
}

// GetCharacters returns the Characters field value
func (o *RiskAuditUsageV2) GetCharacters() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Characters
}

// GetCharactersOk returns a tuple with the Characters field value
// and a boolean to check if the value has been set.
func (o *RiskAuditUsageV2) GetCharactersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Characters, true
}

// SetCharacters sets field value
func (o *RiskAuditUsageV2) SetCharacters(v int32) {
	o.Characters = v
}

// GetCreditsConsumed returns the CreditsConsumed field value
func (o *RiskAuditUsageV2) GetCreditsConsumed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsConsumed
}

// GetCreditsConsumedOk returns a tuple with the CreditsConsumed field value
// and a boolean to check if the value has been set.
func (o *RiskAuditUsageV2) GetCreditsConsumedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsConsumed, true
}

// SetCreditsConsumed sets field value
func (o *RiskAuditUsageV2) SetCreditsConsumed(v int32) {
	o.CreditsConsumed = v
}

// GetProcessingMs returns the ProcessingMs field value
func (o *RiskAuditUsageV2) GetProcessingMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessingMs
}

// GetProcessingMsOk returns a tuple with the ProcessingMs field value
// and a boolean to check if the value has been set.
func (o *RiskAuditUsageV2) GetProcessingMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingMs, true
}

// SetProcessingMs sets field value
func (o *RiskAuditUsageV2) SetProcessingMs(v int32) {
	o.ProcessingMs = v
}

func (o RiskAuditUsageV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditUsageV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["characters"] = o.Characters
	toSerialize["credits_consumed"] = o.CreditsConsumed
	toSerialize["processing_ms"] = o.ProcessingMs
	return toSerialize, nil
}

func (o *RiskAuditUsageV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"characters",
		"credits_consumed",
		"processing_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskAuditUsageV2 := _RiskAuditUsageV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskAuditUsageV2)

	if err != nil {
		return err
	}

	*o = RiskAuditUsageV2(varRiskAuditUsageV2)

	return err
}

type NullableRiskAuditUsageV2 struct {
	value *RiskAuditUsageV2
	isSet bool
}

func (v NullableRiskAuditUsageV2) Get() *RiskAuditUsageV2 {
	return v.value
}

func (v *NullableRiskAuditUsageV2) Set(val *RiskAuditUsageV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditUsageV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditUsageV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditUsageV2(val *RiskAuditUsageV2) *NullableRiskAuditUsageV2 {
	return &NullableRiskAuditUsageV2{value: val, isSet: true}
}

func (v NullableRiskAuditUsageV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditUsageV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


