/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiagnosticResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticResponse{}

// DiagnosticResponse struct for DiagnosticResponse
type DiagnosticResponse struct {
	// Unique analysis identifier. Prefix 'di-' + UUID
	Id string `json:"id"`
	// Language used in the response. E.g.: 'pt-BR', 'en-US', 'es-ES'
	ResponseLanguage string `json:"response_language"`
	// Object type. Always 'analysis'
	Object string `json:"object"`
	// The 6 conversation analyses (5 + participants)
	Analysis DiagnosticAnalysisMap `json:"analysis"`
	// Usage and processing information
	Usage DiagnosticUsage `json:"usage"`
	// Client-supplied ID echoed verbatim (if provided in request)
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
}

type _DiagnosticResponse DiagnosticResponse

// NewDiagnosticResponse instantiates a new DiagnosticResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticResponse(id string, responseLanguage string, object string, analysis DiagnosticAnalysisMap, usage DiagnosticUsage) *DiagnosticResponse {
	this := DiagnosticResponse{}
	this.Id = id
	this.ResponseLanguage = responseLanguage
	this.Object = object
	this.Analysis = analysis
	this.Usage = usage
	return &this
}

// NewDiagnosticResponseWithDefaults instantiates a new DiagnosticResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticResponseWithDefaults() *DiagnosticResponse {
	this := DiagnosticResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DiagnosticResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DiagnosticResponse) SetId(v string) {
	o.Id = v
}

// GetResponseLanguage returns the ResponseLanguage field value
func (o *DiagnosticResponse) GetResponseLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseLanguage
}

// GetResponseLanguageOk returns a tuple with the ResponseLanguage field value
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetResponseLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseLanguage, true
}

// SetResponseLanguage sets field value
func (o *DiagnosticResponse) SetResponseLanguage(v string) {
	o.ResponseLanguage = v
}

// GetObject returns the Object field value
func (o *DiagnosticResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *DiagnosticResponse) SetObject(v string) {
	o.Object = v
}

// GetAnalysis returns the Analysis field value
func (o *DiagnosticResponse) GetAnalysis() DiagnosticAnalysisMap {
	if o == nil {
		var ret DiagnosticAnalysisMap
		return ret
	}

	return o.Analysis
}

// GetAnalysisOk returns a tuple with the Analysis field value
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetAnalysisOk() (*DiagnosticAnalysisMap, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Analysis, true
}

// SetAnalysis sets field value
func (o *DiagnosticResponse) SetAnalysis(v DiagnosticAnalysisMap) {
	o.Analysis = v
}

// GetUsage returns the Usage field value
func (o *DiagnosticResponse) GetUsage() DiagnosticUsage {
	if o == nil {
		var ret DiagnosticUsage
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetUsageOk() (*DiagnosticUsage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *DiagnosticResponse) SetUsage(v DiagnosticUsage) {
	o.Usage = v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *DiagnosticResponse) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticResponse) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *DiagnosticResponse) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *DiagnosticResponse) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

func (o DiagnosticResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["response_language"] = o.ResponseLanguage
	toSerialize["object"] = o.Object
	toSerialize["analysis"] = o.Analysis
	toSerialize["usage"] = o.Usage
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	return toSerialize, nil
}

func (o *DiagnosticResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"response_language",
		"object",
		"analysis",
		"usage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiagnosticResponse := _DiagnosticResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiagnosticResponse)

	if err != nil {
		return err
	}

	*o = DiagnosticResponse(varDiagnosticResponse)

	return err
}

type NullableDiagnosticResponse struct {
	value *DiagnosticResponse
	isSet bool
}

func (v NullableDiagnosticResponse) Get() *DiagnosticResponse {
	return v.value
}

func (v *NullableDiagnosticResponse) Set(val *DiagnosticResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticResponse(val *DiagnosticResponse) *NullableDiagnosticResponse {
	return &NullableDiagnosticResponse{value: val, isSet: true}
}

func (v NullableDiagnosticResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


