/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WhatsappConversationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsappConversationsResponse{}

// WhatsappConversationsResponse struct for WhatsappConversationsResponse
type WhatsappConversationsResponse struct {
	// Unique identifier. Prefix 'wc-' + UUID
	Id string `json:"id"`
	// Object type. Always 'conversations'
	Object string `json:"object"`
	// Usage and processing information
	Usage WhatsappUsage `json:"usage"`
	// Segmented conversations
	Conversations []WhatsappConversation `json:"conversations"`
	// Client-supplied ID echoed verbatim (if provided)
	ClientReferenceId *string `json:"client_reference_id,omitempty"`
	// Segmentation parameters and counts
	Meta WhatsappMeta `json:"meta"`
}

type _WhatsappConversationsResponse WhatsappConversationsResponse

// NewWhatsappConversationsResponse instantiates a new WhatsappConversationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappConversationsResponse(id string, object string, usage WhatsappUsage, conversations []WhatsappConversation, meta WhatsappMeta) *WhatsappConversationsResponse {
	this := WhatsappConversationsResponse{}
	this.Id = id
	this.Object = object
	this.Usage = usage
	this.Conversations = conversations
	this.Meta = meta
	return &this
}

// NewWhatsappConversationsResponseWithDefaults instantiates a new WhatsappConversationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappConversationsResponseWithDefaults() *WhatsappConversationsResponse {
	this := WhatsappConversationsResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WhatsappConversationsResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WhatsappConversationsResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *WhatsappConversationsResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *WhatsappConversationsResponse) SetObject(v string) {
	o.Object = v
}

// GetUsage returns the Usage field value
func (o *WhatsappConversationsResponse) GetUsage() WhatsappUsage {
	if o == nil {
		var ret WhatsappUsage
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetUsageOk() (*WhatsappUsage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *WhatsappConversationsResponse) SetUsage(v WhatsappUsage) {
	o.Usage = v
}

// GetConversations returns the Conversations field value
func (o *WhatsappConversationsResponse) GetConversations() []WhatsappConversation {
	if o == nil {
		var ret []WhatsappConversation
		return ret
	}

	return o.Conversations
}

// GetConversationsOk returns a tuple with the Conversations field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetConversationsOk() ([]WhatsappConversation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conversations, true
}

// SetConversations sets field value
func (o *WhatsappConversationsResponse) SetConversations(v []WhatsappConversation) {
	o.Conversations = v
}

// GetClientReferenceId returns the ClientReferenceId field value if set, zero value otherwise.
func (o *WhatsappConversationsResponse) GetClientReferenceId() string {
	if o == nil || IsNil(o.ClientReferenceId) {
		var ret string
		return ret
	}
	return *o.ClientReferenceId
}

// GetClientReferenceIdOk returns a tuple with the ClientReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetClientReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientReferenceId) {
		return nil, false
	}
	return o.ClientReferenceId, true
}

// HasClientReferenceId returns a boolean if a field has been set.
func (o *WhatsappConversationsResponse) HasClientReferenceId() bool {
	if o != nil && !IsNil(o.ClientReferenceId) {
		return true
	}

	return false
}

// SetClientReferenceId gets a reference to the given string and assigns it to the ClientReferenceId field.
func (o *WhatsappConversationsResponse) SetClientReferenceId(v string) {
	o.ClientReferenceId = &v
}

// GetMeta returns the Meta field value
func (o *WhatsappConversationsResponse) GetMeta() WhatsappMeta {
	if o == nil {
		var ret WhatsappMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *WhatsappConversationsResponse) GetMetaOk() (*WhatsappMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *WhatsappConversationsResponse) SetMeta(v WhatsappMeta) {
	o.Meta = v
}

func (o WhatsappConversationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsappConversationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["usage"] = o.Usage
	toSerialize["conversations"] = o.Conversations
	if !IsNil(o.ClientReferenceId) {
		toSerialize["client_reference_id"] = o.ClientReferenceId
	}
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *WhatsappConversationsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"usage",
		"conversations",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsappConversationsResponse := _WhatsappConversationsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsappConversationsResponse)

	if err != nil {
		return err
	}

	*o = WhatsappConversationsResponse(varWhatsappConversationsResponse)

	return err
}

type NullableWhatsappConversationsResponse struct {
	value *WhatsappConversationsResponse
	isSet bool
}

func (v NullableWhatsappConversationsResponse) Get() *WhatsappConversationsResponse {
	return v.value
}

func (v *NullableWhatsappConversationsResponse) Set(val *WhatsappConversationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappConversationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappConversationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappConversationsResponse(val *WhatsappConversationsResponse) *NullableWhatsappConversationsResponse {
	return &NullableWhatsappConversationsResponse{value: val, isSet: true}
}

func (v NullableWhatsappConversationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappConversationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


