/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditAudioEventModelV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditAudioEventModelV2{}

// RiskAuditAudioEventModelV2 struct for RiskAuditAudioEventModelV2
type RiskAuditAudioEventModelV2 struct {
	// MAC model text (i18n)
	Model *string `json:"model,omitempty"`
	// MAC description (i18n)
	Description *string `json:"description,omitempty"`
	// Temporal windows (s)
	WindowsS map[string]interface{} `json:"windows_s,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskAuditAudioEventModelV2 RiskAuditAudioEventModelV2

// NewRiskAuditAudioEventModelV2 instantiates a new RiskAuditAudioEventModelV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditAudioEventModelV2() *RiskAuditAudioEventModelV2 {
	this := RiskAuditAudioEventModelV2{}
	var model string = ""
	this.Model = &model
	var description string = ""
	this.Description = &description
	return &this
}

// NewRiskAuditAudioEventModelV2WithDefaults instantiates a new RiskAuditAudioEventModelV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditAudioEventModelV2WithDefaults() *RiskAuditAudioEventModelV2 {
	this := RiskAuditAudioEventModelV2{}
	var model string = ""
	this.Model = &model
	var description string = ""
	this.Description = &description
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *RiskAuditAudioEventModelV2) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAudioEventModelV2) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *RiskAuditAudioEventModelV2) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *RiskAuditAudioEventModelV2) SetModel(v string) {
	o.Model = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RiskAuditAudioEventModelV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAudioEventModelV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RiskAuditAudioEventModelV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RiskAuditAudioEventModelV2) SetDescription(v string) {
	o.Description = &v
}

// GetWindowsS returns the WindowsS field value if set, zero value otherwise.
func (o *RiskAuditAudioEventModelV2) GetWindowsS() map[string]interface{} {
	if o == nil || IsNil(o.WindowsS) {
		var ret map[string]interface{}
		return ret
	}
	return o.WindowsS
}

// GetWindowsSOk returns a tuple with the WindowsS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAudioEventModelV2) GetWindowsSOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WindowsS) {
		return map[string]interface{}{}, false
	}
	return o.WindowsS, true
}

// HasWindowsS returns a boolean if a field has been set.
func (o *RiskAuditAudioEventModelV2) HasWindowsS() bool {
	if o != nil && !IsNil(o.WindowsS) {
		return true
	}

	return false
}

// SetWindowsS gets a reference to the given map[string]interface{} and assigns it to the WindowsS field.
func (o *RiskAuditAudioEventModelV2) SetWindowsS(v map[string]interface{}) {
	o.WindowsS = v
}

func (o RiskAuditAudioEventModelV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditAudioEventModelV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WindowsS) {
		toSerialize["windows_s"] = o.WindowsS
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskAuditAudioEventModelV2) UnmarshalJSON(data []byte) (err error) {
	varRiskAuditAudioEventModelV2 := _RiskAuditAudioEventModelV2{}

	err = json.Unmarshal(data, &varRiskAuditAudioEventModelV2)

	if err != nil {
		return err
	}

	*o = RiskAuditAudioEventModelV2(varRiskAuditAudioEventModelV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "model")
		delete(additionalProperties, "description")
		delete(additionalProperties, "windows_s")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskAuditAudioEventModelV2 struct {
	value *RiskAuditAudioEventModelV2
	isSet bool
}

func (v NullableRiskAuditAudioEventModelV2) Get() *RiskAuditAudioEventModelV2 {
	return v.value
}

func (v *NullableRiskAuditAudioEventModelV2) Set(val *RiskAuditAudioEventModelV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditAudioEventModelV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditAudioEventModelV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditAudioEventModelV2(val *RiskAuditAudioEventModelV2) *NullableRiskAuditAudioEventModelV2 {
	return &NullableRiskAuditAudioEventModelV2{value: val, isSet: true}
}

func (v NullableRiskAuditAudioEventModelV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditAudioEventModelV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


