/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.49
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the DiagnosticTextAnalysis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiagnosticTextAnalysis{}

// DiagnosticTextAnalysis struct for DiagnosticTextAnalysis
type DiagnosticTextAnalysis struct {
	// Explanatory text (used in summary and reason)
	Explanation *string `json:"explanation,omitempty"`
}

// NewDiagnosticTextAnalysis instantiates a new DiagnosticTextAnalysis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticTextAnalysis() *DiagnosticTextAnalysis {
	this := DiagnosticTextAnalysis{}
	return &this
}

// NewDiagnosticTextAnalysisWithDefaults instantiates a new DiagnosticTextAnalysis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticTextAnalysisWithDefaults() *DiagnosticTextAnalysis {
	this := DiagnosticTextAnalysis{}
	return &this
}

// GetExplanation returns the Explanation field value if set, zero value otherwise.
func (o *DiagnosticTextAnalysis) GetExplanation() string {
	if o == nil || IsNil(o.Explanation) {
		var ret string
		return ret
	}
	return *o.Explanation
}

// GetExplanationOk returns a tuple with the Explanation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticTextAnalysis) GetExplanationOk() (*string, bool) {
	if o == nil || IsNil(o.Explanation) {
		return nil, false
	}
	return o.Explanation, true
}

// HasExplanation returns a boolean if a field has been set.
func (o *DiagnosticTextAnalysis) HasExplanation() bool {
	if o != nil && !IsNil(o.Explanation) {
		return true
	}

	return false
}

// SetExplanation gets a reference to the given string and assigns it to the Explanation field.
func (o *DiagnosticTextAnalysis) SetExplanation(v string) {
	o.Explanation = &v
}

func (o DiagnosticTextAnalysis) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiagnosticTextAnalysis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Explanation) {
		toSerialize["explanation"] = o.Explanation
	}
	return toSerialize, nil
}

type NullableDiagnosticTextAnalysis struct {
	value *DiagnosticTextAnalysis
	isSet bool
}

func (v NullableDiagnosticTextAnalysis) Get() *DiagnosticTextAnalysis {
	return v.value
}

func (v *NullableDiagnosticTextAnalysis) Set(val *DiagnosticTextAnalysis) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticTextAnalysis) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticTextAnalysis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticTextAnalysis(val *DiagnosticTextAnalysis) *NullableDiagnosticTextAnalysis {
	return &NullableDiagnosticTextAnalysis{value: val, isSet: true}
}

func (v NullableDiagnosticTextAnalysis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticTextAnalysis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


