/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
)

// checks if the RiskAuditAuditDecisionsV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskAuditAuditDecisionsV2{}

// RiskAuditAuditDecisionsV2 struct for RiskAuditAuditDecisionsV2
type RiskAuditAuditDecisionsV2 struct {
	// Risk origin
	RiskOrigin *string `json:"risk_origin,omitempty"`
	// Has zero-tolerance violation
	HasZeroToleranceViolation *bool `json:"has_zero_tolerance_violation,omitempty"`
	// Deterministic validator changes
	DeterministicValidatorChanges []interface{} `json:"deterministic_validator_changes,omitempty"`
}

// NewRiskAuditAuditDecisionsV2 instantiates a new RiskAuditAuditDecisionsV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskAuditAuditDecisionsV2() *RiskAuditAuditDecisionsV2 {
	this := RiskAuditAuditDecisionsV2{}
	return &this
}

// NewRiskAuditAuditDecisionsV2WithDefaults instantiates a new RiskAuditAuditDecisionsV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskAuditAuditDecisionsV2WithDefaults() *RiskAuditAuditDecisionsV2 {
	this := RiskAuditAuditDecisionsV2{}
	return &this
}

// GetRiskOrigin returns the RiskOrigin field value if set, zero value otherwise.
func (o *RiskAuditAuditDecisionsV2) GetRiskOrigin() string {
	if o == nil || IsNil(o.RiskOrigin) {
		var ret string
		return ret
	}
	return *o.RiskOrigin
}

// GetRiskOriginOk returns a tuple with the RiskOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAuditDecisionsV2) GetRiskOriginOk() (*string, bool) {
	if o == nil || IsNil(o.RiskOrigin) {
		return nil, false
	}
	return o.RiskOrigin, true
}

// HasRiskOrigin returns a boolean if a field has been set.
func (o *RiskAuditAuditDecisionsV2) HasRiskOrigin() bool {
	if o != nil && !IsNil(o.RiskOrigin) {
		return true
	}

	return false
}

// SetRiskOrigin gets a reference to the given string and assigns it to the RiskOrigin field.
func (o *RiskAuditAuditDecisionsV2) SetRiskOrigin(v string) {
	o.RiskOrigin = &v
}

// GetHasZeroToleranceViolation returns the HasZeroToleranceViolation field value if set, zero value otherwise.
func (o *RiskAuditAuditDecisionsV2) GetHasZeroToleranceViolation() bool {
	if o == nil || IsNil(o.HasZeroToleranceViolation) {
		var ret bool
		return ret
	}
	return *o.HasZeroToleranceViolation
}

// GetHasZeroToleranceViolationOk returns a tuple with the HasZeroToleranceViolation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAuditDecisionsV2) GetHasZeroToleranceViolationOk() (*bool, bool) {
	if o == nil || IsNil(o.HasZeroToleranceViolation) {
		return nil, false
	}
	return o.HasZeroToleranceViolation, true
}

// HasHasZeroToleranceViolation returns a boolean if a field has been set.
func (o *RiskAuditAuditDecisionsV2) HasHasZeroToleranceViolation() bool {
	if o != nil && !IsNil(o.HasZeroToleranceViolation) {
		return true
	}

	return false
}

// SetHasZeroToleranceViolation gets a reference to the given bool and assigns it to the HasZeroToleranceViolation field.
func (o *RiskAuditAuditDecisionsV2) SetHasZeroToleranceViolation(v bool) {
	o.HasZeroToleranceViolation = &v
}

// GetDeterministicValidatorChanges returns the DeterministicValidatorChanges field value if set, zero value otherwise.
func (o *RiskAuditAuditDecisionsV2) GetDeterministicValidatorChanges() []interface{} {
	if o == nil || IsNil(o.DeterministicValidatorChanges) {
		var ret []interface{}
		return ret
	}
	return o.DeterministicValidatorChanges
}

// GetDeterministicValidatorChangesOk returns a tuple with the DeterministicValidatorChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskAuditAuditDecisionsV2) GetDeterministicValidatorChangesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.DeterministicValidatorChanges) {
		return nil, false
	}
	return o.DeterministicValidatorChanges, true
}

// HasDeterministicValidatorChanges returns a boolean if a field has been set.
func (o *RiskAuditAuditDecisionsV2) HasDeterministicValidatorChanges() bool {
	if o != nil && !IsNil(o.DeterministicValidatorChanges) {
		return true
	}

	return false
}

// SetDeterministicValidatorChanges gets a reference to the given []interface{} and assigns it to the DeterministicValidatorChanges field.
func (o *RiskAuditAuditDecisionsV2) SetDeterministicValidatorChanges(v []interface{}) {
	o.DeterministicValidatorChanges = v
}

func (o RiskAuditAuditDecisionsV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskAuditAuditDecisionsV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RiskOrigin) {
		toSerialize["risk_origin"] = o.RiskOrigin
	}
	if !IsNil(o.HasZeroToleranceViolation) {
		toSerialize["has_zero_tolerance_violation"] = o.HasZeroToleranceViolation
	}
	if !IsNil(o.DeterministicValidatorChanges) {
		toSerialize["deterministic_validator_changes"] = o.DeterministicValidatorChanges
	}
	return toSerialize, nil
}

type NullableRiskAuditAuditDecisionsV2 struct {
	value *RiskAuditAuditDecisionsV2
	isSet bool
}

func (v NullableRiskAuditAuditDecisionsV2) Get() *RiskAuditAuditDecisionsV2 {
	return v.value
}

func (v *NullableRiskAuditAuditDecisionsV2) Set(val *RiskAuditAuditDecisionsV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskAuditAuditDecisionsV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskAuditAuditDecisionsV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskAuditAuditDecisionsV2(val *RiskAuditAuditDecisionsV2) *NullableRiskAuditAuditDecisionsV2 {
	return &NullableRiskAuditAuditDecisionsV2{value: val, isSet: true}
}

func (v NullableRiskAuditAuditDecisionsV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskAuditAuditDecisionsV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


