/*
FalaAI API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.21.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package falaai

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantDiagnostic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantDiagnostic{}

// ParticipantDiagnostic struct for ParticipantDiagnostic
type ParticipantDiagnostic struct {
	// Exact speaker label from the dialog (e.g. 'Speaker 1')
	Interlocutor string `json:"interlocutor"`
	// Role: agent | client | bot | agent_requester | agent_custodian
	Role string `json:"role"`
	// Participant name if mentioned in the dialogue
	Name *string `json:"name,omitempty"`
	// high | medium | low
	Confidence *string `json:"confidence,omitempty"`
	// Exact verbatim quote supporting the role (no timestamps)
	Evidence *string `json:"evidence,omitempty"`
}

type _ParticipantDiagnostic ParticipantDiagnostic

// NewParticipantDiagnostic instantiates a new ParticipantDiagnostic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantDiagnostic(interlocutor string, role string) *ParticipantDiagnostic {
	this := ParticipantDiagnostic{}
	this.Interlocutor = interlocutor
	this.Role = role
	return &this
}

// NewParticipantDiagnosticWithDefaults instantiates a new ParticipantDiagnostic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantDiagnosticWithDefaults() *ParticipantDiagnostic {
	this := ParticipantDiagnostic{}
	return &this
}

// GetInterlocutor returns the Interlocutor field value
func (o *ParticipantDiagnostic) GetInterlocutor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interlocutor
}

// GetInterlocutorOk returns a tuple with the Interlocutor field value
// and a boolean to check if the value has been set.
func (o *ParticipantDiagnostic) GetInterlocutorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interlocutor, true
}

// SetInterlocutor sets field value
func (o *ParticipantDiagnostic) SetInterlocutor(v string) {
	o.Interlocutor = v
}

// GetRole returns the Role field value
func (o *ParticipantDiagnostic) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ParticipantDiagnostic) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ParticipantDiagnostic) SetRole(v string) {
	o.Role = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ParticipantDiagnostic) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantDiagnostic) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ParticipantDiagnostic) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ParticipantDiagnostic) SetName(v string) {
	o.Name = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *ParticipantDiagnostic) GetConfidence() string {
	if o == nil || IsNil(o.Confidence) {
		var ret string
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantDiagnostic) GetConfidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *ParticipantDiagnostic) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given string and assigns it to the Confidence field.
func (o *ParticipantDiagnostic) SetConfidence(v string) {
	o.Confidence = &v
}

// GetEvidence returns the Evidence field value if set, zero value otherwise.
func (o *ParticipantDiagnostic) GetEvidence() string {
	if o == nil || IsNil(o.Evidence) {
		var ret string
		return ret
	}
	return *o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantDiagnostic) GetEvidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Evidence) {
		return nil, false
	}
	return o.Evidence, true
}

// HasEvidence returns a boolean if a field has been set.
func (o *ParticipantDiagnostic) HasEvidence() bool {
	if o != nil && !IsNil(o.Evidence) {
		return true
	}

	return false
}

// SetEvidence gets a reference to the given string and assigns it to the Evidence field.
func (o *ParticipantDiagnostic) SetEvidence(v string) {
	o.Evidence = &v
}

func (o ParticipantDiagnostic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantDiagnostic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["interlocutor"] = o.Interlocutor
	toSerialize["role"] = o.Role
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Evidence) {
		toSerialize["evidence"] = o.Evidence
	}
	return toSerialize, nil
}

func (o *ParticipantDiagnostic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interlocutor",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantDiagnostic := _ParticipantDiagnostic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantDiagnostic)

	if err != nil {
		return err
	}

	*o = ParticipantDiagnostic(varParticipantDiagnostic)

	return err
}

type NullableParticipantDiagnostic struct {
	value *ParticipantDiagnostic
	isSet bool
}

func (v NullableParticipantDiagnostic) Get() *ParticipantDiagnostic {
	return v.value
}

func (v *NullableParticipantDiagnostic) Set(val *ParticipantDiagnostic) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantDiagnostic) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantDiagnostic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantDiagnostic(val *ParticipantDiagnostic) *NullableParticipantDiagnostic {
	return &NullableParticipantDiagnostic{value: val, isSet: true}
}

func (v NullableParticipantDiagnostic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantDiagnostic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


